openapi: "3.1.0"
info:
  title: ZeroBin API
  description: Set of APIs to test the Zero Trust primitives
  version: 0.0.1
servers: 
  - url: http://zerobin.spilikin.dev/
    description: Development server
paths:
  /echo:
    get:
      summary: Echoes back the request
      description: Echoes back the request including headers, method, path, query, and optional MTLS certificate
      responses:
        '200':
          description: Echoes back the request
          content:
            application/json:
              schema:
                type: object
                properties:
                  headers:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
                  host:
                    type: string
                  metadata:
                    type: object
                    additionalProperties:
                      type: string
                  method:
                    type: string
                  proto:
                    type: string
                  remoteAddr:
                    type: string
                  requestURI:
                    type: string
                  tlsCipherSuite:
                    type: string
                  tlsClientCertificates:
                    type: array
                    items:
                      type: object
                      properties:
                        issuer:
                          type: string
                        notAfter:
                          type: string
                        notBefore:
                          type: string
                        subject:
                          type: string
                  tlsHostname:
                    type: string
                  tlsVersion:
                    type: string





 
