// Code generated by wsdl2openapi; DO NOT EDIT.

/// `SOAP-ENV:Body` content of a `ExternalAuthenticate` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub enum ExternalAuthenticateInput {
    #[serde(rename = "signatureservice74:ExternalAuthenticate")]
    ExternalAuthenticate(crate::api::gematik::conn::signatureservice74::ExternalAuthenticate),
}

impl crate::api::soap::BodyContent for ExternalAuthenticateInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:connectorcommon50",
            "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
        ),
        (
            "@xmlns:connectorcontext20",
            "http://ws.gematik.de/conn/ConnectorContext/v2.0",
        ),
        ("@xmlns:dss10core", "urn:oasis:names:tc:dss:1.0:core:schema"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
        ("@xmlns:ns-xmldsig", "http://www.w3.org/2000/09/xmldsig#"),
        (
            "@xmlns:signatureservice74",
            "http://ws.gematik.de/conn/SignatureService/v7.4",
        ),
    ];
}

impl crate::api::soap::SoapRequest for ExternalAuthenticateInput {
    const OPERATION: crate::api::soap::SoapOperation = crate::api::soap::SoapOperation {
        name: "ExternalAuthenticate",
        soap_action: "http://ws.gematik.de/conn/SignatureService/v7.4#ExternalAuthenticate",
        binding_type: "soap11",
        service: "AuthSignatureService",
        version: "7.4",
        timeout: crate::api::soap::Timeout::Long,
    };
    type Response = ExternalAuthenticateOutput;
}

impl From<crate::api::gematik::conn::signatureservice74::ExternalAuthenticate>
    for ExternalAuthenticateInput
{
    fn from(request: crate::api::gematik::conn::signatureservice74::ExternalAuthenticate) -> Self {
        Self::ExternalAuthenticate(request)
    }
}

impl From<crate::api::gematik::conn::signatureservice74::ExternalAuthenticate>
    for crate::api::soap::Envelope<ExternalAuthenticateInput>
{
    fn from(request: crate::api::gematik::conn::signatureservice74::ExternalAuthenticate) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `ExternalAuthenticate` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum ExternalAuthenticateOutput {
    #[serde(rename = "ExternalAuthenticateResponse")]
    ExternalAuthenticateResponse(
        crate::api::gematik::conn::signatureservice74::ExternalAuthenticateResponse,
    ),
    #[serde(rename = "Fault")]
    Fault(crate::api::soap::Fault<ExternalAuthenticateFaultDetail>),
}

impl crate::api::soap::SoapResponse for ExternalAuthenticateOutput {
    type Success = crate::api::gematik::conn::signatureservice74::ExternalAuthenticateResponse;
    type Detail = ExternalAuthenticateFaultDetail;
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
    #[allow(clippy::result_large_err)]
    fn into_result(
        self,
    ) -> Result<
        crate::api::gematik::conn::signatureservice74::ExternalAuthenticateResponse,
        crate::api::soap::Fault<ExternalAuthenticateFaultDetail>,
    > {
        match self {
            Self::ExternalAuthenticateResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

/// Typed `detail` content of a `ExternalAuthenticate` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ExternalAuthenticateFaultDetail {
    #[serde(rename = "Error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<crate::api::gematik::tel::error20::Error>,
}

pub type ExternalAuthenticateEnvelope = crate::api::soap::Envelope<ExternalAuthenticateInput>;

pub type ExternalAuthenticateResponseEnvelope =
    crate::api::soap::Envelope<ExternalAuthenticateOutput>;
