// Code generated by wsdl2openapi; DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct Cards {
    #[serde(rename = "Card", default, skip_serializing_if = "Vec::is_empty")]
    pub card: Vec<Card>,
}

pub type Card = CardInfoType;

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct VersionInfoType {
    #[serde(rename = "Major")]
    pub major: i64,
    #[serde(rename = "Minor")]
    pub minor: i64,
    #[serde(rename = "Revision")]
    pub revision: i64,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct CardInfoType {
    #[serde(rename = "CardHandle")]
    pub card_handle: String,
    #[serde(rename = "CardType")]
    pub card_type: crate::api::gematik::conn::cardservicecommon20::CardType,
    #[serde(
        rename = "CardVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub card_version: Option<CardInfoTypeCardVersion>,
    #[serde(rename = "Iccsn", default, skip_serializing_if = "Option::is_none")]
    pub iccsn: Option<String>,
    #[serde(rename = "CtId")]
    pub ct_id: String,
    #[serde(rename = "SlotId")]
    pub slot_id: i64,
    #[serde(rename = "InsertTime")]
    pub insert_time: String,
    #[serde(
        rename = "CardHolderName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub card_holder_name: Option<String>,
    #[serde(rename = "Kvnr", default, skip_serializing_if = "Option::is_none")]
    pub kvnr: Option<String>,
    #[serde(
        rename = "CertificateExpirationDate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub certificate_expiration_date: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct CardInfoTypeCardVersion {
    #[serde(rename = "COSVersion")]
    pub cos_version: VersionInfoType,
    #[serde(rename = "ObjectSystemVersion")]
    pub object_system_version: VersionInfoType,
    #[serde(
        rename = "CardPTPersVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub card_pt_pers_version: Option<VersionInfoType>,
    #[serde(
        rename = "DataStructureVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub data_structure_version: Option<VersionInfoType>,
    #[serde(
        rename = "LoggingVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub logging_version: Option<VersionInfoType>,
    #[serde(
        rename = "ATRVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub atr_version: Option<VersionInfoType>,
    #[serde(
        rename = "GDOVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub gdo_version: Option<VersionInfoType>,
    #[serde(
        rename = "KeyInfoVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub key_info_version: Option<VersionInfoType>,
}
