// Code generated by wsdl2openapi; DO NOT EDIT.

pub type CardType = CardTypeType;

pub type PinResult = PinResultEnum;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CardTypeType {
    Egk,
    HbaQSig,
    Hba,
    SmcB,
    HsmB,
    SmcKt,
    Kvk,
    Zod20,
    Unknown,
    HbAx,
    SmB,
}

impl CardTypeType {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Egk => "EGK",
            Self::HbaQSig => "HBA-qSig",
            Self::Hba => "HBA",
            Self::SmcB => "SMC-B",
            Self::HsmB => "HSM-B",
            Self::SmcKt => "SMC-KT",
            Self::Kvk => "KVK",
            Self::Zod20 => "ZOD_2.0",
            Self::Unknown => "UNKNOWN",
            Self::HbAx => "HBAx",
            Self::SmB => "SM-B",
        }
    }
}

impl ::std::fmt::Display for CardTypeType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl ::std::str::FromStr for CardTypeType {
    type Err = crate::api::soap::UnknownEnumValue;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "EGK" => Ok(Self::Egk),
            "HBA-qSig" => Ok(Self::HbaQSig),
            "HBA" => Ok(Self::Hba),
            "SMC-B" => Ok(Self::SmcB),
            "HSM-B" => Ok(Self::HsmB),
            "SMC-KT" => Ok(Self::SmcKt),
            "KVK" => Ok(Self::Kvk),
            "ZOD_2.0" => Ok(Self::Zod20),
            "UNKNOWN" => Ok(Self::Unknown),
            "HBAx" => Ok(Self::HbAx),
            "SM-B" => Ok(Self::SmB),
            _ => Err(crate::api::soap::UnknownEnumValue {
                type_name: "CardTypeType",
                value: value.to_owned(),
            }),
        }
    }
}

impl ::serde::Serialize for CardTypeType {
    fn serialize<S: ::serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> ::serde::Deserialize<'de> for CardTypeType {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <String as ::serde::Deserialize>::deserialize(deserializer)?;
        value.parse().map_err(::serde::de::Error::custom)
    }
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct PinResponseType {
    #[serde(rename = "Status")]
    pub status: crate::api::gematik::conn::connectorcommon50::Status,
    #[serde(rename = "PinResult")]
    pub pin_result: PinResult,
    #[serde(rename = "LeftTries", default, skip_serializing_if = "Option::is_none")]
    pub left_tries: Option<i64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PinResultEnum {
    Error,
    Ok,
    Rejected,
    Wasblocked,
    Nowblocked,
    TransportPin,
}

impl PinResultEnum {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Error => "ERROR",
            Self::Ok => "OK",
            Self::Rejected => "REJECTED",
            Self::Wasblocked => "WASBLOCKED",
            Self::Nowblocked => "NOWBLOCKED",
            Self::TransportPin => "TRANSPORT_PIN",
        }
    }
}

impl ::std::fmt::Display for PinResultEnum {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl ::std::str::FromStr for PinResultEnum {
    type Err = crate::api::soap::UnknownEnumValue;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "ERROR" => Ok(Self::Error),
            "OK" => Ok(Self::Ok),
            "REJECTED" => Ok(Self::Rejected),
            "WASBLOCKED" => Ok(Self::Wasblocked),
            "NOWBLOCKED" => Ok(Self::Nowblocked),
            "TRANSPORT_PIN" => Ok(Self::TransportPin),
            _ => Err(crate::api::soap::UnknownEnumValue {
                type_name: "PinResultEnum",
                value: value.to_owned(),
            }),
        }
    }
}

impl<'de> ::serde::Deserialize<'de> for PinResultEnum {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <String as ::serde::Deserialize>::deserialize(deserializer)?;
        value.parse().map_err(::serde::de::Error::custom)
    }
}
