// Code generated by wsdl2openapi; DO NOT EDIT.

pub type CardTerminal = CardTerminalInfoType;

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct CardTerminalInfoType {
    #[serde(rename = "ProductInformation")]
    pub product_information:
        crate::api::gematik::int::version::productinformation11::ProductInformation,
    #[serde(rename = "CtId")]
    pub ct_id: String,
    #[serde(rename = "WorkplaceIds")]
    pub workplace_ids: crate::api::gematik::conn::connectorcommon50::WorkplaceIds,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "MacAddress")]
    pub mac_address: String,
    #[serde(rename = "IPAddress", default, skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<CardTerminalInfoTypeIpAddress>,
    #[serde(rename = "Slots")]
    pub slots: i64,
    #[serde(rename = "IS_PHYSICAL")]
    pub is_physical: bool,
    #[serde(rename = "Connected")]
    pub connected: bool,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct CardTerminalInfoTypeIpAddress {
    #[serde(
        rename = "IPV4Address",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ipv4_address: Option<String>,
    #[serde(
        rename = "IPV6Address",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ipv6_address: Option<String>,
}
