// Code generated by wsdl2openapi; DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct StartCardSession {
    #[serde(rename = "connectorcontext20:Context")]
    pub context: crate::api::gematik::conn::connectorcontext20::Context,
    #[serde(rename = "connectorcommon50:CardHandle")]
    pub card_handle: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct StartCardSessionResponse {
    #[serde(rename = "Status")]
    pub status: crate::api::gematik::conn::connectorcommon50::Status,
    #[serde(rename = "SessionId")]
    pub session_id: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct SecureSendApdu {
    #[serde(
        rename = "cardservice821:SignedScenario",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signed_scenario: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct SecureSendApduResponse {
    #[serde(rename = "Status")]
    pub status: crate::api::gematik::conn::connectorcommon50::Status,
    #[serde(
        rename = "SignedScenarioResponse",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signed_scenario_response: Option<SignedScenarioResponseType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct StopCardSession {
    #[serde(rename = "cardservice821:SessionId")]
    pub session_id: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct StopCardSessionResponse {
    #[serde(rename = "Status")]
    pub status: crate::api::gematik::conn::connectorcommon50::Status,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct SignedScenarioResponseType {
    #[serde(rename = "ResponseApduList")]
    pub response_apdu_list: SignedScenarioResponseTypeResponseApduList,
    #[serde(rename = "TimeSpan")]
    pub time_span: i64,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct SignedScenarioResponseTypeResponseApduList {
    #[serde(
        rename = "ResponseApdu",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub response_apdu: Vec<String>,
}

/// `SOAP-ENV:Body` content of a `SecureSendAPDU` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub enum SecureSendApduInput {
    #[serde(rename = "cardservice821:SecureSendAPDU")]
    SecureSendApdu(SecureSendApdu),
}

impl crate::api::soap::BodyContent for SecureSendApduInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:cardservice821",
            "http://ws.gematik.de/conn/CardService/v8.2",
        ),
        (
            "@xmlns:connectorcommon50",
            "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
        ),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::api::soap::SoapRequest for SecureSendApduInput {
    const OPERATION: crate::api::soap::SoapOperation = crate::api::soap::SoapOperation {
        name: "SecureSendAPDU",
        soap_action: "http://ws.gematik.de/conn/CardService/v8.2#SecureSendAPDU",
        binding_type: "soap11",
        service: "CardService",
        version: "8.2",
        timeout: crate::api::soap::Timeout::Long,
    };
    type Response = SecureSendApduOutput;
}

impl From<SecureSendApdu> for SecureSendApduInput {
    fn from(request: SecureSendApdu) -> Self {
        Self::SecureSendApdu(request)
    }
}

impl From<SecureSendApdu> for crate::api::soap::Envelope<SecureSendApduInput> {
    fn from(request: SecureSendApdu) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `SecureSendAPDU` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum SecureSendApduOutput {
    #[serde(rename = "SecureSendAPDUResponse")]
    SecureSendApduResponse(SecureSendApduResponse),
    #[serde(rename = "Fault")]
    Fault(crate::api::soap::Fault<SecureSendApduFaultDetail>),
}

impl crate::api::soap::SoapResponse for SecureSendApduOutput {
    type Success = SecureSendApduResponse;
    type Detail = SecureSendApduFaultDetail;
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
    #[allow(clippy::result_large_err)]
    fn into_result(
        self,
    ) -> Result<SecureSendApduResponse, crate::api::soap::Fault<SecureSendApduFaultDetail>> {
        match self {
            Self::SecureSendApduResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

/// Typed `detail` content of a `SecureSendAPDU` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct SecureSendApduFaultDetail {
    #[serde(rename = "Error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<crate::api::gematik::tel::error20::Error>,
}

pub type SecureSendApduEnvelope = crate::api::soap::Envelope<SecureSendApduInput>;

pub type SecureSendApduResponseEnvelope = crate::api::soap::Envelope<SecureSendApduOutput>;

/// `SOAP-ENV:Body` content of a `StartCardSession` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub enum StartCardSessionInput {
    #[serde(rename = "cardservice821:StartCardSession")]
    StartCardSession(StartCardSession),
}

impl crate::api::soap::BodyContent for StartCardSessionInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:cardservice821",
            "http://ws.gematik.de/conn/CardService/v8.2",
        ),
        (
            "@xmlns:connectorcommon50",
            "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
        ),
        (
            "@xmlns:connectorcontext20",
            "http://ws.gematik.de/conn/ConnectorContext/v2.0",
        ),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::api::soap::SoapRequest for StartCardSessionInput {
    const OPERATION: crate::api::soap::SoapOperation = crate::api::soap::SoapOperation {
        name: "StartCardSession",
        soap_action: "http://ws.gematik.de/conn/CardService/v8.2#StartCardSession",
        binding_type: "soap11",
        service: "CardService",
        version: "8.2",
        timeout: crate::api::soap::Timeout::Short,
    };
    type Response = StartCardSessionOutput;
}

impl From<StartCardSession> for StartCardSessionInput {
    fn from(request: StartCardSession) -> Self {
        Self::StartCardSession(request)
    }
}

impl From<StartCardSession> for crate::api::soap::Envelope<StartCardSessionInput> {
    fn from(request: StartCardSession) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `StartCardSession` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum StartCardSessionOutput {
    #[serde(rename = "StartCardSessionResponse")]
    StartCardSessionResponse(StartCardSessionResponse),
    #[serde(rename = "Fault")]
    Fault(crate::api::soap::Fault<StartCardSessionFaultDetail>),
}

impl crate::api::soap::SoapResponse for StartCardSessionOutput {
    type Success = StartCardSessionResponse;
    type Detail = StartCardSessionFaultDetail;
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
    #[allow(clippy::result_large_err)]
    fn into_result(
        self,
    ) -> Result<StartCardSessionResponse, crate::api::soap::Fault<StartCardSessionFaultDetail>>
    {
        match self {
            Self::StartCardSessionResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

/// Typed `detail` content of a `StartCardSession` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct StartCardSessionFaultDetail {
    #[serde(rename = "Error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<crate::api::gematik::tel::error20::Error>,
}

pub type StartCardSessionEnvelope = crate::api::soap::Envelope<StartCardSessionInput>;

pub type StartCardSessionResponseEnvelope = crate::api::soap::Envelope<StartCardSessionOutput>;

/// `SOAP-ENV:Body` content of a `StopCardSession` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub enum StopCardSessionInput {
    #[serde(rename = "cardservice821:StopCardSession")]
    StopCardSession(StopCardSession),
}

impl crate::api::soap::BodyContent for StopCardSessionInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:cardservice821",
            "http://ws.gematik.de/conn/CardService/v8.2",
        ),
        (
            "@xmlns:connectorcommon50",
            "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
        ),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::api::soap::SoapRequest for StopCardSessionInput {
    const OPERATION: crate::api::soap::SoapOperation = crate::api::soap::SoapOperation {
        name: "StopCardSession",
        soap_action: "http://ws.gematik.de/conn/CardService/v8.2#StopCardSession",
        binding_type: "soap11",
        service: "CardService",
        version: "8.2",
        timeout: crate::api::soap::Timeout::Short,
    };
    type Response = StopCardSessionOutput;
}

impl From<StopCardSession> for StopCardSessionInput {
    fn from(request: StopCardSession) -> Self {
        Self::StopCardSession(request)
    }
}

impl From<StopCardSession> for crate::api::soap::Envelope<StopCardSessionInput> {
    fn from(request: StopCardSession) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `StopCardSession` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum StopCardSessionOutput {
    #[serde(rename = "StopCardSessionResponse")]
    StopCardSessionResponse(StopCardSessionResponse),
    #[serde(rename = "Fault")]
    Fault(crate::api::soap::Fault<StopCardSessionFaultDetail>),
}

impl crate::api::soap::SoapResponse for StopCardSessionOutput {
    type Success = StopCardSessionResponse;
    type Detail = StopCardSessionFaultDetail;
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
    #[allow(clippy::result_large_err)]
    fn into_result(
        self,
    ) -> Result<StopCardSessionResponse, crate::api::soap::Fault<StopCardSessionFaultDetail>> {
        match self {
            Self::StopCardSessionResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

/// Typed `detail` content of a `StopCardSession` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct StopCardSessionFaultDetail {
    #[serde(rename = "Error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<crate::api::gematik::tel::error20::Error>,
}

pub type StopCardSessionEnvelope = crate::api::soap::Envelope<StopCardSessionInput>;

pub type StopCardSessionResponseEnvelope = crate::api::soap::Envelope<StopCardSessionOutput>;
