// Code generated by wsdl2openapi; DO NOT EDIT.

pub type X509DataInfoList = X509DataInfoListType;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CertRefEnum {
    CAut,
    CEnc,
    CSig,
    CQes,
}

impl CertRefEnum {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::CAut => "C.AUT",
            Self::CEnc => "C.ENC",
            Self::CSig => "C.SIG",
            Self::CQes => "C.QES",
        }
    }
}

impl ::std::fmt::Display for CertRefEnum {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl ::std::str::FromStr for CertRefEnum {
    type Err = crate::api::soap::UnknownEnumValue;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "C.AUT" => Ok(Self::CAut),
            "C.ENC" => Ok(Self::CEnc),
            "C.SIG" => Ok(Self::CSig),
            "C.QES" => Ok(Self::CQes),
            _ => Err(crate::api::soap::UnknownEnumValue {
                type_name: "CertRefEnum",
                value: value.to_owned(),
            }),
        }
    }
}

impl<'de> ::serde::Deserialize<'de> for CertRefEnum {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <String as ::serde::Deserialize>::deserialize(deserializer)?;
        value.parse().map_err(::serde::de::Error::custom)
    }
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct X509DataInfoListType {
    #[serde(
        rename = "X509DataInfo",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub x509_data_info: Vec<X509DataInfoListTypeX509DataInfo>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct X509DataInfoListTypeX509DataInfo {
    #[serde(rename = "CertRef")]
    pub cert_ref: CertRefEnum,
    #[serde(rename = "X509Data", default, skip_serializing_if = "Option::is_none")]
    pub x509_data: Option<X509DataInfoListTypeX509DataInfoX509Data>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct X509DataInfoListTypeX509DataInfoX509Data {
    #[serde(rename = "X509IssuerSerial")]
    pub x509_issuer_serial: X509DataInfoListTypeX509DataInfoX509DataX509IssuerSerial,
    #[serde(rename = "X509SubjectName")]
    pub x509_subject_name: String,
    #[serde(rename = "X509Certificate")]
    pub x509_certificate: crate::api::soap::Base64Binary,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct X509DataInfoListTypeX509DataInfoX509DataX509IssuerSerial {
    #[serde(rename = "X509IssuerName")]
    pub x509_issuer_name: String,
    #[serde(rename = "X509SerialNumber")]
    pub x509_serial_number: String,
}
