// Code generated by wsdl2openapi; DO NOT EDIT.

pub type Context = ContextType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct ContextType {
    #[serde(rename = "connectorcommon50:MandantId")]
    pub mandant_id: String,
    #[serde(rename = "connectorcommon50:ClientSystemId")]
    pub client_system_id: String,
    #[serde(rename = "connectorcommon50:WorkplaceId")]
    pub workplace_id: String,
    #[serde(
        rename = "connectorcommon50:UserId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub user_id: Option<String>,
}
