// Code generated by wsdl2openapi; DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct Status {
    #[serde(rename = "Result")]
    pub result: Result,
    #[serde(rename = "Error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<crate::api::gematik::tel::error20::Error>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Result {
    Ok,
    Warning,
}

impl Result {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Ok => "OK",
            Self::Warning => "Warning",
        }
    }
}

impl ::std::fmt::Display for Result {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl ::std::str::FromStr for Result {
    type Err = crate::api::soap::UnknownEnumValue;
    fn from_str(value: &str) -> ::std::result::Result<Self, Self::Err> {
        match value {
            "OK" => Ok(Self::Ok),
            "Warning" => Ok(Self::Warning),
            _ => Err(crate::api::soap::UnknownEnumValue {
                type_name: "Result",
                value: value.to_owned(),
            }),
        }
    }
}

impl<'de> ::serde::Deserialize<'de> for Result {
    fn deserialize<D: ::serde::Deserializer<'de>>(
        deserializer: D,
    ) -> ::std::result::Result<Self, D::Error> {
        let value = <String as ::serde::Deserialize>::deserialize(deserializer)?;
        value.parse().map_err(::serde::de::Error::custom)
    }
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct WorkplaceIds {
    #[serde(rename = "WorkplaceId", default, skip_serializing_if = "Vec::is_empty")]
    pub workplace_id: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct Connector {
    #[serde(rename = "VPNTIStatus")]
    pub vpn_ti_status: ConnectorVpnTiStatus,
    #[serde(rename = "VPNSISStatus")]
    pub vpn_sis_status: ConnectorVpnSisStatus,
    #[serde(rename = "OperatingState")]
    pub operating_state: OperatingState,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ErrorState {
    #[serde(rename = "ErrorCondition")]
    pub error_condition: String,
    #[serde(rename = "Severity")]
    pub severity: String,
    #[serde(rename = "Type")]
    pub r#type: String,
    #[serde(rename = "Value")]
    pub value: bool,
    #[serde(rename = "ValidFrom")]
    pub valid_from: String,
}

pub type Document = DocumentType;

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct OperatingState {
    #[serde(rename = "ErrorState", default, skip_serializing_if = "Vec::is_empty")]
    pub error_state: Vec<ErrorState>,
}

pub type XslStylesheet = AttachmentType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct AttachmentType {
    #[serde(rename = "connectorcommon50:Data")]
    pub data: crate::api::soap::Base64Binary,
    #[serde(rename = "connectorcommon50:RefURI")]
    pub ref_uri: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct DocumentType {
    #[serde(rename = "@ID", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "@RefURI", default, skip_serializing_if = "Option::is_none")]
    pub ref_uri: Option<String>,
    #[serde(rename = "@RefType", default, skip_serializing_if = "Option::is_none")]
    pub ref_type: Option<String>,
    #[serde(
        rename = "@SchemaRefs",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub schema_refs: Option<String>,
    #[serde(
        rename(serialize = "connectorcommon50:Base64XML", deserialize = "Base64XML"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub base64_xml: Option<crate::api::soap::Base64Binary>,
    #[serde(
        rename(serialize = "dss10core:Base64Data", deserialize = "Base64Data"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub base64_data: Option<crate::api::oasis::dss10core::Base64Data>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ConnectorVpnTiStatus {
    #[serde(rename = "ConnectionStatus")]
    pub connection_status: String,
    #[serde(rename = "Timestamp")]
    pub timestamp: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ConnectorVpnSisStatus {
    #[serde(rename = "ConnectionStatus")]
    pub connection_status: String,
    #[serde(rename = "Timestamp")]
    pub timestamp: String,
}
