// Code generated by wsdl2openapi; DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct EncryptDocument {
    #[serde(rename = "connectorcontext20:Context")]
    pub context: crate::api::gematik::conn::connectorcontext20::Context,
    #[serde(rename = "encryptionservice611:RecipientKeys")]
    pub recipient_keys: EncryptDocumentRecipientKeys,
    #[serde(rename = "connectorcommon50:Document")]
    pub document: crate::api::gematik::conn::connectorcommon50::Document,
    #[serde(
        rename = "encryptionservice611:OptionalInputs",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub optional_inputs: Option<EncryptDocumentOptionalInputs>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct EncryptDocumentResponse {
    #[serde(rename = "Status")]
    pub status: crate::api::gematik::conn::connectorcommon50::Status,
    #[serde(
        rename = "OptionalOutputs",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub optional_outputs: Option<crate::api::soap::AnyXml>,
    #[serde(rename = "Document", default, skip_serializing_if = "Option::is_none")]
    pub document: Option<crate::api::gematik::conn::connectorcommon50::Document>,
}

pub type CertificateOnCard = KeyOnCardType;

pub type PrivateKeyOnCard = KeyOnCardType;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EncryptionType {
    HttpWwwW3OrgTrXmlencCore,
    UrnIetfRfc5652,
    UrnIetfRfc5751,
}

impl EncryptionType {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::HttpWwwW3OrgTrXmlencCore => "http://www.w3.org/TR/xmlenc-core/",
            Self::UrnIetfRfc5652 => "urn:ietf:rfc:5652",
            Self::UrnIetfRfc5751 => "urn:ietf:rfc:5751",
        }
    }
}

impl ::std::fmt::Display for EncryptionType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl ::std::str::FromStr for EncryptionType {
    type Err = crate::api::soap::UnknownEnumValue;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "http://www.w3.org/TR/xmlenc-core/" => Ok(Self::HttpWwwW3OrgTrXmlencCore),
            "urn:ietf:rfc:5652" => Ok(Self::UrnIetfRfc5652),
            "urn:ietf:rfc:5751" => Ok(Self::UrnIetfRfc5751),
            _ => Err(crate::api::soap::UnknownEnumValue {
                type_name: "EncryptionType",
                value: value.to_owned(),
            }),
        }
    }
}

impl ::serde::Serialize for EncryptionType {
    fn serialize<S: ::serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct Element {
    #[serde(rename = "@Type")]
    pub r#type: String,
    #[serde(rename = "$text", default)]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct DecryptDocument {
    #[serde(rename = "connectorcontext20:Context")]
    pub context: crate::api::gematik::conn::connectorcontext20::Context,
    #[serde(rename = "encryptionservice611:PrivateKeyOnCard")]
    pub private_key_on_card: PrivateKeyOnCard,
    #[serde(rename = "connectorcommon50:Document")]
    pub document: crate::api::gematik::conn::connectorcommon50::Document,
    #[serde(
        rename = "encryptionservice611:OptionalInputs",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub optional_inputs: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct DecryptDocumentResponse {
    #[serde(rename = "Status")]
    pub status: crate::api::gematik::conn::connectorcommon50::Status,
    #[serde(rename = "Document", default, skip_serializing_if = "Option::is_none")]
    pub document: Option<crate::api::gematik::conn::connectorcommon50::Document>,
    #[serde(
        rename = "OptionalOutputs",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub optional_outputs: Option<crate::api::soap::AnyXml>,
}

pub type UnprotectedProperties = crate::api::oasis::dss10core::PropertiesType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct KeyOnCardType {
    #[serde(rename = "connectorcommon50:CardHandle")]
    pub card_handle: String,
    #[serde(
        rename = "encryptionservice611:KeyReference",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub key_reference: Option<String>,
    #[serde(
        rename = "encryptionservice611:Crypt",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub crypt: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct EncryptDocumentRecipientKeys {
    #[serde(
        rename = "encryptionservice611:CertificateOnCard",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub certificate_on_card: Option<CertificateOnCard>,
    #[serde(
        rename = "encryptionservice611:Certificate",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub certificate: Vec<crate::api::soap::Base64Binary>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct EncryptDocumentOptionalInputs {
    #[serde(
        rename = "encryptionservice611:EncryptionType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub encryption_type: Option<EncryptionType>,
    #[serde(
        rename = "encryptionservice611:Element",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub element: Vec<Element>,
    #[serde(
        rename = "encryptionservice611:UnprotectedProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unprotected_properties: Option<UnprotectedProperties>,
}

/// `SOAP-ENV:Body` content of a `EncryptDocument` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub enum EncryptDocumentInput {
    #[serde(rename = "encryptionservice611:EncryptDocument")]
    EncryptDocument(EncryptDocument),
}

impl crate::api::soap::BodyContent for EncryptDocumentInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:connectorcommon50",
            "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
        ),
        (
            "@xmlns:connectorcontext20",
            "http://ws.gematik.de/conn/ConnectorContext/v2.0",
        ),
        ("@xmlns:dss10core", "urn:oasis:names:tc:dss:1.0:core:schema"),
        (
            "@xmlns:encryptionservice611",
            "http://ws.gematik.de/conn/EncryptionService/v6.1",
        ),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::api::soap::SoapRequest for EncryptDocumentInput {
    const OPERATION: crate::api::soap::SoapOperation = crate::api::soap::SoapOperation {
        name: "EncryptDocument",
        soap_action: "http://ws.gematik.de/conn/EncryptionService/v6.1#EncryptDocument",
        binding_type: "soap11",
        service: "EncryptionService",
        version: "6.1",
        timeout: crate::api::soap::Timeout::Long,
    };
    type Response = EncryptDocumentOutput;
}

impl From<EncryptDocument> for EncryptDocumentInput {
    fn from(request: EncryptDocument) -> Self {
        Self::EncryptDocument(request)
    }
}

impl From<EncryptDocument> for crate::api::soap::Envelope<EncryptDocumentInput> {
    fn from(request: EncryptDocument) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `EncryptDocument` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum EncryptDocumentOutput {
    #[serde(rename = "EncryptDocumentResponse")]
    EncryptDocumentResponse(EncryptDocumentResponse),
    #[serde(rename = "Fault")]
    Fault(crate::api::soap::Fault<EncryptDocumentFaultDetail>),
}

impl crate::api::soap::SoapResponse for EncryptDocumentOutput {
    type Success = EncryptDocumentResponse;
    type Detail = EncryptDocumentFaultDetail;
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
    #[allow(clippy::result_large_err)]
    fn into_result(
        self,
    ) -> Result<EncryptDocumentResponse, crate::api::soap::Fault<EncryptDocumentFaultDetail>> {
        match self {
            Self::EncryptDocumentResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

/// Typed `detail` content of a `EncryptDocument` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct EncryptDocumentFaultDetail {
    #[serde(rename = "Error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<crate::api::gematik::tel::error20::Error>,
}

pub type EncryptDocumentEnvelope = crate::api::soap::Envelope<EncryptDocumentInput>;

pub type EncryptDocumentResponseEnvelope = crate::api::soap::Envelope<EncryptDocumentOutput>;

/// `SOAP-ENV:Body` content of a `DecryptDocument` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub enum DecryptDocumentInput {
    #[serde(rename = "encryptionservice611:DecryptDocument")]
    DecryptDocument(DecryptDocument),
}

impl crate::api::soap::BodyContent for DecryptDocumentInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:connectorcommon50",
            "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
        ),
        (
            "@xmlns:connectorcontext20",
            "http://ws.gematik.de/conn/ConnectorContext/v2.0",
        ),
        ("@xmlns:dss10core", "urn:oasis:names:tc:dss:1.0:core:schema"),
        (
            "@xmlns:encryptionservice611",
            "http://ws.gematik.de/conn/EncryptionService/v6.1",
        ),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::api::soap::SoapRequest for DecryptDocumentInput {
    const OPERATION: crate::api::soap::SoapOperation = crate::api::soap::SoapOperation {
        name: "DecryptDocument",
        soap_action: "http://ws.gematik.de/conn/crypt/EncryptionService/v6.1#DecryptDocument",
        binding_type: "soap11",
        service: "EncryptionService",
        version: "6.1",
        timeout: crate::api::soap::Timeout::Long,
    };
    type Response = DecryptDocumentOutput;
}

impl From<DecryptDocument> for DecryptDocumentInput {
    fn from(request: DecryptDocument) -> Self {
        Self::DecryptDocument(request)
    }
}

impl From<DecryptDocument> for crate::api::soap::Envelope<DecryptDocumentInput> {
    fn from(request: DecryptDocument) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `DecryptDocument` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum DecryptDocumentOutput {
    #[serde(rename = "DecryptDocumentResponse")]
    DecryptDocumentResponse(DecryptDocumentResponse),
    #[serde(rename = "Fault")]
    Fault(crate::api::soap::Fault<DecryptDocumentFaultDetail>),
}

impl crate::api::soap::SoapResponse for DecryptDocumentOutput {
    type Success = DecryptDocumentResponse;
    type Detail = DecryptDocumentFaultDetail;
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
    #[allow(clippy::result_large_err)]
    fn into_result(
        self,
    ) -> Result<DecryptDocumentResponse, crate::api::soap::Fault<DecryptDocumentFaultDetail>> {
        match self {
            Self::DecryptDocumentResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

/// Typed `detail` content of a `DecryptDocument` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct DecryptDocumentFaultDetail {
    #[serde(rename = "Error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<crate::api::gematik::tel::error20::Error>,
}

pub type DecryptDocumentEnvelope = crate::api::soap::Envelope<DecryptDocumentInput>;

pub type DecryptDocumentResponseEnvelope = crate::api::soap::Envelope<DecryptDocumentOutput>;
