// Code generated by wsdl2openapi; DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct GetResourceInformation {
    #[serde(rename = "connectorcontext20:Context")]
    pub context: crate::api::gematik::conn::connectorcontext20::Context,
    #[serde(
        rename = "cardservicecommon20:CtId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ct_id: Option<String>,
    #[serde(
        rename = "cardservicecommon20:SlotId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub slot_id: Option<i64>,
    #[serde(
        rename = "cardservicecommon20:Iccsn",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub iccsn: Option<String>,
    #[serde(
        rename = "connectorcommon50:CardHandle",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub card_handle: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct GetResourceInformationResponse {
    #[serde(rename = "Status")]
    pub status: crate::api::gematik::conn::connectorcommon50::Status,
    #[serde(rename = "Card", default, skip_serializing_if = "Option::is_none")]
    pub card: Option<crate::api::gematik::conn::cardservice81::Card>,
    #[serde(
        rename = "CardTerminal",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub card_terminal: Option<crate::api::gematik::conn::cardterminalinfo80::CardTerminal>,
    #[serde(rename = "Connector", default, skip_serializing_if = "Option::is_none")]
    pub connector: Option<crate::api::gematik::conn::connectorcommon50::Connector>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct GetCards {
    #[serde(
        rename = "@mandant-wide",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub mandant_wide: Option<bool>,
    #[serde(rename = "connectorcontext20:Context")]
    pub context: crate::api::gematik::conn::connectorcontext20::Context,
    #[serde(
        rename = "cardservicecommon20:CtId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ct_id: Option<String>,
    #[serde(
        rename = "cardservicecommon20:SlotId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub slot_id: Option<i64>,
    #[serde(
        rename = "cardservicecommon20:CardType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub card_type: Option<crate::api::gematik::conn::cardservicecommon20::CardType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct GetCardsResponse {
    #[serde(rename = "Status")]
    pub status: crate::api::gematik::conn::connectorcommon50::Status,
    #[serde(rename = "Cards")]
    pub cards: crate::api::gematik::conn::cardservice81::Cards,
}

/// `SOAP-ENV:Body` content of a `GetResourceInformation` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub enum GetResourceInformationInput {
    #[serde(rename = "eventservice72:GetResourceInformation")]
    GetResourceInformation(GetResourceInformation),
}

impl crate::api::soap::BodyContent for GetResourceInformationInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:cardservice81",
            "http://ws.gematik.de/conn/CardService/v8.1",
        ),
        (
            "@xmlns:cardservicecommon20",
            "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
        ),
        (
            "@xmlns:cardterminalinfo80",
            "http://ws.gematik.de/conn/CardTerminalInfo/v8.0",
        ),
        (
            "@xmlns:connectorcommon50",
            "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
        ),
        (
            "@xmlns:connectorcontext20",
            "http://ws.gematik.de/conn/ConnectorContext/v2.0",
        ),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
        (
            "@xmlns:eventservice72",
            "http://ws.gematik.de/conn/EventService/v7.2",
        ),
        (
            "@xmlns:productinformation11",
            "http://ws.gematik.de/int/version/ProductInformation/v1.1",
        ),
    ];
}

impl crate::api::soap::SoapRequest for GetResourceInformationInput {
    const OPERATION: crate::api::soap::SoapOperation = crate::api::soap::SoapOperation {
        name: "GetResourceInformation",
        soap_action: "http://ws.gematik.de/conn/EventService/v7.2#GetResourceInformation",
        binding_type: "soap11",
        service: "EventService",
        version: "7.2",
        timeout: crate::api::soap::Timeout::Short,
    };
    type Response = GetResourceInformationOutput;
}

impl From<GetResourceInformation> for GetResourceInformationInput {
    fn from(request: GetResourceInformation) -> Self {
        Self::GetResourceInformation(request)
    }
}

impl From<GetResourceInformation> for crate::api::soap::Envelope<GetResourceInformationInput> {
    fn from(request: GetResourceInformation) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `GetResourceInformation` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum GetResourceInformationOutput {
    #[serde(rename = "GetResourceInformationResponse")]
    GetResourceInformationResponse(GetResourceInformationResponse),
    #[serde(rename = "Fault")]
    Fault(crate::api::soap::Fault<GetResourceInformationFaultDetail>),
}

impl crate::api::soap::SoapResponse for GetResourceInformationOutput {
    type Success = GetResourceInformationResponse;
    type Detail = GetResourceInformationFaultDetail;
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
    #[allow(clippy::result_large_err)]
    fn into_result(
        self,
    ) -> Result<
        GetResourceInformationResponse,
        crate::api::soap::Fault<GetResourceInformationFaultDetail>,
    > {
        match self {
            Self::GetResourceInformationResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

/// Typed `detail` content of a `GetResourceInformation` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct GetResourceInformationFaultDetail {
    #[serde(rename = "Error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<crate::api::gematik::tel::error20::Error>,
}

pub type GetResourceInformationEnvelope = crate::api::soap::Envelope<GetResourceInformationInput>;

pub type GetResourceInformationResponseEnvelope =
    crate::api::soap::Envelope<GetResourceInformationOutput>;

/// `SOAP-ENV:Body` content of a `GetCards` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub enum GetCardsInput {
    #[serde(rename = "eventservice72:GetCards")]
    GetCards(GetCards),
}

impl crate::api::soap::BodyContent for GetCardsInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:cardservice81",
            "http://ws.gematik.de/conn/CardService/v8.1",
        ),
        (
            "@xmlns:cardservicecommon20",
            "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
        ),
        (
            "@xmlns:connectorcommon50",
            "http://ws.gematik.de/conn/ConnectorCommon/v5.0",
        ),
        (
            "@xmlns:connectorcontext20",
            "http://ws.gematik.de/conn/ConnectorContext/v2.0",
        ),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
        (
            "@xmlns:eventservice72",
            "http://ws.gematik.de/conn/EventService/v7.2",
        ),
    ];
}

impl crate::api::soap::SoapRequest for GetCardsInput {
    const OPERATION: crate::api::soap::SoapOperation = crate::api::soap::SoapOperation {
        name: "GetCards",
        soap_action: "http://ws.gematik.de/conn/EventService/v7.2#GetCards",
        binding_type: "soap11",
        service: "EventService",
        version: "7.2",
        timeout: crate::api::soap::Timeout::Short,
    };
    type Response = GetCardsOutput;
}

impl From<GetCards> for GetCardsInput {
    fn from(request: GetCards) -> Self {
        Self::GetCards(request)
    }
}

impl From<GetCards> for crate::api::soap::Envelope<GetCardsInput> {
    fn from(request: GetCards) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `GetCards` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum GetCardsOutput {
    #[serde(rename = "GetCardsResponse")]
    GetCardsResponse(GetCardsResponse),
    #[serde(rename = "Fault")]
    Fault(crate::api::soap::Fault<GetCardsFaultDetail>),
}

impl crate::api::soap::SoapResponse for GetCardsOutput {
    type Success = GetCardsResponse;
    type Detail = GetCardsFaultDetail;
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
    #[allow(clippy::result_large_err)]
    fn into_result(self) -> Result<GetCardsResponse, crate::api::soap::Fault<GetCardsFaultDetail>> {
        match self {
            Self::GetCardsResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

/// Typed `detail` content of a `GetCards` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct GetCardsFaultDetail {
    #[serde(rename = "Error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<crate::api::gematik::tel::error20::Error>,
}

pub type GetCardsEnvelope = crate::api::soap::Envelope<GetCardsInput>;

pub type GetCardsResponseEnvelope = crate::api::soap::Envelope<GetCardsOutput>;
