// Code generated by wsdl2openapi; DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct Error {
    #[serde(rename = "MessageID")]
    pub message_id: String,
    #[serde(rename = "Timestamp")]
    pub timestamp: String,
    #[serde(rename = "Trace", default, skip_serializing_if = "Vec::is_empty")]
    pub trace: Vec<ErrorTrace>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ErrorTrace {
    #[serde(rename = "EventID")]
    pub event_id: String,
    #[serde(rename = "Instance")]
    pub instance: String,
    #[serde(rename = "LogReference")]
    pub log_reference: String,
    #[serde(rename = "CompType")]
    pub comp_type: String,
    #[serde(rename = "Code")]
    pub code: i64,
    #[serde(rename = "Severity")]
    pub severity: String,
    #[serde(rename = "ErrorType")]
    pub error_type: String,
    #[serde(rename = "ErrorText")]
    pub error_text: String,
    #[serde(rename = "Detail", default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<ErrorTraceDetail>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ErrorTraceDetail {
    #[serde(rename = "@Encoding", default, skip_serializing_if = "Option::is_none")]
    pub encoding: Option<String>,
    #[serde(rename = "$text")]
    pub char_data: String,
}
