// Code generated by wsdl2openapi; DO NOT EDIT.

package saml20assertion

import (
	"encoding/xml"
	xmldsig "github.com/gematik/zero-lab/go/kon/api/w3200009/xmldsig"
	xmlenc "github.com/gematik/zero-lab/go/kon/api/w3200104/xmlenc"
)

type BaseID struct {
	XMLName         xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion BaseID"`
	NameQualifier   string   `xml:"NameQualifier,attr,omitempty"`
	SPNameQualifier string   `xml:"SPNameQualifier,attr,omitempty"`
}

type NameID struct {
	XMLName         xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion NameID"`
	NameQualifier   string   `xml:"NameQualifier,attr,omitempty"`
	SPNameQualifier string   `xml:"SPNameQualifier,attr,omitempty"`
	Format          string   `xml:"Format,attr,omitempty"`
	SPProvidedID    string   `xml:"SPProvidedID,attr,omitempty"`
	CharData        string   `xml:"chardata"`
}

type EncryptedID struct {
	XMLName       xml.Name              `xml:"urn:oasis:names:tc:SAML:2.0:assertion EncryptedID"`
	EncryptedData xmlenc.EncryptedData  `xml:"http://www.w3.org/2001/04/xmlenc# EncryptedData"`
	EncryptedKey  []xmlenc.EncryptedKey `xml:"http://www.w3.org/2001/04/xmlenc# EncryptedKey"`
}

type Issuer struct {
	XMLName         xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion Issuer"`
	NameQualifier   string   `xml:"NameQualifier,attr,omitempty"`
	SPNameQualifier string   `xml:"SPNameQualifier,attr,omitempty"`
	Format          string   `xml:"Format,attr,omitempty"`
	SPProvidedID    string   `xml:"SPProvidedID,attr,omitempty"`
	CharData        string   `xml:"chardata"`
}

type Assertion struct {
	XMLName                xml.Name                 `xml:"urn:oasis:names:tc:SAML:2.0:assertion Assertion"`
	Version                string                   `xml:"Version,attr"`
	Id                     string                   `xml:"ID,attr"`
	IssueInstant           string                   `xml:"IssueInstant,attr"`
	Issuer                 Issuer                   `xml:"Issuer"`
	Signature              *xmldsig.Signature       `xml:"http://www.w3.org/2000/09/xmldsig# Signature,omitempty"`
	Subject                *Subject                 `xml:"Subject,omitempty"`
	Conditions             *Conditions              `xml:"Conditions,omitempty"`
	Advice                 *Advice                  `xml:"Advice,omitempty"`
	Statement              []Statement              `xml:"Statement"`
	AuthnStatement         []AuthnStatement         `xml:"AuthnStatement"`
	AuthzDecisionStatement []AuthzDecisionStatement `xml:"AuthzDecisionStatement"`
	AttributeStatement     []AttributeStatement     `xml:"AttributeStatement"`
}

type Subject struct {
	XMLName             xml.Name              `xml:"urn:oasis:names:tc:SAML:2.0:assertion Subject"`
	BaseID              *BaseID               `xml:"BaseID,omitempty"`
	NameID              *NameID               `xml:"NameID,omitempty"`
	EncryptedID         *EncryptedID          `xml:"EncryptedID,omitempty"`
	SubjectConfirmation []SubjectConfirmation `xml:"SubjectConfirmation"`
}

type SubjectConfirmation struct {
	XMLName                 xml.Name                 `xml:"urn:oasis:names:tc:SAML:2.0:assertion SubjectConfirmation"`
	Method                  string                   `xml:"Method,attr"`
	BaseID                  *BaseID                  `xml:"BaseID,omitempty"`
	NameID                  *NameID                  `xml:"NameID,omitempty"`
	EncryptedID             *EncryptedID             `xml:"EncryptedID,omitempty"`
	SubjectConfirmationData *SubjectConfirmationData `xml:"SubjectConfirmationData,omitempty"`
}

type SubjectConfirmationData struct {
	XMLName           xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion SubjectConfirmationData"`
	NotBefore         string   `xml:"NotBefore,attr,omitempty"`
	NotOnOrAfter      string   `xml:"NotOnOrAfter,attr,omitempty"`
	Recipient         string   `xml:"Recipient,attr,omitempty"`
	InResponseTo      string   `xml:"InResponseTo,attr,omitempty"`
	Address           string   `xml:"Address,attr,omitempty"`
	UnknownAttributes string   `xml:"anyAttribute,attr,omitempty"`
	UnknownContent    string
}

type Conditions struct {
	XMLName             xml.Name              `xml:"urn:oasis:names:tc:SAML:2.0:assertion Conditions"`
	NotBefore           string                `xml:"NotBefore,attr,omitempty"`
	NotOnOrAfter        string                `xml:"NotOnOrAfter,attr,omitempty"`
	Condition           []Condition           `xml:"Condition"`
	AudienceRestriction []AudienceRestriction `xml:"AudienceRestriction"`
	OneTimeUse          []OneTimeUse          `xml:"OneTimeUse"`
	ProxyRestriction    []ProxyRestriction    `xml:"ProxyRestriction"`
}

type Condition struct {
	XMLName xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion Condition"`
}

type AudienceRestriction struct {
	XMLName  xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion AudienceRestriction"`
	Audience []string `xml:"Audience"`
}

type OneTimeUse struct {
	XMLName  xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion OneTimeUse"`
	CharData string   `xml:"chardata"`
}

type ProxyRestriction struct {
	XMLName  xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion ProxyRestriction"`
	Count    int      `xml:"Count,attr,omitempty"`
	Audience []string `xml:"Audience"`
}

type Advice struct {
	XMLName            xml.Name             `xml:"urn:oasis:names:tc:SAML:2.0:assertion Advice"`
	AssertionIDRef     []string             `xml:"AssertionIDRef,omitempty"`
	AssertionURIRef    []string             `xml:"AssertionURIRef,omitempty"`
	Assertion          []Assertion          `xml:"Assertion"`
	EncryptedAssertion []EncryptedAssertion `xml:"EncryptedAssertion"`
	UnknownContent     string
}

type EncryptedAssertion struct {
	XMLName       xml.Name              `xml:"urn:oasis:names:tc:SAML:2.0:assertion EncryptedAssertion"`
	EncryptedData xmlenc.EncryptedData  `xml:"http://www.w3.org/2001/04/xmlenc# EncryptedData"`
	EncryptedKey  []xmlenc.EncryptedKey `xml:"http://www.w3.org/2001/04/xmlenc# EncryptedKey"`
}

type Statement struct {
	XMLName xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion Statement"`
}

type AuthnStatement struct {
	XMLName             xml.Name         `xml:"urn:oasis:names:tc:SAML:2.0:assertion AuthnStatement"`
	AuthnInstant        string           `xml:"AuthnInstant,attr"`
	SessionIndex        string           `xml:"SessionIndex,attr,omitempty"`
	SessionNotOnOrAfter string           `xml:"SessionNotOnOrAfter,attr,omitempty"`
	SubjectLocality     *SubjectLocality `xml:"SubjectLocality,omitempty"`
	AuthnContext        AuthnContext     `xml:"AuthnContext"`
}

type SubjectLocality struct {
	XMLName xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion SubjectLocality"`
	Address string   `xml:"Address,attr,omitempty"`
	DNSName string   `xml:"DNSName,attr,omitempty"`
}

type AuthnContext struct {
	XMLName                 xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion AuthnContext"`
	AuthnContextClassRef    string   `xml:"AuthnContextClassRef"`
	AuthnContextDecl        string   `xml:"AuthnContextDecl,omitempty"`
	AuthnContextDeclRef     string   `xml:"AuthnContextDeclRef,omitempty"`
	AuthenticatingAuthority []string `xml:"AuthenticatingAuthority"`
}

type AuthzDecisionStatement struct {
	XMLName  xml.Name     `xml:"urn:oasis:names:tc:SAML:2.0:assertion AuthzDecisionStatement"`
	Resource string       `xml:"Resource,attr"`
	Decision DecisionType `xml:"Decision,attr"`
	Action   []Action     `xml:"Action"`
	Evidence *Evidence    `xml:"Evidence,omitempty"`
}

type Action struct {
	XMLName   xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion Action"`
	Namespace string   `xml:"Namespace,attr"`
	CharData  string   `xml:"chardata"`
}

type Evidence struct {
	XMLName            xml.Name             `xml:"urn:oasis:names:tc:SAML:2.0:assertion Evidence"`
	AssertionIDRef     []string             `xml:"AssertionIDRef,omitempty"`
	AssertionURIRef    []string             `xml:"AssertionURIRef,omitempty"`
	Assertion          []Assertion          `xml:"Assertion"`
	EncryptedAssertion []EncryptedAssertion `xml:"EncryptedAssertion"`
}

type AttributeStatement struct {
	XMLName            xml.Name             `xml:"urn:oasis:names:tc:SAML:2.0:assertion AttributeStatement"`
	Attribute          []Attribute          `xml:"Attribute"`
	EncryptedAttribute []EncryptedAttribute `xml:"EncryptedAttribute"`
}

type Attribute struct {
	XMLName           xml.Name `xml:"urn:oasis:names:tc:SAML:2.0:assertion Attribute"`
	Name              string   `xml:"Name,attr"`
	NameFormat        string   `xml:"NameFormat,attr,omitempty"`
	FriendlyName      string   `xml:"FriendlyName,attr,omitempty"`
	UnknownAttributes string   `xml:"anyAttribute,attr,omitempty"`
	AttributeValue    []string `xml:"AttributeValue"`
}

type EncryptedAttribute struct {
	XMLName       xml.Name              `xml:"urn:oasis:names:tc:SAML:2.0:assertion EncryptedAttribute"`
	EncryptedData xmlenc.EncryptedData  `xml:"http://www.w3.org/2001/04/xmlenc# EncryptedData"`
	EncryptedKey  []xmlenc.EncryptedKey `xml:"http://www.w3.org/2001/04/xmlenc# EncryptedKey"`
}

type BaseIDAbstractType struct {
	NameQualifier   string `xml:"NameQualifier,attr,omitempty"`
	SPNameQualifier string `xml:"SPNameQualifier,attr,omitempty"`
}

// Interface for types that extend BaseIDAbstractType
type IBaseIDAbstractType interface {
	IsAssertionBaseIDAbstractType()
}

// The type itself implements IBaseIDAbstractType
func (BaseIDAbstractType) IsAssertionBaseIDAbstractType() {}

type NameIDType struct {
	NameQualifier   string `xml:"NameQualifier,attr,omitempty"`
	SPNameQualifier string `xml:"SPNameQualifier,attr,omitempty"`
	Format          string `xml:"Format,attr,omitempty"`
	SPProvidedID    string `xml:"SPProvidedID,attr,omitempty"`
	CharData        string `xml:"chardata"`
}

// Interface for types that extend NameIDType
type INameIDType interface {
	IsAssertionNameIDType()
}

// The type itself implements INameIDType
func (NameIDType) IsAssertionNameIDType() {}

type EncryptedElementType struct {
	EncryptedData xmlenc.EncryptedData  `xml:"http://www.w3.org/2001/04/xmlenc# EncryptedData"`
	EncryptedKey  []xmlenc.EncryptedKey `xml:"http://www.w3.org/2001/04/xmlenc# EncryptedKey"`
}

// Interface for types that extend EncryptedElementType
type IEncryptedElementType interface {
	IsAssertionEncryptedElementType()
}

// The type itself implements IEncryptedElementType
func (EncryptedElementType) IsAssertionEncryptedElementType() {}

type AssertionType struct {
	Version                string                   `xml:"Version,attr"`
	Id                     string                   `xml:"ID,attr"`
	IssueInstant           string                   `xml:"IssueInstant,attr"`
	Issuer                 Issuer                   `xml:"urn:oasis:names:tc:SAML:2.0:assertion Issuer"`
	Signature              *xmldsig.Signature       `xml:"http://www.w3.org/2000/09/xmldsig# Signature,omitempty"`
	Subject                *Subject                 `xml:"urn:oasis:names:tc:SAML:2.0:assertion Subject,omitempty"`
	Conditions             *Conditions              `xml:"urn:oasis:names:tc:SAML:2.0:assertion Conditions,omitempty"`
	Advice                 *Advice                  `xml:"urn:oasis:names:tc:SAML:2.0:assertion Advice,omitempty"`
	Statement              []Statement              `xml:"urn:oasis:names:tc:SAML:2.0:assertion Statement"`
	AuthnStatement         []AuthnStatement         `xml:"urn:oasis:names:tc:SAML:2.0:assertion AuthnStatement"`
	AuthzDecisionStatement []AuthzDecisionStatement `xml:"urn:oasis:names:tc:SAML:2.0:assertion AuthzDecisionStatement"`
	AttributeStatement     []AttributeStatement     `xml:"urn:oasis:names:tc:SAML:2.0:assertion AttributeStatement"`
}

// Interface for types that extend AssertionType
type IAssertionType interface {
	IsAssertionAssertionType()
}

// The type itself implements IAssertionType
func (AssertionType) IsAssertionAssertionType() {}

type SubjectType struct {
	BaseID              *BaseID               `xml:"urn:oasis:names:tc:SAML:2.0:assertion BaseID,omitempty"`
	NameID              *NameID               `xml:"urn:oasis:names:tc:SAML:2.0:assertion NameID,omitempty"`
	EncryptedID         *EncryptedID          `xml:"urn:oasis:names:tc:SAML:2.0:assertion EncryptedID,omitempty"`
	SubjectConfirmation []SubjectConfirmation `xml:"urn:oasis:names:tc:SAML:2.0:assertion SubjectConfirmation"`
}

// Interface for types that extend SubjectType
type ISubjectType interface {
	IsAssertionSubjectType()
}

// The type itself implements ISubjectType
func (SubjectType) IsAssertionSubjectType() {}

type SubjectConfirmationType struct {
	Method                  string                   `xml:"Method,attr"`
	BaseID                  *BaseID                  `xml:"urn:oasis:names:tc:SAML:2.0:assertion BaseID,omitempty"`
	NameID                  *NameID                  `xml:"urn:oasis:names:tc:SAML:2.0:assertion NameID,omitempty"`
	EncryptedID             *EncryptedID             `xml:"urn:oasis:names:tc:SAML:2.0:assertion EncryptedID,omitempty"`
	SubjectConfirmationData *SubjectConfirmationData `xml:"urn:oasis:names:tc:SAML:2.0:assertion SubjectConfirmationData,omitempty"`
}

// Interface for types that extend SubjectConfirmationType
type ISubjectConfirmationType interface {
	IsAssertionSubjectConfirmationType()
}

// The type itself implements ISubjectConfirmationType
func (SubjectConfirmationType) IsAssertionSubjectConfirmationType() {}

type SubjectConfirmationDataType struct {
	NotBefore         string `xml:"NotBefore,attr,omitempty"`
	NotOnOrAfter      string `xml:"NotOnOrAfter,attr,omitempty"`
	Recipient         string `xml:"Recipient,attr,omitempty"`
	InResponseTo      string `xml:"InResponseTo,attr,omitempty"`
	Address           string `xml:"Address,attr,omitempty"`
	UnknownAttributes string `xml:"anyAttribute,attr,omitempty"`
	UnknownContent    string
}

// Interface for types that extend SubjectConfirmationDataType
type ISubjectConfirmationDataType interface {
	IsAssertionSubjectConfirmationDataType()
}

// The type itself implements ISubjectConfirmationDataType
func (SubjectConfirmationDataType) IsAssertionSubjectConfirmationDataType() {}

type KeyInfoConfirmationDataType struct {
	NotBefore         string            `xml:"NotBefore,attr,omitempty"`
	NotOnOrAfter      string            `xml:"NotOnOrAfter,attr,omitempty"`
	Recipient         string            `xml:"Recipient,attr,omitempty"`
	InResponseTo      string            `xml:"InResponseTo,attr,omitempty"`
	Address           string            `xml:"Address,attr,omitempty"`
	UnknownAttributes string            `xml:"anyAttribute,attr,omitempty"`
	KeyInfo           []xmldsig.KeyInfo `xml:"http://www.w3.org/2000/09/xmldsig# KeyInfo"`
}

type ConditionsType struct {
	NotBefore           string                `xml:"NotBefore,attr,omitempty"`
	NotOnOrAfter        string                `xml:"NotOnOrAfter,attr,omitempty"`
	Condition           []Condition           `xml:"urn:oasis:names:tc:SAML:2.0:assertion Condition"`
	AudienceRestriction []AudienceRestriction `xml:"urn:oasis:names:tc:SAML:2.0:assertion AudienceRestriction"`
	OneTimeUse          []OneTimeUse          `xml:"urn:oasis:names:tc:SAML:2.0:assertion OneTimeUse"`
	ProxyRestriction    []ProxyRestriction    `xml:"urn:oasis:names:tc:SAML:2.0:assertion ProxyRestriction"`
}

// Interface for types that extend ConditionsType
type IConditionsType interface {
	IsAssertionConditionsType()
}

// The type itself implements IConditionsType
func (ConditionsType) IsAssertionConditionsType() {}

type ConditionAbstractType struct{}

// Interface for types that extend ConditionAbstractType
type IConditionAbstractType interface {
	IsAssertionConditionAbstractType()
}

// The type itself implements IConditionAbstractType
func (ConditionAbstractType) IsAssertionConditionAbstractType() {}

type AudienceRestrictionType struct {
	Audience []string `xml:"urn:oasis:names:tc:SAML:2.0:assertion Audience"`
}

// extends #/components/schemas/oasis.names.tc.SAML20.assertion/ConditionAbstractType
func (AudienceRestrictionType) IsAssertionConditionAbstractType() {}

// Interface for types that extend AudienceRestrictionType
type IAudienceRestrictionType interface {
	IsAssertionAudienceRestrictionType()
}

// The type itself implements IAudienceRestrictionType
func (AudienceRestrictionType) IsAssertionAudienceRestrictionType() {}

type OneTimeUseType struct {
	CharData string `xml:"chardata"`
}

// extends #/components/schemas/oasis.names.tc.SAML20.assertion/ConditionAbstractType
func (OneTimeUseType) IsAssertionConditionAbstractType() {}

// Interface for types that extend OneTimeUseType
type IOneTimeUseType interface {
	IsAssertionOneTimeUseType()
}

// The type itself implements IOneTimeUseType
func (OneTimeUseType) IsAssertionOneTimeUseType() {}

type ProxyRestrictionType struct {
	Count    int      `xml:"Count,attr,omitempty"`
	Audience []string `xml:"urn:oasis:names:tc:SAML:2.0:assertion Audience"`
}

// extends #/components/schemas/oasis.names.tc.SAML20.assertion/ConditionAbstractType
func (ProxyRestrictionType) IsAssertionConditionAbstractType() {}

// Interface for types that extend ProxyRestrictionType
type IProxyRestrictionType interface {
	IsAssertionProxyRestrictionType()
}

// The type itself implements IProxyRestrictionType
func (ProxyRestrictionType) IsAssertionProxyRestrictionType() {}

type AdviceType struct {
	AssertionIDRef     []string             `xml:"urn:oasis:names:tc:SAML:2.0:assertion AssertionIDRef,omitempty"`
	AssertionURIRef    []string             `xml:"urn:oasis:names:tc:SAML:2.0:assertion AssertionURIRef,omitempty"`
	Assertion          []Assertion          `xml:"urn:oasis:names:tc:SAML:2.0:assertion Assertion"`
	EncryptedAssertion []EncryptedAssertion `xml:"urn:oasis:names:tc:SAML:2.0:assertion EncryptedAssertion"`
	UnknownContent     string
}

// Interface for types that extend AdviceType
type IAdviceType interface {
	IsAssertionAdviceType()
}

// The type itself implements IAdviceType
func (AdviceType) IsAssertionAdviceType() {}

type StatementAbstractType struct{}

// Interface for types that extend StatementAbstractType
type IStatementAbstractType interface {
	IsAssertionStatementAbstractType()
}

// The type itself implements IStatementAbstractType
func (StatementAbstractType) IsAssertionStatementAbstractType() {}

type AuthnStatementType struct {
	AuthnInstant        string           `xml:"AuthnInstant,attr"`
	SessionIndex        string           `xml:"SessionIndex,attr,omitempty"`
	SessionNotOnOrAfter string           `xml:"SessionNotOnOrAfter,attr,omitempty"`
	SubjectLocality     *SubjectLocality `xml:"urn:oasis:names:tc:SAML:2.0:assertion SubjectLocality,omitempty"`
	AuthnContext        AuthnContext     `xml:"urn:oasis:names:tc:SAML:2.0:assertion AuthnContext"`
}

// extends #/components/schemas/oasis.names.tc.SAML20.assertion/StatementAbstractType
func (AuthnStatementType) IsAssertionStatementAbstractType() {}

// Interface for types that extend AuthnStatementType
type IAuthnStatementType interface {
	IsAssertionAuthnStatementType()
}

// The type itself implements IAuthnStatementType
func (AuthnStatementType) IsAssertionAuthnStatementType() {}

type SubjectLocalityType struct {
	Address string `xml:"Address,attr,omitempty"`
	DNSName string `xml:"DNSName,attr,omitempty"`
}

// Interface for types that extend SubjectLocalityType
type ISubjectLocalityType interface {
	IsAssertionSubjectLocalityType()
}

// The type itself implements ISubjectLocalityType
func (SubjectLocalityType) IsAssertionSubjectLocalityType() {}

type AuthnContextType struct {
	AuthnContextClassRef    string   `xml:"urn:oasis:names:tc:SAML:2.0:assertion AuthnContextClassRef"`
	AuthnContextDecl        string   `xml:"urn:oasis:names:tc:SAML:2.0:assertion AuthnContextDecl,omitempty"`
	AuthnContextDeclRef     string   `xml:"urn:oasis:names:tc:SAML:2.0:assertion AuthnContextDeclRef,omitempty"`
	AuthenticatingAuthority []string `xml:"urn:oasis:names:tc:SAML:2.0:assertion AuthenticatingAuthority"`
}

// Interface for types that extend AuthnContextType
type IAuthnContextType interface {
	IsAssertionAuthnContextType()
}

// The type itself implements IAuthnContextType
func (AuthnContextType) IsAssertionAuthnContextType() {}

type AuthzDecisionStatementType struct {
	Resource string       `xml:"Resource,attr"`
	Decision DecisionType `xml:"Decision,attr"`
	Action   []Action     `xml:"urn:oasis:names:tc:SAML:2.0:assertion Action"`
	Evidence *Evidence    `xml:"urn:oasis:names:tc:SAML:2.0:assertion Evidence,omitempty"`
}

// extends #/components/schemas/oasis.names.tc.SAML20.assertion/StatementAbstractType
func (AuthzDecisionStatementType) IsAssertionStatementAbstractType() {}

// Interface for types that extend AuthzDecisionStatementType
type IAuthzDecisionStatementType interface {
	IsAssertionAuthzDecisionStatementType()
}

// The type itself implements IAuthzDecisionStatementType
func (AuthzDecisionStatementType) IsAssertionAuthzDecisionStatementType() {}

type DecisionType string

// Enum values for DecisionType
const (
	DecisionTypePermit        DecisionType = "Permit"
	DecisionTypeDeny          DecisionType = "Deny"
	DecisionTypeIndeterminate DecisionType = "Indeterminate"
)

func (v DecisionType) IsValid() bool {
	switch v {
	case DecisionTypePermit:
		return true
	case DecisionTypeDeny:
		return true
	case DecisionTypeIndeterminate:
		return true
	default:
		return false
	}
}

type ActionType struct {
	Namespace string `xml:"Namespace,attr"`
	CharData  string `xml:"chardata"`
}

// Interface for types that extend ActionType
type IActionType interface {
	IsAssertionActionType()
}

// The type itself implements IActionType
func (ActionType) IsAssertionActionType() {}

type EvidenceType struct {
	AssertionIDRef     []string             `xml:"urn:oasis:names:tc:SAML:2.0:assertion AssertionIDRef,omitempty"`
	AssertionURIRef    []string             `xml:"urn:oasis:names:tc:SAML:2.0:assertion AssertionURIRef,omitempty"`
	Assertion          []Assertion          `xml:"urn:oasis:names:tc:SAML:2.0:assertion Assertion"`
	EncryptedAssertion []EncryptedAssertion `xml:"urn:oasis:names:tc:SAML:2.0:assertion EncryptedAssertion"`
}

// Interface for types that extend EvidenceType
type IEvidenceType interface {
	IsAssertionEvidenceType()
}

// The type itself implements IEvidenceType
func (EvidenceType) IsAssertionEvidenceType() {}

type AttributeStatementType struct {
	Attribute          []Attribute          `xml:"urn:oasis:names:tc:SAML:2.0:assertion Attribute"`
	EncryptedAttribute []EncryptedAttribute `xml:"urn:oasis:names:tc:SAML:2.0:assertion EncryptedAttribute"`
}

// extends #/components/schemas/oasis.names.tc.SAML20.assertion/StatementAbstractType
func (AttributeStatementType) IsAssertionStatementAbstractType() {}

// Interface for types that extend AttributeStatementType
type IAttributeStatementType interface {
	IsAssertionAttributeStatementType()
}

// The type itself implements IAttributeStatementType
func (AttributeStatementType) IsAssertionAttributeStatementType() {}

type AttributeType struct {
	Name              string   `xml:"Name,attr"`
	NameFormat        string   `xml:"NameFormat,attr,omitempty"`
	FriendlyName      string   `xml:"FriendlyName,attr,omitempty"`
	UnknownAttributes string   `xml:"anyAttribute,attr,omitempty"`
	AttributeValue    []string `xml:"urn:oasis:names:tc:SAML:2.0:assertion AttributeValue"`
}

// Interface for types that extend AttributeType
type IAttributeType interface {
	IsAssertionAttributeType()
}

// The type itself implements IAttributeType
func (AttributeType) IsAssertionAttributeType() {}
