// Code generated by wsdl2openapi go generator. DO NOT EDIT.

package encryptionservice611

import (
	"encoding/xml"
	error20 "github.com/gematik/zero-lab/go/kon/api/gematik/tel/error20"
)

type soapOperation struct {
	name        string
	soapAction  string
	bindingType string
}

func (op *soapOperation) Name() string {
	return op.name
}

func (op *soapOperation) SOAPAction() string {
	return op.soapAction
}

func (op *soapOperation) BindingType() string {
	return op.bindingType
}

var OperationEncryptDocument = soapOperation{
	bindingType: "soap11",
	name:        "EncryptDocument",
	soapAction:  "http://ws.gematik.de/conn/EncryptionService/v6.1#EncryptDocument",
}

type EncryptDocumentEnvelope struct {
	XMLName         xml.Name         `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	EncryptDocument *EncryptDocument `xml:"Body>EncryptDocument"`
}

func (e *EncryptDocumentEnvelope) IsFault() bool {
	return false
}

type EncryptDocumentResponseEnvelope struct {
	XMLName                 xml.Name                 `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	EncryptDocumentResponse *EncryptDocumentResponse `xml:"Body>EncryptDocumentResponse"`
	Fault                   *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *EncryptDocumentResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationDecryptDocument = soapOperation{
	bindingType: "soap11",
	name:        "DecryptDocument",
	soapAction:  "http://ws.gematik.de/conn/crypt/EncryptionService/v6.1#DecryptDocument",
}

type DecryptDocumentEnvelope struct {
	XMLName         xml.Name         `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	DecryptDocument *DecryptDocument `xml:"Body>DecryptDocument"`
}

func (e *DecryptDocumentEnvelope) IsFault() bool {
	return false
}

type DecryptDocumentResponseEnvelope struct {
	XMLName                 xml.Name                 `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	DecryptDocumentResponse *DecryptDocumentResponse `xml:"Body>DecryptDocumentResponse"`
	Fault                   *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *DecryptDocumentResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}
