// Code generated by wsdl2openapi; DO NOT EDIT.

package etsi022312

import (
	"encoding/xml"
	xmldsig "github.com/gematik/zero-lab/go/kon/api/w3200009/xmldsig"
)

type PostalAddresses struct {
	XMLName       xml.Name        `xml:"http://uri.etsi.org/02231/v2# PostalAddresses"`
	PostalAddress []PostalAddress `xml:"PostalAddress"`
}

type PostalAddress struct {
	XMLName         xml.Name `xml:"http://uri.etsi.org/02231/v2# PostalAddress"`
	Lang            string   `xml:"http://www.w3.org/XML/1998/namespace lang,attr,omitempty"`
	StreetAddress   string   `xml:"StreetAddress"`
	Locality        string   `xml:"Locality"`
	StateOrProvince string   `xml:"StateOrProvince,omitempty"`
	PostalCode      string   `xml:"PostalCode,omitempty"`
	CountryName     string   `xml:"CountryName"`
}

type ElectronicAddress struct {
	XMLName xml.Name `xml:"http://uri.etsi.org/02231/v2# ElectronicAddress"`
	Uri     []string `xml:"URI"`
}

type Extension struct {
	XMLName        xml.Name `xml:"http://uri.etsi.org/02231/v2# Extension"`
	Critical       bool     `xml:"Critical,attr"`
	UnknownContent string
}

type TrustServiceStatusList struct {
	XMLName                  xml.Name                  `xml:"http://uri.etsi.org/02231/v2# TrustServiceStatusList"`
	TSLTag                   TSLTagType                `xml:"TSLTag,attr"`
	Id                       string                    `xml:"Id,attr,omitempty"`
	SchemeInformation        SchemeInformation         `xml:"SchemeInformation"`
	TrustServiceProviderList *TrustServiceProviderList `xml:"TrustServiceProviderList,omitempty"`
	Signature                *xmldsig.Signature        `xml:"http://www.w3.org/2000/09/xmldsig# Signature,omitempty"`
}

type TrustServiceProviderList struct {
	XMLName              xml.Name               `xml:"http://uri.etsi.org/02231/v2# TrustServiceProviderList"`
	TrustServiceProvider []TrustServiceProvider `xml:"TrustServiceProvider"`
}

type SchemeInformation struct {
	XMLName                     xml.Name                  `xml:"http://uri.etsi.org/02231/v2# SchemeInformation"`
	TSLVersionIdentifier        int                       `xml:"TSLVersionIdentifier"`
	TSLSequenceNumber           int                       `xml:"TSLSequenceNumber"`
	TSLType                     string                    `xml:"TSLType"`
	SchemeOperatorName          SchemeOperatorName        `xml:"SchemeOperatorName"`
	SchemeOperatorAddress       AddressType               `xml:"SchemeOperatorAddress"`
	SchemeName                  SchemeName                `xml:"SchemeName"`
	SchemeInformationURI        SchemeInformationURI      `xml:"SchemeInformationURI"`
	StatusDeterminationApproach string                    `xml:"StatusDeterminationApproach"`
	SchemeTypeCommunityRules    *SchemeTypeCommunityRules `xml:"SchemeTypeCommunityRules,omitempty"`
	SchemeTerritory             string                    `xml:"SchemeTerritory,omitempty"`
	PolicyOrLegalNotice         *PolicyOrLegalNotice      `xml:"PolicyOrLegalNotice,omitempty"`
	HistoricalInformationPeriod int                       `xml:"HistoricalInformationPeriod"`
	PointersToOtherTSL          *PointersToOtherTSL       `xml:"PointersToOtherTSL,omitempty"`
	ListIssueDateTime           string                    `xml:"ListIssueDateTime"`
	NextUpdate                  NextUpdate                `xml:"NextUpdate"`
	DistributionPoints          *DistributionPoints       `xml:"DistributionPoints,omitempty"`
	SchemeExtensions            *ExtensionsListType       `xml:"SchemeExtensions,omitempty"`
}

type SchemeOperatorName struct {
	XMLName xml.Name                  `xml:"http://uri.etsi.org/02231/v2# SchemeOperatorName"`
	Name    []MultiLangNormStringType `xml:"Name"`
}

type SchemeName struct {
	XMLName xml.Name                  `xml:"http://uri.etsi.org/02231/v2# SchemeName"`
	Name    []MultiLangNormStringType `xml:"Name"`
}

type SchemeInformationURI struct {
	XMLName xml.Name                   `xml:"http://uri.etsi.org/02231/v2# SchemeInformationURI"`
	Uri     []NonEmptyMultiLangURIType `xml:"URI"`
}

type SchemeTypeCommunityRules struct {
	XMLName xml.Name `xml:"http://uri.etsi.org/02231/v2# SchemeTypeCommunityRules"`
	Uri     []string `xml:"URI"`
}

type PolicyOrLegalNotice struct {
	XMLName        xml.Name                   `xml:"http://uri.etsi.org/02231/v2# PolicyOrLegalNotice"`
	TSLPolicy      []NonEmptyMultiLangURIType `xml:"TSLPolicy"`
	TSLLegalNotice []MultiLangStringType      `xml:"TSLLegalNotice"`
}

type NextUpdate struct {
	XMLName  xml.Name `xml:"http://uri.etsi.org/02231/v2# NextUpdate"`
	DateTime string   `xml:"dateTime,omitempty"`
}

type PointersToOtherTSL struct {
	XMLName         xml.Name          `xml:"http://uri.etsi.org/02231/v2# PointersToOtherTSL"`
	OtherTSLPointer []OtherTSLPointer `xml:"OtherTSLPointer"`
}

type OtherTSLPointer struct {
	XMLName                  xml.Name                  `xml:"http://uri.etsi.org/02231/v2# OtherTSLPointer"`
	ServiceDigitalIdentities *ServiceDigitalIdentities `xml:"ServiceDigitalIdentities,omitempty"`
	TSLLocation              string                    `xml:"TSLLocation"`
	AdditionalInformation    *AdditionalInformation    `xml:"AdditionalInformation,omitempty"`
}

type ServiceDigitalIdentities struct {
	XMLName                xml.Name                 `xml:"http://uri.etsi.org/02231/v2# ServiceDigitalIdentities"`
	ServiceDigitalIdentity []ServiceDigitalIdentity `xml:"ServiceDigitalIdentity"`
}

type AdditionalInformation struct {
	XMLName            xml.Name              `xml:"http://uri.etsi.org/02231/v2# AdditionalInformation"`
	TextualInformation []MultiLangStringType `xml:"TextualInformation"`
	OtherInformation   []AnyType             `xml:"OtherInformation"`
}

type DistributionPoints struct {
	XMLName xml.Name `xml:"http://uri.etsi.org/02231/v2# DistributionPoints"`
	Uri     []string `xml:"URI"`
}

type TrustServiceProvider struct {
	XMLName        xml.Name       `xml:"http://uri.etsi.org/02231/v2# TrustServiceProvider"`
	TSPInformation TSPInformation `xml:"TSPInformation"`
	TSPServices    TSPServices    `xml:"TSPServices"`
}

type TSPInformation struct {
	XMLName                  xml.Name                     `xml:"http://uri.etsi.org/02231/v2# TSPInformation"`
	TSPName                  InternationalNamesType       `xml:"TSPName"`
	TSPTradeName             *InternationalNamesType      `xml:"TSPTradeName,omitempty"`
	TSPAddress               AddressType                  `xml:"TSPAddress"`
	TSPInformationURI        NonEmptyMultiLangURIListType `xml:"TSPInformationURI"`
	TSPInformationExtensions *ExtensionsListType          `xml:"TSPInformationExtensions,omitempty"`
}

type TSPServices struct {
	XMLName    xml.Name     `xml:"http://uri.etsi.org/02231/v2# TSPServices"`
	TSPService []TSPService `xml:"TSPService"`
}

type TSPService struct {
	XMLName            xml.Name           `xml:"http://uri.etsi.org/02231/v2# TSPService"`
	ServiceInformation ServiceInformation `xml:"ServiceInformation"`
	ServiceHistory     *ServiceHistory    `xml:"ServiceHistory,omitempty"`
}

type ServiceInformation struct {
	XMLName                      xml.Name                      `xml:"http://uri.etsi.org/02231/v2# ServiceInformation"`
	ServiceTypeIdentifier        string                        `xml:"ServiceTypeIdentifier"`
	ServiceName                  InternationalNamesType        `xml:"ServiceName"`
	ServiceDigitalIdentity       ServiceDigitalIdentity        `xml:"ServiceDigitalIdentity"`
	ServiceStatus                string                        `xml:"ServiceStatus"`
	StatusStartingTime           string                        `xml:"StatusStartingTime"`
	SchemeServiceDefinitionURI   *NonEmptyMultiLangURIListType `xml:"SchemeServiceDefinitionURI,omitempty"`
	ServiceSupplyPoints          *ServiceSupplyPoints          `xml:"ServiceSupplyPoints,omitempty"`
	TSPServiceDefinitionURI      *NonEmptyMultiLangURIListType `xml:"TSPServiceDefinitionURI,omitempty"`
	ServiceInformationExtensions *ExtensionsListType           `xml:"ServiceInformationExtensions,omitempty"`
}

type ServiceSupplyPoints struct {
	XMLName            xml.Name `xml:"http://uri.etsi.org/02231/v2# ServiceSupplyPoints"`
	ServiceSupplyPoint []string `xml:"ServiceSupplyPoint"`
}

type ServiceDigitalIdentity struct {
	XMLName   xml.Name              `xml:"http://uri.etsi.org/02231/v2# ServiceDigitalIdentity"`
	DigitalId []DigitalIdentityType `xml:"DigitalId"`
}

type ServiceHistory struct {
	XMLName                xml.Name                 `xml:"http://uri.etsi.org/02231/v2# ServiceHistory"`
	ServiceHistoryInstance []ServiceHistoryInstance `xml:"ServiceHistoryInstance"`
}

type ServiceHistoryInstance struct {
	XMLName                      xml.Name               `xml:"http://uri.etsi.org/02231/v2# ServiceHistoryInstance"`
	ServiceTypeIdentifier        string                 `xml:"ServiceTypeIdentifier"`
	ServiceName                  InternationalNamesType `xml:"ServiceName"`
	ServiceDigitalIdentity       ServiceDigitalIdentity `xml:"ServiceDigitalIdentity"`
	ServiceStatus                string                 `xml:"ServiceStatus"`
	StatusStartingTime           string                 `xml:"StatusStartingTime"`
	ServiceInformationExtensions *ExtensionsListType    `xml:"ServiceInformationExtensions,omitempty"`
}

type AdditionalServiceInformation struct {
	XMLName          xml.Name                 `xml:"http://uri.etsi.org/02231/v2# AdditionalServiceInformation"`
	Uri              NonEmptyMultiLangURIType `xml:"URI"`
	InformationValue string                   `xml:"InformationValue,omitempty"`
	OtherInformation *AnyType                 `xml:"OtherInformation,omitempty"`
}

type InternationalNamesType struct {
	Name []MultiLangNormStringType `xml:"http://uri.etsi.org/02231/v2# Name"`
}

// Interface for types that extend InternationalNamesType
type IInternationalNamesType interface {
	IsEtsi022312InternationalNamesType()
}

// The type itself implements IInternationalNamesType
func (InternationalNamesType) IsEtsi022312InternationalNamesType() {}

type MultiLangNormStringType struct {
	Lang     string `xml:"http://www.w3.org/XML/1998/namespace lang,attr,omitempty"`
	CharData string `xml:"chardata"`
}

type MultiLangStringType struct {
	Lang     string `xml:"http://www.w3.org/XML/1998/namespace lang,attr,omitempty"`
	CharData string `xml:"chardata"`
}

type AddressType struct {
	PostalAddresses   PostalAddresses   `xml:"http://uri.etsi.org/02231/v2# PostalAddresses"`
	ElectronicAddress ElectronicAddress `xml:"http://uri.etsi.org/02231/v2# ElectronicAddress"`
}

type PostalAddressListType struct {
	PostalAddress []PostalAddress `xml:"http://uri.etsi.org/02231/v2# PostalAddress"`
}

// Interface for types that extend PostalAddressListType
type IPostalAddressListType interface {
	IsEtsi022312PostalAddressListType()
}

// The type itself implements IPostalAddressListType
func (PostalAddressListType) IsEtsi022312PostalAddressListType() {}

type PostalAddressType struct {
	Lang            string `xml:"http://www.w3.org/XML/1998/namespace lang,attr,omitempty"`
	StreetAddress   string `xml:"http://uri.etsi.org/02231/v2# StreetAddress"`
	Locality        string `xml:"http://uri.etsi.org/02231/v2# Locality"`
	StateOrProvince string `xml:"http://uri.etsi.org/02231/v2# StateOrProvince,omitempty"`
	PostalCode      string `xml:"http://uri.etsi.org/02231/v2# PostalCode,omitempty"`
	CountryName     string `xml:"http://uri.etsi.org/02231/v2# CountryName"`
}

// Interface for types that extend PostalAddressType
type IPostalAddressType interface {
	IsEtsi022312PostalAddressType()
}

// The type itself implements IPostalAddressType
func (PostalAddressType) IsEtsi022312PostalAddressType() {}

type ElectronicAddressType struct {
	Uri []string `xml:"http://uri.etsi.org/02231/v2# URI"`
}

// Interface for types that extend ElectronicAddressType
type IElectronicAddressType interface {
	IsEtsi022312ElectronicAddressType()
}

// The type itself implements IElectronicAddressType
func (ElectronicAddressType) IsEtsi022312ElectronicAddressType() {}

type AnyType struct {
	UnknownContent string
}

// Interface for types that extend AnyType
type IAnyType interface {
	IsEtsi022312AnyType()
}

// The type itself implements IAnyType
func (AnyType) IsEtsi022312AnyType() {}

type ExtensionType struct {
	Critical       bool `xml:"Critical,attr"`
	UnknownContent string
}

// extends #/components/schemas/org.etsi022312/AnyType
func (ExtensionType) IsEtsi022312AnyType() {}

// Interface for types that extend ExtensionType
type IExtensionType interface {
	IsEtsi022312ExtensionType()
}

// The type itself implements IExtensionType
func (ExtensionType) IsEtsi022312ExtensionType() {}

type ExtensionsListType struct {
	Extension []Extension `xml:"http://uri.etsi.org/02231/v2# Extension"`
}

type NonEmptyMultiLangURIType struct {
	Lang     string `xml:"http://www.w3.org/XML/1998/namespace lang,attr,omitempty"`
	CharData string `xml:"chardata"`
}

type NonEmptyMultiLangURIListType struct {
	Uri []NonEmptyMultiLangURIType `xml:"http://uri.etsi.org/02231/v2# URI"`
}

// Interface for types that extend NonEmptyMultiLangURIListType
type INonEmptyMultiLangURIListType interface {
	IsEtsi022312NonEmptyMultiLangURIListType()
}

// The type itself implements INonEmptyMultiLangURIListType
func (NonEmptyMultiLangURIListType) IsEtsi022312NonEmptyMultiLangURIListType() {}

type NonEmptyURIListType struct {
	Uri []string `xml:"http://uri.etsi.org/02231/v2# URI"`
}

// Interface for types that extend NonEmptyURIListType
type INonEmptyURIListType interface {
	IsEtsi022312NonEmptyURIListType()
}

// The type itself implements INonEmptyURIListType
func (NonEmptyURIListType) IsEtsi022312NonEmptyURIListType() {}

type TrustStatusListType struct {
	TSLTag                   TSLTagType                `xml:"TSLTag,attr"`
	Id                       string                    `xml:"Id,attr,omitempty"`
	SchemeInformation        SchemeInformation         `xml:"http://uri.etsi.org/02231/v2# SchemeInformation"`
	TrustServiceProviderList *TrustServiceProviderList `xml:"http://uri.etsi.org/02231/v2# TrustServiceProviderList,omitempty"`
	Signature                *xmldsig.Signature        `xml:"http://www.w3.org/2000/09/xmldsig# Signature,omitempty"`
}

// Interface for types that extend TrustStatusListType
type ITrustStatusListType interface {
	IsEtsi022312TrustStatusListType()
}

// The type itself implements ITrustStatusListType
func (TrustStatusListType) IsEtsi022312TrustStatusListType() {}

type TSLTagType string

// Enum values for TSLTagType
const (
	TSLTagTypeHttpUriEtsiOrg02231TSLTag TSLTagType = "http://uri.etsi.org/02231/TSLTag"
)

func (v TSLTagType) IsValid() bool {
	switch v {
	case TSLTagTypeHttpUriEtsiOrg02231TSLTag:
		return true
	default:
		return false
	}
}

type TrustServiceProviderListType struct {
	TrustServiceProvider []TrustServiceProvider `xml:"http://uri.etsi.org/02231/v2# TrustServiceProvider"`
}

// Interface for types that extend TrustServiceProviderListType
type ITrustServiceProviderListType interface {
	IsEtsi022312TrustServiceProviderListType()
}

// The type itself implements ITrustServiceProviderListType
func (TrustServiceProviderListType) IsEtsi022312TrustServiceProviderListType() {}

type TSLSchemeInformationType struct {
	TSLVersionIdentifier        int                       `xml:"http://uri.etsi.org/02231/v2# TSLVersionIdentifier"`
	TSLSequenceNumber           int                       `xml:"http://uri.etsi.org/02231/v2# TSLSequenceNumber"`
	TSLType                     string                    `xml:"http://uri.etsi.org/02231/v2# TSLType"`
	SchemeOperatorName          SchemeOperatorName        `xml:"http://uri.etsi.org/02231/v2# SchemeOperatorName"`
	SchemeOperatorAddress       AddressType               `xml:"http://uri.etsi.org/02231/v2# SchemeOperatorAddress"`
	SchemeName                  SchemeName                `xml:"http://uri.etsi.org/02231/v2# SchemeName"`
	SchemeInformationURI        SchemeInformationURI      `xml:"http://uri.etsi.org/02231/v2# SchemeInformationURI"`
	StatusDeterminationApproach string                    `xml:"http://uri.etsi.org/02231/v2# StatusDeterminationApproach"`
	SchemeTypeCommunityRules    *SchemeTypeCommunityRules `xml:"http://uri.etsi.org/02231/v2# SchemeTypeCommunityRules,omitempty"`
	SchemeTerritory             string                    `xml:"http://uri.etsi.org/02231/v2# SchemeTerritory,omitempty"`
	PolicyOrLegalNotice         *PolicyOrLegalNotice      `xml:"http://uri.etsi.org/02231/v2# PolicyOrLegalNotice,omitempty"`
	HistoricalInformationPeriod int                       `xml:"http://uri.etsi.org/02231/v2# HistoricalInformationPeriod"`
	PointersToOtherTSL          *PointersToOtherTSL       `xml:"http://uri.etsi.org/02231/v2# PointersToOtherTSL,omitempty"`
	ListIssueDateTime           string                    `xml:"http://uri.etsi.org/02231/v2# ListIssueDateTime"`
	NextUpdate                  NextUpdate                `xml:"http://uri.etsi.org/02231/v2# NextUpdate"`
	DistributionPoints          *DistributionPoints       `xml:"http://uri.etsi.org/02231/v2# DistributionPoints,omitempty"`
	SchemeExtensions            *ExtensionsListType       `xml:"http://uri.etsi.org/02231/v2# SchemeExtensions,omitempty"`
}

// Interface for types that extend TSLSchemeInformationType
type ITSLSchemeInformationType interface {
	IsEtsi022312TSLSchemeInformationType()
}

// The type itself implements ITSLSchemeInformationType
func (TSLSchemeInformationType) IsEtsi022312TSLSchemeInformationType() {}

type PolicyOrLegalnoticeType struct {
	TSLPolicy      []NonEmptyMultiLangURIType `xml:"http://uri.etsi.org/02231/v2# TSLPolicy"`
	TSLLegalNotice []MultiLangStringType      `xml:"http://uri.etsi.org/02231/v2# TSLLegalNotice"`
}

// Interface for types that extend PolicyOrLegalnoticeType
type IPolicyOrLegalnoticeType interface {
	IsEtsi022312PolicyOrLegalnoticeType()
}

// The type itself implements IPolicyOrLegalnoticeType
func (PolicyOrLegalnoticeType) IsEtsi022312PolicyOrLegalnoticeType() {}

type NextUpdateType struct {
	DateTime string `xml:"http://uri.etsi.org/02231/v2# dateTime,omitempty"`
}

// Interface for types that extend NextUpdateType
type INextUpdateType interface {
	IsEtsi022312NextUpdateType()
}

// The type itself implements INextUpdateType
func (NextUpdateType) IsEtsi022312NextUpdateType() {}

type OtherTSLPointersType struct {
	OtherTSLPointer []OtherTSLPointer `xml:"http://uri.etsi.org/02231/v2# OtherTSLPointer"`
}

// Interface for types that extend OtherTSLPointersType
type IOtherTSLPointersType interface {
	IsEtsi022312OtherTSLPointersType()
}

// The type itself implements IOtherTSLPointersType
func (OtherTSLPointersType) IsEtsi022312OtherTSLPointersType() {}

type OtherTSLPointerType struct {
	ServiceDigitalIdentities *ServiceDigitalIdentities `xml:"http://uri.etsi.org/02231/v2# ServiceDigitalIdentities,omitempty"`
	TSLLocation              string                    `xml:"http://uri.etsi.org/02231/v2# TSLLocation"`
	AdditionalInformation    *AdditionalInformation    `xml:"http://uri.etsi.org/02231/v2# AdditionalInformation,omitempty"`
}

// Interface for types that extend OtherTSLPointerType
type IOtherTSLPointerType interface {
	IsEtsi022312OtherTSLPointerType()
}

// The type itself implements IOtherTSLPointerType
func (OtherTSLPointerType) IsEtsi022312OtherTSLPointerType() {}

type ServiceDigitalIdentityListType struct {
	ServiceDigitalIdentity []ServiceDigitalIdentity `xml:"http://uri.etsi.org/02231/v2# ServiceDigitalIdentity"`
}

// Interface for types that extend ServiceDigitalIdentityListType
type IServiceDigitalIdentityListType interface {
	IsEtsi022312ServiceDigitalIdentityListType()
}

// The type itself implements IServiceDigitalIdentityListType
func (ServiceDigitalIdentityListType) IsEtsi022312ServiceDigitalIdentityListType() {}

type AdditionalInformationType struct {
	TextualInformation []MultiLangStringType `xml:"http://uri.etsi.org/02231/v2# TextualInformation"`
	OtherInformation   []AnyType             `xml:"http://uri.etsi.org/02231/v2# OtherInformation"`
}

// Interface for types that extend AdditionalInformationType
type IAdditionalInformationType interface {
	IsEtsi022312AdditionalInformationType()
}

// The type itself implements IAdditionalInformationType
func (AdditionalInformationType) IsEtsi022312AdditionalInformationType() {}

type TSPType struct {
	TSPInformation TSPInformation `xml:"http://uri.etsi.org/02231/v2# TSPInformation"`
	TSPServices    TSPServices    `xml:"http://uri.etsi.org/02231/v2# TSPServices"`
}

// Interface for types that extend TSPType
type ITSPType interface {
	IsEtsi022312TSPType()
}

// The type itself implements ITSPType
func (TSPType) IsEtsi022312TSPType() {}

type TSPInformationType struct {
	TSPName                  InternationalNamesType       `xml:"http://uri.etsi.org/02231/v2# TSPName"`
	TSPTradeName             *InternationalNamesType      `xml:"http://uri.etsi.org/02231/v2# TSPTradeName,omitempty"`
	TSPAddress               AddressType                  `xml:"http://uri.etsi.org/02231/v2# TSPAddress"`
	TSPInformationURI        NonEmptyMultiLangURIListType `xml:"http://uri.etsi.org/02231/v2# TSPInformationURI"`
	TSPInformationExtensions *ExtensionsListType          `xml:"http://uri.etsi.org/02231/v2# TSPInformationExtensions,omitempty"`
}

// Interface for types that extend TSPInformationType
type ITSPInformationType interface {
	IsEtsi022312TSPInformationType()
}

// The type itself implements ITSPInformationType
func (TSPInformationType) IsEtsi022312TSPInformationType() {}

type TSPServicesListType struct {
	TSPService []TSPService `xml:"http://uri.etsi.org/02231/v2# TSPService"`
}

// Interface for types that extend TSPServicesListType
type ITSPServicesListType interface {
	IsEtsi022312TSPServicesListType()
}

// The type itself implements ITSPServicesListType
func (TSPServicesListType) IsEtsi022312TSPServicesListType() {}

type TSPServiceType struct {
	ServiceInformation ServiceInformation `xml:"http://uri.etsi.org/02231/v2# ServiceInformation"`
	ServiceHistory     *ServiceHistory    `xml:"http://uri.etsi.org/02231/v2# ServiceHistory,omitempty"`
}

// Interface for types that extend TSPServiceType
type ITSPServiceType interface {
	IsEtsi022312TSPServiceType()
}

// The type itself implements ITSPServiceType
func (TSPServiceType) IsEtsi022312TSPServiceType() {}

type TSPServiceInformationType struct {
	ServiceTypeIdentifier        string                        `xml:"http://uri.etsi.org/02231/v2# ServiceTypeIdentifier"`
	ServiceName                  InternationalNamesType        `xml:"http://uri.etsi.org/02231/v2# ServiceName"`
	ServiceDigitalIdentity       ServiceDigitalIdentity        `xml:"http://uri.etsi.org/02231/v2# ServiceDigitalIdentity"`
	ServiceStatus                string                        `xml:"http://uri.etsi.org/02231/v2# ServiceStatus"`
	StatusStartingTime           string                        `xml:"http://uri.etsi.org/02231/v2# StatusStartingTime"`
	SchemeServiceDefinitionURI   *NonEmptyMultiLangURIListType `xml:"http://uri.etsi.org/02231/v2# SchemeServiceDefinitionURI,omitempty"`
	ServiceSupplyPoints          *ServiceSupplyPoints          `xml:"http://uri.etsi.org/02231/v2# ServiceSupplyPoints,omitempty"`
	TSPServiceDefinitionURI      *NonEmptyMultiLangURIListType `xml:"http://uri.etsi.org/02231/v2# TSPServiceDefinitionURI,omitempty"`
	ServiceInformationExtensions *ExtensionsListType           `xml:"http://uri.etsi.org/02231/v2# ServiceInformationExtensions,omitempty"`
}

// Interface for types that extend TSPServiceInformationType
type ITSPServiceInformationType interface {
	IsEtsi022312TSPServiceInformationType()
}

// The type itself implements ITSPServiceInformationType
func (TSPServiceInformationType) IsEtsi022312TSPServiceInformationType() {}

type ServiceSupplyPointsType struct {
	ServiceSupplyPoint []string `xml:"http://uri.etsi.org/02231/v2# ServiceSupplyPoint"`
}

// Interface for types that extend ServiceSupplyPointsType
type IServiceSupplyPointsType interface {
	IsEtsi022312ServiceSupplyPointsType()
}

// The type itself implements IServiceSupplyPointsType
func (ServiceSupplyPointsType) IsEtsi022312ServiceSupplyPointsType() {}

type DigitalIdentityListType struct {
	DigitalId []DigitalIdentityType `xml:"http://uri.etsi.org/02231/v2# DigitalId"`
}

// Interface for types that extend DigitalIdentityListType
type IDigitalIdentityListType interface {
	IsEtsi022312DigitalIdentityListType()
}

// The type itself implements IDigitalIdentityListType
func (DigitalIdentityListType) IsEtsi022312DigitalIdentityListType() {}

type DigitalIdentityType struct {
	X509Certificate string            `xml:"http://uri.etsi.org/02231/v2# X509Certificate,omitempty"`
	X509SubjectName string            `xml:"http://uri.etsi.org/02231/v2# X509SubjectName,omitempty"`
	KeyValue        *xmldsig.KeyValue `xml:"http://www.w3.org/2000/09/xmldsig# KeyValue,omitempty"`
	X509ski         string            `xml:"http://uri.etsi.org/02231/v2# X509SKI,omitempty"`
	Other           *AnyType          `xml:"http://uri.etsi.org/02231/v2# Other,omitempty"`
}

type ServiceHistoryType struct {
	ServiceHistoryInstance []ServiceHistoryInstance `xml:"http://uri.etsi.org/02231/v2# ServiceHistoryInstance"`
}

// Interface for types that extend ServiceHistoryType
type IServiceHistoryType interface {
	IsEtsi022312ServiceHistoryType()
}

// The type itself implements IServiceHistoryType
func (ServiceHistoryType) IsEtsi022312ServiceHistoryType() {}

type ServiceHistoryInstanceType struct {
	ServiceTypeIdentifier        string                 `xml:"http://uri.etsi.org/02231/v2# ServiceTypeIdentifier"`
	ServiceName                  InternationalNamesType `xml:"http://uri.etsi.org/02231/v2# ServiceName"`
	ServiceDigitalIdentity       ServiceDigitalIdentity `xml:"http://uri.etsi.org/02231/v2# ServiceDigitalIdentity"`
	ServiceStatus                string                 `xml:"http://uri.etsi.org/02231/v2# ServiceStatus"`
	StatusStartingTime           string                 `xml:"http://uri.etsi.org/02231/v2# StatusStartingTime"`
	ServiceInformationExtensions *ExtensionsListType    `xml:"http://uri.etsi.org/02231/v2# ServiceInformationExtensions,omitempty"`
}

// Interface for types that extend ServiceHistoryInstanceType
type IServiceHistoryInstanceType interface {
	IsEtsi022312ServiceHistoryInstanceType()
}

// The type itself implements IServiceHistoryInstanceType
func (ServiceHistoryInstanceType) IsEtsi022312ServiceHistoryInstanceType() {}

type AdditionalServiceInformationType struct {
	Uri              NonEmptyMultiLangURIType `xml:"http://uri.etsi.org/02231/v2# URI"`
	InformationValue string                   `xml:"http://uri.etsi.org/02231/v2# InformationValue,omitempty"`
	OtherInformation *AnyType                 `xml:"http://uri.etsi.org/02231/v2# OtherInformation,omitempty"`
}

// Interface for types that extend AdditionalServiceInformationType
type IAdditionalServiceInformationType interface {
	IsEtsi022312AdditionalServiceInformationType()
}

// The type itself implements IAdditionalServiceInformationType
func (AdditionalServiceInformationType) IsEtsi022312AdditionalServiceInformationType() {}
