// Code generated by wsdl2openapi go generator. DO NOT EDIT.

package certificateservice601

import (
	"encoding/xml"
	error20 "github.com/gematik/zero-lab/go/kon/api/gematik/tel/error20"
)

type soapOperation struct {
	name        string
	soapAction  string
	bindingType string
}

func (op *soapOperation) Name() string {
	return op.name
}

func (op *soapOperation) SOAPAction() string {
	return op.soapAction
}

func (op *soapOperation) BindingType() string {
	return op.bindingType
}

var OperationCheckCertificateExpiration = soapOperation{
	bindingType: "soap11",
	name:        "CheckCertificateExpiration",
	soapAction:  "http://ws.gematik.de/conn/CertificateService/v6.0#CheckCertificateExpiration",
}

type CheckCertificateExpirationEnvelope struct {
	XMLName                    xml.Name                    `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	CheckCertificateExpiration *CheckCertificateExpiration `xml:"Body>CheckCertificateExpiration"`
}

func (e *CheckCertificateExpirationEnvelope) IsFault() bool {
	return false
}

type CheckCertificateExpirationResponseEnvelope struct {
	XMLName                            xml.Name                            `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	CheckCertificateExpirationResponse *CheckCertificateExpirationResponse `xml:"Body>CheckCertificateExpirationResponse"`
	Fault                              *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *CheckCertificateExpirationResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationReadCardCertificate = soapOperation{
	bindingType: "soap11",
	name:        "ReadCardCertificate",
	soapAction:  "http://ws.gematik.de/conn/CertificateService/v6.0#ReadCardCertificate",
}

type ReadCardCertificateEnvelope struct {
	XMLName             xml.Name             `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	ReadCardCertificate *ReadCardCertificate `xml:"Body>ReadCardCertificate"`
}

func (e *ReadCardCertificateEnvelope) IsFault() bool {
	return false
}

type ReadCardCertificateResponseEnvelope struct {
	XMLName                     xml.Name                     `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	ReadCardCertificateResponse *ReadCardCertificateResponse `xml:"Body>ReadCardCertificateResponse"`
	Fault                       *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *ReadCardCertificateResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationVerifyCertificate = soapOperation{
	bindingType: "soap11",
	name:        "VerifyCertificate",
	soapAction:  "http://ws.gematik.de/conn/CertificateService/v6.0#VerifyCertificate",
}

type VerifyCertificateEnvelope struct {
	XMLName           xml.Name           `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	VerifyCertificate *VerifyCertificate `xml:"Body>VerifyCertificate"`
}

func (e *VerifyCertificateEnvelope) IsFault() bool {
	return false
}

type VerifyCertificateResponseEnvelope struct {
	XMLName                   xml.Name                   `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	VerifyCertificateResponse *VerifyCertificateResponse `xml:"Body>VerifyCertificateResponse"`
	Fault                     *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *VerifyCertificateResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}
