// Code generated by wsdl2openapi go generator. DO NOT EDIT.

package authsignatureservice74

import (
	"encoding/xml"
	signatureservice74 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/signatureservice74"
	error20 "github.com/gematik/zero-lab/go/kon/api/gematik/tel/error20"
)

type soapOperation struct {
	name        string
	soapAction  string
	bindingType string
}

func (op *soapOperation) Name() string {
	return op.name
}

func (op *soapOperation) SOAPAction() string {
	return op.soapAction
}

func (op *soapOperation) BindingType() string {
	return op.bindingType
}

var OperationExternalAuthenticate = soapOperation{
	bindingType: "soap11",
	name:        "ExternalAuthenticate",
	soapAction:  "http://ws.gematik.de/conn/SignatureService/v7.4#ExternalAuthenticate",
}

type ExternalAuthenticateEnvelope struct {
	XMLName              xml.Name                                 `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	ExternalAuthenticate *signatureservice74.ExternalAuthenticate `xml:"Body>ExternalAuthenticate"`
}

func (e *ExternalAuthenticateEnvelope) IsFault() bool {
	return false
}

type ExternalAuthenticateResponseEnvelope struct {
	XMLName                      xml.Name                                         `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	ExternalAuthenticateResponse *signatureservice74.ExternalAuthenticateResponse `xml:"Body>ExternalAuthenticateResponse"`
	Fault                        *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *ExternalAuthenticateResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}
