// Code generated by wsdl2openapi; DO NOT EDIT.

package saml10assertion

import (
	"encoding/xml"
	xmldsig "github.com/gematik/zero-lab/go/kon/api/w3200009/xmldsig"
)

type Assertion struct {
	XMLName                        xml.Name                         `xml:"urn:oasis:names:tc:SAML:1.0:assertion Assertion"`
	MajorVersion                   int                              `xml:"MajorVersion,attr"`
	MinorVersion                   int                              `xml:"MinorVersion,attr"`
	AssertionID                    string                           `xml:"AssertionID,attr"`
	Issuer                         string                           `xml:"Issuer,attr"`
	IssueInstant                   string                           `xml:"IssueInstant,attr"`
	Conditions                     *Conditions                      `xml:"Conditions,omitempty"`
	Advice                         *Advice                          `xml:"Advice,omitempty"`
	Statement                      []Statement                      `xml:"Statement"`
	SubjectStatement               []SubjectStatement               `xml:"SubjectStatement"`
	AuthenticationStatement        []AuthenticationStatement        `xml:"AuthenticationStatement"`
	AuthorizationDecisionStatement []AuthorizationDecisionStatement `xml:"AuthorizationDecisionStatement"`
	AttributeStatement             []AttributeStatement             `xml:"AttributeStatement"`
	Signature                      *xmldsig.Signature               `xml:"http://www.w3.org/2000/09/xmldsig# Signature,omitempty"`
}

type Conditions struct {
	XMLName                      xml.Name                       `xml:"urn:oasis:names:tc:SAML:1.0:assertion Conditions"`
	NotBefore                    string                         `xml:"NotBefore,attr,omitempty"`
	NotOnOrAfter                 string                         `xml:"NotOnOrAfter,attr,omitempty"`
	AudienceRestrictionCondition []AudienceRestrictionCondition `xml:"AudienceRestrictionCondition"`
	DoNotCacheCondition          []DoNotCacheCondition          `xml:"DoNotCacheCondition"`
	Condition                    []Condition                    `xml:"Condition"`
}

type Condition struct {
	XMLName xml.Name `xml:"urn:oasis:names:tc:SAML:1.0:assertion Condition"`
}

type AudienceRestrictionCondition struct {
	XMLName  xml.Name `xml:"urn:oasis:names:tc:SAML:1.0:assertion AudienceRestrictionCondition"`
	Audience []string `xml:"Audience"`
}

type DoNotCacheCondition struct {
	XMLName  xml.Name `xml:"urn:oasis:names:tc:SAML:1.0:assertion DoNotCacheCondition"`
	CharData string   `xml:"chardata"`
}

type Advice struct {
	XMLName              xml.Name    `xml:"urn:oasis:names:tc:SAML:1.0:assertion Advice"`
	AssertionIDReference []string    `xml:"AssertionIDReference,omitempty"`
	Assertion            []Assertion `xml:"Assertion"`
	UnknownContent       string
}

type Statement struct {
	XMLName xml.Name `xml:"urn:oasis:names:tc:SAML:1.0:assertion Statement"`
}

type SubjectStatement struct {
	XMLName xml.Name `xml:"urn:oasis:names:tc:SAML:1.0:assertion SubjectStatement"`
	Subject Subject  `xml:"Subject"`
}

type Subject struct {
	XMLName             xml.Name             `xml:"urn:oasis:names:tc:SAML:1.0:assertion Subject"`
	NameIdentifier      NameIdentifier       `xml:"NameIdentifier"`
	SubjectConfirmation *SubjectConfirmation `xml:"SubjectConfirmation,omitempty"`
}

type NameIdentifier struct {
	XMLName       xml.Name `xml:"urn:oasis:names:tc:SAML:1.0:assertion NameIdentifier"`
	NameQualifier string   `xml:"NameQualifier,attr,omitempty"`
	Format        string   `xml:"Format,attr,omitempty"`
	CharData      string   `xml:"chardata"`
}

type SubjectConfirmation struct {
	XMLName                 xml.Name         `xml:"urn:oasis:names:tc:SAML:1.0:assertion SubjectConfirmation"`
	ConfirmationMethod      []string         `xml:"ConfirmationMethod"`
	SubjectConfirmationData string           `xml:"SubjectConfirmationData,omitempty"`
	KeyInfo                 *xmldsig.KeyInfo `xml:"http://www.w3.org/2000/09/xmldsig# KeyInfo,omitempty"`
}

type AuthenticationStatement struct {
	XMLName               xml.Name           `xml:"urn:oasis:names:tc:SAML:1.0:assertion AuthenticationStatement"`
	AuthenticationMethod  string             `xml:"AuthenticationMethod,attr"`
	AuthenticationInstant string             `xml:"AuthenticationInstant,attr"`
	Subject               Subject            `xml:"Subject"`
	SubjectLocality       *SubjectLocality   `xml:"SubjectLocality,omitempty"`
	AuthorityBinding      []AuthorityBinding `xml:"AuthorityBinding"`
}

type SubjectLocality struct {
	XMLName    xml.Name `xml:"urn:oasis:names:tc:SAML:1.0:assertion SubjectLocality"`
	IPAddress  string   `xml:"IPAddress,attr,omitempty"`
	DNSAddress string   `xml:"DNSAddress,attr,omitempty"`
}

type AuthorityBinding struct {
	XMLName       xml.Name `xml:"urn:oasis:names:tc:SAML:1.0:assertion AuthorityBinding"`
	AuthorityKind string   `xml:"AuthorityKind,attr"`
	Location      string   `xml:"Location,attr"`
	Binding       string   `xml:"Binding,attr"`
}

type AuthorizationDecisionStatement struct {
	XMLName  xml.Name     `xml:"urn:oasis:names:tc:SAML:1.0:assertion AuthorizationDecisionStatement"`
	Resource string       `xml:"Resource,attr"`
	Decision DecisionType `xml:"Decision,attr"`
	Subject  Subject      `xml:"Subject"`
	Action   []Action     `xml:"Action"`
	Evidence *Evidence    `xml:"Evidence,omitempty"`
}

type Action struct {
	XMLName   xml.Name `xml:"urn:oasis:names:tc:SAML:1.0:assertion Action"`
	Namespace string   `xml:"Namespace,attr,omitempty"`
	CharData  string   `xml:"chardata"`
}

type Evidence struct {
	XMLName              xml.Name    `xml:"urn:oasis:names:tc:SAML:1.0:assertion Evidence"`
	AssertionIDReference []string    `xml:"AssertionIDReference,omitempty"`
	Assertion            []Assertion `xml:"Assertion"`
}

type AttributeStatement struct {
	XMLName   xml.Name    `xml:"urn:oasis:names:tc:SAML:1.0:assertion AttributeStatement"`
	Subject   Subject     `xml:"Subject"`
	Attribute []Attribute `xml:"Attribute"`
}

type AttributeDesignator struct {
	XMLName            xml.Name `xml:"urn:oasis:names:tc:SAML:1.0:assertion AttributeDesignator"`
	AttributeName      string   `xml:"AttributeName,attr"`
	AttributeNamespace string   `xml:"AttributeNamespace,attr"`
}

type Attribute struct {
	XMLName            xml.Name `xml:"urn:oasis:names:tc:SAML:1.0:assertion Attribute"`
	AttributeName      string   `xml:"AttributeName,attr"`
	AttributeNamespace string   `xml:"AttributeNamespace,attr"`
	AttributeValue     []string `xml:"AttributeValue"`
}

type DecisionType string

// Enum values for DecisionType
const (
	DecisionTypePermit        DecisionType = "Permit"
	DecisionTypeDeny          DecisionType = "Deny"
	DecisionTypeIndeterminate DecisionType = "Indeterminate"
)

func (v DecisionType) IsValid() bool {
	switch v {
	case DecisionTypePermit:
		return true
	case DecisionTypeDeny:
		return true
	case DecisionTypeIndeterminate:
		return true
	default:
		return false
	}
}

type AssertionType struct {
	MajorVersion                   int                              `xml:"MajorVersion,attr"`
	MinorVersion                   int                              `xml:"MinorVersion,attr"`
	AssertionID                    string                           `xml:"AssertionID,attr"`
	Issuer                         string                           `xml:"Issuer,attr"`
	IssueInstant                   string                           `xml:"IssueInstant,attr"`
	Conditions                     *Conditions                      `xml:"urn:oasis:names:tc:SAML:1.0:assertion Conditions,omitempty"`
	Advice                         *Advice                          `xml:"urn:oasis:names:tc:SAML:1.0:assertion Advice,omitempty"`
	Statement                      []Statement                      `xml:"urn:oasis:names:tc:SAML:1.0:assertion Statement"`
	SubjectStatement               []SubjectStatement               `xml:"urn:oasis:names:tc:SAML:1.0:assertion SubjectStatement"`
	AuthenticationStatement        []AuthenticationStatement        `xml:"urn:oasis:names:tc:SAML:1.0:assertion AuthenticationStatement"`
	AuthorizationDecisionStatement []AuthorizationDecisionStatement `xml:"urn:oasis:names:tc:SAML:1.0:assertion AuthorizationDecisionStatement"`
	AttributeStatement             []AttributeStatement             `xml:"urn:oasis:names:tc:SAML:1.0:assertion AttributeStatement"`
	Signature                      *xmldsig.Signature               `xml:"http://www.w3.org/2000/09/xmldsig# Signature,omitempty"`
}

// Interface for types that extend AssertionType
type IAssertionType interface {
	IsAssertionAssertionType()
}

// The type itself implements IAssertionType
func (AssertionType) IsAssertionAssertionType() {}

type ConditionsType struct {
	NotBefore                    string                         `xml:"NotBefore,attr,omitempty"`
	NotOnOrAfter                 string                         `xml:"NotOnOrAfter,attr,omitempty"`
	AudienceRestrictionCondition []AudienceRestrictionCondition `xml:"urn:oasis:names:tc:SAML:1.0:assertion AudienceRestrictionCondition"`
	DoNotCacheCondition          []DoNotCacheCondition          `xml:"urn:oasis:names:tc:SAML:1.0:assertion DoNotCacheCondition"`
	Condition                    []Condition                    `xml:"urn:oasis:names:tc:SAML:1.0:assertion Condition"`
}

// Interface for types that extend ConditionsType
type IConditionsType interface {
	IsAssertionConditionsType()
}

// The type itself implements IConditionsType
func (ConditionsType) IsAssertionConditionsType() {}

type ConditionAbstractType struct{}

// Interface for types that extend ConditionAbstractType
type IConditionAbstractType interface {
	IsAssertionConditionAbstractType()
}

// The type itself implements IConditionAbstractType
func (ConditionAbstractType) IsAssertionConditionAbstractType() {}

type AudienceRestrictionConditionType struct {
	Audience []string `xml:"urn:oasis:names:tc:SAML:1.0:assertion Audience"`
}

// extends #/components/schemas/oasis.names.tc.SAML10.assertion/ConditionAbstractType
func (AudienceRestrictionConditionType) IsAssertionConditionAbstractType() {}

// Interface for types that extend AudienceRestrictionConditionType
type IAudienceRestrictionConditionType interface {
	IsAssertionAudienceRestrictionConditionType()
}

// The type itself implements IAudienceRestrictionConditionType
func (AudienceRestrictionConditionType) IsAssertionAudienceRestrictionConditionType() {}

type DoNotCacheConditionType struct {
	CharData string `xml:"chardata"`
}

// extends #/components/schemas/oasis.names.tc.SAML10.assertion/ConditionAbstractType
func (DoNotCacheConditionType) IsAssertionConditionAbstractType() {}

// Interface for types that extend DoNotCacheConditionType
type IDoNotCacheConditionType interface {
	IsAssertionDoNotCacheConditionType()
}

// The type itself implements IDoNotCacheConditionType
func (DoNotCacheConditionType) IsAssertionDoNotCacheConditionType() {}

type AdviceType struct {
	AssertionIDReference []string    `xml:"urn:oasis:names:tc:SAML:1.0:assertion AssertionIDReference,omitempty"`
	Assertion            []Assertion `xml:"urn:oasis:names:tc:SAML:1.0:assertion Assertion"`
	UnknownContent       string
}

// Interface for types that extend AdviceType
type IAdviceType interface {
	IsAssertionAdviceType()
}

// The type itself implements IAdviceType
func (AdviceType) IsAssertionAdviceType() {}

type StatementAbstractType struct{}

// Interface for types that extend StatementAbstractType
type IStatementAbstractType interface {
	IsAssertionStatementAbstractType()
}

// The type itself implements IStatementAbstractType
func (StatementAbstractType) IsAssertionStatementAbstractType() {}

type SubjectStatementAbstractType struct {
	Subject Subject `xml:"urn:oasis:names:tc:SAML:1.0:assertion Subject"`
}

// extends #/components/schemas/oasis.names.tc.SAML10.assertion/StatementAbstractType
func (SubjectStatementAbstractType) IsAssertionStatementAbstractType() {}

// Interface for types that extend SubjectStatementAbstractType
type ISubjectStatementAbstractType interface {
	IsAssertionSubjectStatementAbstractType()
}

// The type itself implements ISubjectStatementAbstractType
func (SubjectStatementAbstractType) IsAssertionSubjectStatementAbstractType() {}

type SubjectType struct {
	NameIdentifier      NameIdentifier       `xml:"urn:oasis:names:tc:SAML:1.0:assertion NameIdentifier"`
	SubjectConfirmation *SubjectConfirmation `xml:"urn:oasis:names:tc:SAML:1.0:assertion SubjectConfirmation,omitempty"`
}

// Interface for types that extend SubjectType
type ISubjectType interface {
	IsAssertionSubjectType()
}

// The type itself implements ISubjectType
func (SubjectType) IsAssertionSubjectType() {}

type NameIdentifierType struct {
	NameQualifier string `xml:"NameQualifier,attr,omitempty"`
	Format        string `xml:"Format,attr,omitempty"`
	CharData      string `xml:"chardata"`
}

// Interface for types that extend NameIdentifierType
type INameIdentifierType interface {
	IsAssertionNameIdentifierType()
}

// The type itself implements INameIdentifierType
func (NameIdentifierType) IsAssertionNameIdentifierType() {}

type SubjectConfirmationType struct {
	ConfirmationMethod      []string         `xml:"urn:oasis:names:tc:SAML:1.0:assertion ConfirmationMethod"`
	SubjectConfirmationData string           `xml:"urn:oasis:names:tc:SAML:1.0:assertion SubjectConfirmationData,omitempty"`
	KeyInfo                 *xmldsig.KeyInfo `xml:"http://www.w3.org/2000/09/xmldsig# KeyInfo,omitempty"`
}

// Interface for types that extend SubjectConfirmationType
type ISubjectConfirmationType interface {
	IsAssertionSubjectConfirmationType()
}

// The type itself implements ISubjectConfirmationType
func (SubjectConfirmationType) IsAssertionSubjectConfirmationType() {}

type AuthenticationStatementType struct {
	AuthenticationMethod  string             `xml:"AuthenticationMethod,attr"`
	AuthenticationInstant string             `xml:"AuthenticationInstant,attr"`
	Subject               Subject            `xml:"urn:oasis:names:tc:SAML:1.0:assertion Subject"`
	SubjectLocality       *SubjectLocality   `xml:"urn:oasis:names:tc:SAML:1.0:assertion SubjectLocality,omitempty"`
	AuthorityBinding      []AuthorityBinding `xml:"urn:oasis:names:tc:SAML:1.0:assertion AuthorityBinding"`
}

// extends #/components/schemas/oasis.names.tc.SAML10.assertion/SubjectStatementAbstractType
func (AuthenticationStatementType) IsAssertionSubjectStatementAbstractType() {}

// extends #/components/schemas/oasis.names.tc.SAML10.assertion/StatementAbstractType
func (AuthenticationStatementType) IsAssertionStatementAbstractType() {}

// Interface for types that extend AuthenticationStatementType
type IAuthenticationStatementType interface {
	IsAssertionAuthenticationStatementType()
}

// The type itself implements IAuthenticationStatementType
func (AuthenticationStatementType) IsAssertionAuthenticationStatementType() {}

type SubjectLocalityType struct {
	IPAddress  string `xml:"IPAddress,attr,omitempty"`
	DNSAddress string `xml:"DNSAddress,attr,omitempty"`
}

// Interface for types that extend SubjectLocalityType
type ISubjectLocalityType interface {
	IsAssertionSubjectLocalityType()
}

// The type itself implements ISubjectLocalityType
func (SubjectLocalityType) IsAssertionSubjectLocalityType() {}

type AuthorityBindingType struct {
	AuthorityKind string `xml:"AuthorityKind,attr"`
	Location      string `xml:"Location,attr"`
	Binding       string `xml:"Binding,attr"`
}

// Interface for types that extend AuthorityBindingType
type IAuthorityBindingType interface {
	IsAssertionAuthorityBindingType()
}

// The type itself implements IAuthorityBindingType
func (AuthorityBindingType) IsAssertionAuthorityBindingType() {}

type AuthorizationDecisionStatementType struct {
	Resource string       `xml:"Resource,attr"`
	Decision DecisionType `xml:"Decision,attr"`
	Subject  Subject      `xml:"urn:oasis:names:tc:SAML:1.0:assertion Subject"`
	Action   []Action     `xml:"urn:oasis:names:tc:SAML:1.0:assertion Action"`
	Evidence *Evidence    `xml:"urn:oasis:names:tc:SAML:1.0:assertion Evidence,omitempty"`
}

// extends #/components/schemas/oasis.names.tc.SAML10.assertion/SubjectStatementAbstractType
func (AuthorizationDecisionStatementType) IsAssertionSubjectStatementAbstractType() {}

// extends #/components/schemas/oasis.names.tc.SAML10.assertion/StatementAbstractType
func (AuthorizationDecisionStatementType) IsAssertionStatementAbstractType() {}

// Interface for types that extend AuthorizationDecisionStatementType
type IAuthorizationDecisionStatementType interface {
	IsAssertionAuthorizationDecisionStatementType()
}

// The type itself implements IAuthorizationDecisionStatementType
func (AuthorizationDecisionStatementType) IsAssertionAuthorizationDecisionStatementType() {}

type ActionType struct {
	Namespace string `xml:"Namespace,attr,omitempty"`
	CharData  string `xml:"chardata"`
}

// Interface for types that extend ActionType
type IActionType interface {
	IsAssertionActionType()
}

// The type itself implements IActionType
func (ActionType) IsAssertionActionType() {}

type EvidenceType struct {
	AssertionIDReference []string    `xml:"urn:oasis:names:tc:SAML:1.0:assertion AssertionIDReference,omitempty"`
	Assertion            []Assertion `xml:"urn:oasis:names:tc:SAML:1.0:assertion Assertion"`
}

// Interface for types that extend EvidenceType
type IEvidenceType interface {
	IsAssertionEvidenceType()
}

// The type itself implements IEvidenceType
func (EvidenceType) IsAssertionEvidenceType() {}

type AttributeStatementType struct {
	Subject   Subject     `xml:"urn:oasis:names:tc:SAML:1.0:assertion Subject"`
	Attribute []Attribute `xml:"urn:oasis:names:tc:SAML:1.0:assertion Attribute"`
}

// extends #/components/schemas/oasis.names.tc.SAML10.assertion/SubjectStatementAbstractType
func (AttributeStatementType) IsAssertionSubjectStatementAbstractType() {}

// extends #/components/schemas/oasis.names.tc.SAML10.assertion/StatementAbstractType
func (AttributeStatementType) IsAssertionStatementAbstractType() {}

// Interface for types that extend AttributeStatementType
type IAttributeStatementType interface {
	IsAssertionAttributeStatementType()
}

// The type itself implements IAttributeStatementType
func (AttributeStatementType) IsAssertionAttributeStatementType() {}

type AttributeDesignatorType struct {
	AttributeName      string `xml:"AttributeName,attr"`
	AttributeNamespace string `xml:"AttributeNamespace,attr"`
}

// Interface for types that extend AttributeDesignatorType
type IAttributeDesignatorType interface {
	IsAssertionAttributeDesignatorType()
}

// The type itself implements IAttributeDesignatorType
func (AttributeDesignatorType) IsAssertionAttributeDesignatorType() {}

type AttributeType struct {
	AttributeName      string   `xml:"AttributeName,attr"`
	AttributeNamespace string   `xml:"AttributeNamespace,attr"`
	AttributeValue     []string `xml:"urn:oasis:names:tc:SAML:1.0:assertion AttributeValue"`
}

// extends #/components/schemas/oasis.names.tc.SAML10.assertion/AttributeDesignatorType
func (AttributeType) IsAssertionAttributeDesignatorType() {}

// Interface for types that extend AttributeType
type IAttributeType interface {
	IsAssertionAttributeType()
}

// The type itself implements IAttributeType
func (AttributeType) IsAssertionAttributeType() {}
