// Code generated by addchain. DO NOT EDIT.

package fiatn

// Invert sets e = 1/x mod n, and returns e.
//
// If x == 0, Invert returns e = 0.
func (e *Element) Invert(x *Element) *Element {
	// Inversion is implemented as exponentiation with exponent n − 2.
	// The sequence of 58 multiplications and 251 squarings is derived from the
	// following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
	//
	//	_10     = 2*1
	//	_11     = 1 + _10
	//	_101    = _10 + _11
	//	_111    = _10 + _101
	//	_1001   = _10 + _111
	//	_1011   = _10 + _1001
	//	_1101   = _10 + _1011
	//	_1111   = _10 + _1101
	//	_10001  = _10 + _1111
	//	_10011  = _10 + _10001
	//	_10101  = _10 + _10011
	//	_10111  = _10 + _10101
	//	_11001  = _10 + _10111
	//	_11011  = _10 + _11001
	//	_11101  = _10 + _11011
	//	_11111  = _10 + _11101
	//	_101010 = _1011 + _11111
	//	i31     = (2*(_101010 << 6 + _11111) + 1) << 5
	//	i45     = ((_1101 + i31) << 6 + _10111) << 5 + _11011
	//	i67     = ((i45 << 6 + _11101) << 8 + _1111) << 6
	//	i81     = ((_11101 + i67) << 4 + _101) << 7 + _11011
	//	i101    = ((i81 << 2 + _11) << 9 + _11111) << 7
	//	i115    = (2*(_11001 + i101) + 1) << 10 + _10101
	//	i133    = ((i115 << 3 + 1) << 9 + _10011) << 4
	//	i151    = ((_1011 + i133) << 8 + _111) << 7 + _1101
	//	i167    = ((i151 << 4 + _111) << 5 + _11) << 5
	//	i184    = ((_11 + i167) << 7 + _111) << 7 + _10111
	//	i202    = ((i184 << 5 + _10101) << 6 + _10001) << 5
	//	i212    = 2*((_11011 + i202) << 6 + _10101) + 1
	//	i234    = ((i212 << 8 + _1101) << 7 + _11011) << 5
	//	i253    = ((_11011 + i234) << 5 + _11001) << 11 + _1111
	//	i280    = ((i253 << 10 + _11101) << 8 + _101) << 7
	//	i297    = ((_10111 + i280) << 5 + _1001) << 9 + _10101
	//	return    (i297 << 5 + _10101) << 5 + _101
	//

	var z = new(Element).Set(e)
	var t0 = new(Element)
	var t1 = new(Element)
	var t2 = new(Element)
	var t3 = new(Element)
	var t4 = new(Element)
	var t5 = new(Element)
	var t6 = new(Element)
	var t7 = new(Element)
	var t8 = new(Element)
	var t9 = new(Element)
	var t10 = new(Element)
	var t11 = new(Element)
	var t12 = new(Element)
	var t13 = new(Element)
	var t14 = new(Element)

	t13.Square(x)
	t10.Mul(x, t13)
	z.Mul(t13, t10)
	t9.Mul(t13, z)
	t1.Mul(t13, t9)
	t11.Mul(t13, t1)
	t7.Mul(t13, t11)
	t4.Mul(t13, t7)
	t8.Mul(t13, t4)
	t12.Mul(t13, t8)
	t0.Mul(t13, t12)
	t2.Mul(t13, t0)
	t5.Mul(t13, t2)
	t6.Mul(t13, t5)
	t3.Mul(t13, t6)
	t13.Mul(t13, t3)
	t14.Mul(t11, t13)
	for s := 0; s < 6; s++ {
		t14.Square(t14)
	}
	t14.Mul(t13, t14)
	t14.Square(t14)
	t14.Mul(x, t14)
	for s := 0; s < 5; s++ {
		t14.Square(t14)
	}
	t14.Mul(t7, t14)
	for s := 0; s < 6; s++ {
		t14.Square(t14)
	}
	t14.Mul(t2, t14)
	for s := 0; s < 5; s++ {
		t14.Square(t14)
	}
	t14.Mul(t6, t14)
	for s := 0; s < 6; s++ {
		t14.Square(t14)
	}
	t14.Mul(t3, t14)
	for s := 0; s < 8; s++ {
		t14.Square(t14)
	}
	t14.Mul(t4, t14)
	for s := 0; s < 6; s++ {
		t14.Square(t14)
	}
	t14.Mul(t3, t14)
	for s := 0; s < 4; s++ {
		t14.Square(t14)
	}
	t14.Mul(z, t14)
	for s := 0; s < 7; s++ {
		t14.Square(t14)
	}
	t14.Mul(t6, t14)
	for s := 0; s < 2; s++ {
		t14.Square(t14)
	}
	t14.Mul(t10, t14)
	for s := 0; s < 9; s++ {
		t14.Square(t14)
	}
	t13.Mul(t13, t14)
	for s := 0; s < 7; s++ {
		t13.Square(t13)
	}
	t13.Mul(t5, t13)
	t13.Square(t13)
	t13.Mul(x, t13)
	for s := 0; s < 10; s++ {
		t13.Square(t13)
	}
	t13.Mul(t0, t13)
	for s := 0; s < 3; s++ {
		t13.Square(t13)
	}
	t13.Mul(x, t13)
	for s := 0; s < 9; s++ {
		t13.Square(t13)
	}
	t12.Mul(t12, t13)
	for s := 0; s < 4; s++ {
		t12.Square(t12)
	}
	t11.Mul(t11, t12)
	for s := 0; s < 8; s++ {
		t11.Square(t11)
	}
	t11.Mul(t9, t11)
	for s := 0; s < 7; s++ {
		t11.Square(t11)
	}
	t11.Mul(t7, t11)
	for s := 0; s < 4; s++ {
		t11.Square(t11)
	}
	t11.Mul(t9, t11)
	for s := 0; s < 5; s++ {
		t11.Square(t11)
	}
	t11.Mul(t10, t11)
	for s := 0; s < 5; s++ {
		t11.Square(t11)
	}
	t10.Mul(t10, t11)
	for s := 0; s < 7; s++ {
		t10.Square(t10)
	}
	t9.Mul(t9, t10)
	for s := 0; s < 7; s++ {
		t9.Square(t9)
	}
	t9.Mul(t2, t9)
	for s := 0; s < 5; s++ {
		t9.Square(t9)
	}
	t9.Mul(t0, t9)
	for s := 0; s < 6; s++ {
		t9.Square(t9)
	}
	t8.Mul(t8, t9)
	for s := 0; s < 5; s++ {
		t8.Square(t8)
	}
	t8.Mul(t6, t8)
	for s := 0; s < 6; s++ {
		t8.Square(t8)
	}
	t8.Mul(t0, t8)
	t8.Square(t8)
	t8.Mul(x, t8)
	for s := 0; s < 8; s++ {
		t8.Square(t8)
	}
	t7.Mul(t7, t8)
	for s := 0; s < 7; s++ {
		t7.Square(t7)
	}
	t7.Mul(t6, t7)
	for s := 0; s < 5; s++ {
		t7.Square(t7)
	}
	t6.Mul(t6, t7)
	for s := 0; s < 5; s++ {
		t6.Square(t6)
	}
	t5.Mul(t5, t6)
	for s := 0; s < 11; s++ {
		t5.Square(t5)
	}
	t4.Mul(t4, t5)
	for s := 0; s < 10; s++ {
		t4.Square(t4)
	}
	t3.Mul(t3, t4)
	for s := 0; s < 8; s++ {
		t3.Square(t3)
	}
	t3.Mul(z, t3)
	for s := 0; s < 7; s++ {
		t3.Square(t3)
	}
	t2.Mul(t2, t3)
	for s := 0; s < 5; s++ {
		t2.Square(t2)
	}
	t1.Mul(t1, t2)
	for s := 0; s < 9; s++ {
		t1.Square(t1)
	}
	t1.Mul(t0, t1)
	for s := 0; s < 5; s++ {
		t1.Square(t1)
	}
	t0.Mul(t0, t1)
	for s := 0; s < 5; s++ {
		t0.Square(t0)
	}
	z.Mul(z, t0)

	return e.Set(z)
}
