// Code generated by wsdl2openapi; DO NOT EDIT.

package xmlenc

import (
	"encoding/base64"
	"encoding/xml"
	xmldsig "github.com/gematik/zero-lab/go/kon/api/w3200009/xmldsig"
)

type CipherData struct {
	XMLName         xml.Name         `xml:"http://www.w3.org/2001/04/xmlenc# CipherData"`
	CipherValue     Base64Bytes      `xml:"CipherValue,omitempty"`
	CipherReference *CipherReference `xml:"CipherReference,omitempty"`
}

type CipherReference struct {
	XMLName    xml.Name        `xml:"http://www.w3.org/2001/04/xmlenc# CipherReference"`
	Uri        string          `xml:"URI,attr"`
	Transforms *TransformsType `xml:"Transforms,omitempty"`
}

type EncryptedData struct {
	XMLName              xml.Name              `xml:"http://www.w3.org/2001/04/xmlenc# EncryptedData"`
	Id                   string                `xml:"Id,attr,omitempty"`
	Type                 string                `xml:"Type,attr,omitempty"`
	MimeType             string                `xml:"MimeType,attr,omitempty"`
	Encoding             string                `xml:"Encoding,attr,omitempty"`
	EncryptionMethod     *EncryptionMethodType `xml:"EncryptionMethod,omitempty"`
	KeyInfo              *xmldsig.KeyInfo      `xml:"http://www.w3.org/2000/09/xmldsig# KeyInfo,omitempty"`
	CipherData           CipherData            `xml:"CipherData"`
	EncryptionProperties *EncryptionProperties `xml:"EncryptionProperties,omitempty"`
}

type EncryptedKey struct {
	XMLName              xml.Name              `xml:"http://www.w3.org/2001/04/xmlenc# EncryptedKey"`
	Id                   string                `xml:"Id,attr,omitempty"`
	Type                 string                `xml:"Type,attr,omitempty"`
	MimeType             string                `xml:"MimeType,attr,omitempty"`
	Encoding             string                `xml:"Encoding,attr,omitempty"`
	Recipient            string                `xml:"Recipient,attr,omitempty"`
	EncryptionMethod     *EncryptionMethodType `xml:"EncryptionMethod,omitempty"`
	KeyInfo              *xmldsig.KeyInfo      `xml:"http://www.w3.org/2000/09/xmldsig# KeyInfo,omitempty"`
	CipherData           CipherData            `xml:"CipherData"`
	EncryptionProperties *EncryptionProperties `xml:"EncryptionProperties,omitempty"`
	ReferenceList        *ReferenceList        `xml:"ReferenceList,omitempty"`
	CarriedKeyName       string                `xml:"CarriedKeyName,omitempty"`
}

type AgreementMethod struct {
	XMLName           xml.Name    `xml:"http://www.w3.org/2001/04/xmlenc# AgreementMethod"`
	Algorithm         string      `xml:"Algorithm,attr"`
	KaNonce           Base64Bytes `xml:"KA-Nonce,omitempty"`
	UnknownContent    string
	OriginatorKeyInfo *xmldsig.KeyInfoType `xml:"OriginatorKeyInfo,omitempty"`
	RecipientKeyInfo  *xmldsig.KeyInfoType `xml:"RecipientKeyInfo,omitempty"`
}

type ReferenceList struct {
	XMLName       xml.Name        `xml:"http://www.w3.org/2001/04/xmlenc# ReferenceList"`
	DataReference []ReferenceType `xml:"DataReference"`
	KeyReference  []ReferenceType `xml:"KeyReference"`
}

type EncryptionProperties struct {
	XMLName            xml.Name             `xml:"http://www.w3.org/2001/04/xmlenc# EncryptionProperties"`
	Id                 string               `xml:"Id,attr,omitempty"`
	EncryptionProperty []EncryptionProperty `xml:"EncryptionProperty"`
}

type EncryptionProperty struct {
	XMLName           xml.Name `xml:"http://www.w3.org/2001/04/xmlenc# EncryptionProperty"`
	Target            string   `xml:"Target,attr,omitempty"`
	Id                string   `xml:"Id,attr,omitempty"`
	UnknownAttributes string   `xml:"anyAttribute,attr,omitempty"`
	UnknownContent    string
}

type DHKeyValue struct {
	XMLName     xml.Name    `xml:"http://www.w3.org/2001/04/xmlenc# DHKeyValue"`
	P           Base64Bytes `xml:"P"`
	Q           Base64Bytes `xml:"Q"`
	Generator   Base64Bytes `xml:"Generator"`
	Public      Base64Bytes `xml:"Public"`
	Seed        Base64Bytes `xml:"seed"`
	PgenCounter Base64Bytes `xml:"pgenCounter"`
}

type EncryptedType struct {
	Id                   string                `xml:"Id,attr,omitempty"`
	Type                 string                `xml:"Type,attr,omitempty"`
	MimeType             string                `xml:"MimeType,attr,omitempty"`
	Encoding             string                `xml:"Encoding,attr,omitempty"`
	EncryptionMethod     *EncryptionMethodType `xml:"http://www.w3.org/2001/04/xmlenc# EncryptionMethod,omitempty"`
	KeyInfo              *xmldsig.KeyInfo      `xml:"http://www.w3.org/2000/09/xmldsig# KeyInfo,omitempty"`
	CipherData           CipherData            `xml:"http://www.w3.org/2001/04/xmlenc# CipherData"`
	EncryptionProperties *EncryptionProperties `xml:"http://www.w3.org/2001/04/xmlenc# EncryptionProperties,omitempty"`
}

// Interface for types that extend EncryptedType
type IEncryptedType interface {
	IsXmlencEncryptedType()
}

// The type itself implements IEncryptedType
func (EncryptedType) IsXmlencEncryptedType() {}

type EncryptionMethodType struct {
	Algorithm      string      `xml:"Algorithm,attr"`
	KeySize        int         `xml:"http://www.w3.org/2001/04/xmlenc# KeySize,omitempty"`
	OaePparams     Base64Bytes `xml:"http://www.w3.org/2001/04/xmlenc# OAEPparams,omitempty"`
	UnknownContent string
}

type CipherDataType struct {
	CipherValue     Base64Bytes      `xml:"http://www.w3.org/2001/04/xmlenc# CipherValue,omitempty"`
	CipherReference *CipherReference `xml:"http://www.w3.org/2001/04/xmlenc# CipherReference,omitempty"`
}

// Interface for types that extend CipherDataType
type ICipherDataType interface {
	IsXmlencCipherDataType()
}

// The type itself implements ICipherDataType
func (CipherDataType) IsXmlencCipherDataType() {}

type CipherReferenceType struct {
	Uri        string          `xml:"URI,attr"`
	Transforms *TransformsType `xml:"http://www.w3.org/2001/04/xmlenc# Transforms,omitempty"`
}

// Interface for types that extend CipherReferenceType
type ICipherReferenceType interface {
	IsXmlencCipherReferenceType()
}

// The type itself implements ICipherReferenceType
func (CipherReferenceType) IsXmlencCipherReferenceType() {}

type TransformsType struct {
	Transform []xmldsig.Transform `xml:"http://www.w3.org/2000/09/xmldsig# Transform"`
}

type EncryptedDataType struct {
	Id                   string                `xml:"Id,attr,omitempty"`
	Type                 string                `xml:"Type,attr,omitempty"`
	MimeType             string                `xml:"MimeType,attr,omitempty"`
	Encoding             string                `xml:"Encoding,attr,omitempty"`
	EncryptionMethod     *EncryptionMethodType `xml:"http://www.w3.org/2001/04/xmlenc# EncryptionMethod,omitempty"`
	KeyInfo              *xmldsig.KeyInfo      `xml:"http://www.w3.org/2000/09/xmldsig# KeyInfo,omitempty"`
	CipherData           CipherData            `xml:"http://www.w3.org/2001/04/xmlenc# CipherData"`
	EncryptionProperties *EncryptionProperties `xml:"http://www.w3.org/2001/04/xmlenc# EncryptionProperties,omitempty"`
}

// extends #/components/schemas/org.w3200104.xmlenc.EncryptedType
func (EncryptedDataType) IsXmlencEncryptedType() {}

// Interface for types that extend EncryptedDataType
type IEncryptedDataType interface {
	IsXmlencEncryptedDataType()
}

// The type itself implements IEncryptedDataType
func (EncryptedDataType) IsXmlencEncryptedDataType() {}

type EncryptedKeyType struct {
	Id                   string                `xml:"Id,attr,omitempty"`
	Type                 string                `xml:"Type,attr,omitempty"`
	MimeType             string                `xml:"MimeType,attr,omitempty"`
	Encoding             string                `xml:"Encoding,attr,omitempty"`
	Recipient            string                `xml:"Recipient,attr,omitempty"`
	EncryptionMethod     *EncryptionMethodType `xml:"http://www.w3.org/2001/04/xmlenc# EncryptionMethod,omitempty"`
	KeyInfo              *xmldsig.KeyInfo      `xml:"http://www.w3.org/2000/09/xmldsig# KeyInfo,omitempty"`
	CipherData           CipherData            `xml:"http://www.w3.org/2001/04/xmlenc# CipherData"`
	EncryptionProperties *EncryptionProperties `xml:"http://www.w3.org/2001/04/xmlenc# EncryptionProperties,omitempty"`
	ReferenceList        *ReferenceList        `xml:"http://www.w3.org/2001/04/xmlenc# ReferenceList,omitempty"`
	CarriedKeyName       string                `xml:"http://www.w3.org/2001/04/xmlenc# CarriedKeyName,omitempty"`
}

// extends #/components/schemas/org.w3200104.xmlenc.EncryptedType
func (EncryptedKeyType) IsXmlencEncryptedType() {}

// Interface for types that extend EncryptedKeyType
type IEncryptedKeyType interface {
	IsXmlencEncryptedKeyType()
}

// The type itself implements IEncryptedKeyType
func (EncryptedKeyType) IsXmlencEncryptedKeyType() {}

type AgreementMethodType struct {
	Algorithm         string      `xml:"Algorithm,attr"`
	KaNonce           Base64Bytes `xml:"http://www.w3.org/2001/04/xmlenc# KA-Nonce,omitempty"`
	UnknownContent    string
	OriginatorKeyInfo *xmldsig.KeyInfoType `xml:"http://www.w3.org/2001/04/xmlenc# OriginatorKeyInfo,omitempty"`
	RecipientKeyInfo  *xmldsig.KeyInfoType `xml:"http://www.w3.org/2001/04/xmlenc# RecipientKeyInfo,omitempty"`
}

// Interface for types that extend AgreementMethodType
type IAgreementMethodType interface {
	IsXmlencAgreementMethodType()
}

// The type itself implements IAgreementMethodType
func (AgreementMethodType) IsXmlencAgreementMethodType() {}

type ReferenceType struct {
	Uri            string `xml:"URI,attr"`
	UnknownContent string
}

type EncryptionPropertiesType struct {
	Id                 string               `xml:"Id,attr,omitempty"`
	EncryptionProperty []EncryptionProperty `xml:"http://www.w3.org/2001/04/xmlenc# EncryptionProperty"`
}

// Interface for types that extend EncryptionPropertiesType
type IEncryptionPropertiesType interface {
	IsXmlencEncryptionPropertiesType()
}

// The type itself implements IEncryptionPropertiesType
func (EncryptionPropertiesType) IsXmlencEncryptionPropertiesType() {}

type EncryptionPropertyType struct {
	Target            string `xml:"Target,attr,omitempty"`
	Id                string `xml:"Id,attr,omitempty"`
	UnknownAttributes string `xml:"anyAttribute,attr,omitempty"`
	UnknownContent    string
}

// Interface for types that extend EncryptionPropertyType
type IEncryptionPropertyType interface {
	IsXmlencEncryptionPropertyType()
}

// The type itself implements IEncryptionPropertyType
func (EncryptionPropertyType) IsXmlencEncryptionPropertyType() {}

type DHKeyValueType struct {
	P           Base64Bytes `xml:"http://www.w3.org/2001/04/xmlenc# P"`
	Q           Base64Bytes `xml:"http://www.w3.org/2001/04/xmlenc# Q"`
	Generator   Base64Bytes `xml:"http://www.w3.org/2001/04/xmlenc# Generator"`
	Public      Base64Bytes `xml:"http://www.w3.org/2001/04/xmlenc# Public"`
	Seed        Base64Bytes `xml:"http://www.w3.org/2001/04/xmlenc# seed"`
	PgenCounter Base64Bytes `xml:"http://www.w3.org/2001/04/xmlenc# pgenCounter"`
}

// Interface for types that extend DHKeyValueType
type IDHKeyValueType interface {
	IsXmlencDHKeyValueType()
}

// The type itself implements IDHKeyValueType
func (DHKeyValueType) IsXmlencDHKeyValueType() {}

type Base64Bytes []byte

func (b *Base64Bytes) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var s string
	if err := d.DecodeElement(&s, &start); err != nil {
		return err
	}
	decoded, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		return err
	}
	*b = decoded
	return nil
}

func (b Base64Bytes) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.EncodeElement(base64.StdEncoding.EncodeToString(b), start)
}
