// Code generated by wsdl2openapi; DO NOT EDIT.

package productinformation11

import "encoding/xml"

type ProductInformation struct {
	XMLName                xml.Name               `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductInformation"`
	InformationDate        string                 `xml:"InformationDate"`
	ProductTypeInformation ProductTypeInformation `xml:"ProductTypeInformation"`
	ProductIdentification  ProductIdentification  `xml:"ProductIdentification"`
	ProductMiscellaneous   ProductMiscellaneous   `xml:"ProductMiscellaneous"`
}

type ProductVersionLocal struct {
	HWVersion string `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 HWVersion"`
	FWVersion string `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 FWVersion"`
}

type ProductVersion struct {
	Local   *ProductVersionLocal `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 Local,omitempty"`
	Central string               `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 Central,omitempty"`
}

type ProductTypeInformation struct {
	ProductType        string `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductType"`
	ProductTypeVersion string `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductTypeVersion"`
}

type ProductIdentification struct {
	ProductVendorID string         `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductVendorID"`
	ProductCode     string         `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductCode"`
	ProductVersion  ProductVersion `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductVersion"`
}

type ProductMiscellaneous struct {
	ProductVendorName string `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductVendorName"`
	ProductName       string `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductName"`
}

type ProductInformationElementType struct {
	InformationDate        string                 `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 InformationDate"`
	ProductTypeInformation ProductTypeInformation `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductTypeInformation"`
	ProductIdentification  ProductIdentification  `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductIdentification"`
	ProductMiscellaneous   ProductMiscellaneous   `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductMiscellaneous"`
}

// Interface for types that extend ProductInformationElementType
type IProductInformationElementType interface {
	IsProductInformation11ProductInformationElementType()
}

// The type itself implements IProductInformationElementType
func (ProductInformationElementType) IsProductInformation11ProductInformationElementType() {}
