// Code generated by wsdl2openapi; DO NOT EDIT.

package encryptionservice61

import (
	"encoding/xml"
	connectorcommon50 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/connectorcommon50"
	connectorcontext20 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/connectorcontext20"
	dss10core "github.com/gematik/zero-lab/go/kon/api/oasis/dss10core"
)

type EncryptDocument struct {
	XMLName        xml.Name                       `xml:"http://ws.gematik.de/conn/EncryptionService/v6.1 EncryptDocument"`
	Context        connectorcontext20.Context     `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	RecipientKeys  EncryptDocumentRecipientKeys   `xml:"RecipientKeys"`
	Document       connectorcommon50.Document     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Document"`
	OptionalInputs *EncryptDocumentOptionalInputs `xml:"OptionalInputs,omitempty"`
}

type EncryptDocumentResponse struct {
	XMLName         xml.Name                    `xml:"http://ws.gematik.de/conn/EncryptionService/v6.1 EncryptDocumentResponse"`
	Status          connectorcommon50.Status    `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	OptionalOutputs string                      `xml:"OptionalOutputs,omitempty"`
	Document        *connectorcommon50.Document `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Document,omitempty"`
}

type CertificateOnCard struct {
	XMLName      xml.Name `xml:"http://ws.gematik.de/conn/EncryptionService/v6.1 CertificateOnCard"`
	CardHandle   string   `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	KeyReference string   `xml:"KeyReference,omitempty"`
}

type PrivateKeyOnCard struct {
	XMLName      xml.Name `xml:"http://ws.gematik.de/conn/EncryptionService/v6.1 PrivateKeyOnCard"`
	CardHandle   string   `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	KeyReference string   `xml:"KeyReference,omitempty"`
}

type EncryptionType string

// Enum values for EncryptionType
const (
	EncryptionTypeHttpWwwW3OrgTRXmlencCore EncryptionType = "http://www.w3.org/TR/xmlenc-core/"
	EncryptionTypeUrnIetfRfc5652           EncryptionType = "urn:ietf:rfc:5652"
	EncryptionTypeUrnIetfRfc5751           EncryptionType = "urn:ietf:rfc:5751"
)

func (v EncryptionType) IsValid() bool {
	switch v {
	case EncryptionTypeHttpWwwW3OrgTRXmlencCore:
		return true
	case EncryptionTypeUrnIetfRfc5652:
		return true
	case EncryptionTypeUrnIetfRfc5751:
		return true
	default:
		return false
	}
}

type Element struct {
	XMLName  xml.Name `xml:"http://ws.gematik.de/conn/EncryptionService/v6.1 Element"`
	Type     string   `xml:"Type,attr"`
	CharData string   `xml:"chardata"`
}

type DecryptDocument struct {
	XMLName          xml.Name                   `xml:"http://ws.gematik.de/conn/EncryptionService/v6.1 DecryptDocument"`
	Context          connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	PrivateKeyOnCard PrivateKeyOnCard           `xml:"PrivateKeyOnCard"`
	Document         connectorcommon50.Document `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Document"`
	OptionalInputs   string                     `xml:"OptionalInputs,omitempty"`
}

type DecryptDocumentResponse struct {
	XMLName         xml.Name                    `xml:"http://ws.gematik.de/conn/EncryptionService/v6.1 DecryptDocumentResponse"`
	Status          connectorcommon50.Status    `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	Document        *connectorcommon50.Document `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Document,omitempty"`
	OptionalOutputs string                      `xml:"OptionalOutputs,omitempty"`
}

type UnprotectedProperties struct {
	XMLName  xml.Name             `xml:"http://ws.gematik.de/conn/EncryptionService/v6.1 UnprotectedProperties"`
	Property []dss10core.Property `xml:"urn:oasis:names:tc:dss:1.0:core:schema Property"`
}

type CommonStepsEnum string

// Enum values for CommonStepsEnum
const (
	CommonStepsEnumEncryptXMLData CommonStepsEnum = "EncryptXMLData"
	CommonStepsEnumDecryptXMLData CommonStepsEnum = "DecryptXMLData"
)

func (v CommonStepsEnum) IsValid() bool {
	switch v {
	case CommonStepsEnumEncryptXMLData:
		return true
	case CommonStepsEnumDecryptXMLData:
		return true
	default:
		return false
	}
}

type EncryptionStepResultEnum string

// Enum values for EncryptionStepResultEnum
const (
	EncryptionStepResultEnumError EncryptionStepResultEnum = "ERROR"
	EncryptionStepResultEnumOk    EncryptionStepResultEnum = "OK"
)

func (v EncryptionStepResultEnum) IsValid() bool {
	switch v {
	case EncryptionStepResultEnumError:
		return true
	case EncryptionStepResultEnumOk:
		return true
	default:
		return false
	}
}

type KeyOnCardType struct {
	CardHandle   string `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	KeyReference string `xml:"http://ws.gematik.de/conn/EncryptionService/v6.1 KeyReference,omitempty"`
}

// Interface for types that extend KeyOnCardType
type IKeyOnCardType interface {
	IsEncryptionService61KeyOnCardType()
}

// The type itself implements IKeyOnCardType
func (KeyOnCardType) IsEncryptionService61KeyOnCardType() {}

type EncryptDocumentRecipientKeys struct {
	XMLName           xml.Name           `xml:"http://ws.gematik.de/conn/EncryptionService/v6.1 RecipientKeys"`
	CertificateOnCard *CertificateOnCard `xml:"CertificateOnCard,omitempty"`
	Certificate       []string           `xml:"Certificate"`
}

type EncryptDocumentOptionalInputs struct {
	XMLName               xml.Name               `xml:"http://ws.gematik.de/conn/EncryptionService/v6.1 OptionalInputs"`
	EncryptionType        EncryptionType         `xml:"EncryptionType,omitempty"`
	Element               []Element              `xml:"Element"`
	UnprotectedProperties *UnprotectedProperties `xml:"UnprotectedProperties,omitempty"`
}
