// Code generated by wsdl2openapi; DO NOT EDIT.

package error20

import "encoding/xml"

type Error struct {
	XMLName   xml.Name     `xml:"http://ws.gematik.de/tel/error/v2.0 Error"`
	MessageID string       `xml:"MessageID"`
	Timestamp string       `xml:"Timestamp"`
	Trace     []ErrorTrace `xml:"Trace"`
}

type ErrorTrace struct {
	XMLName      xml.Name          `xml:"http://ws.gematik.de/tel/error/v2.0 Trace"`
	EventID      string            `xml:"EventID"`
	Instance     string            `xml:"Instance"`
	LogReference string            `xml:"LogReference"`
	CompType     string            `xml:"CompType"`
	Code         int               `xml:"Code"`
	Severity     string            `xml:"Severity"`
	ErrorType    string            `xml:"ErrorType"`
	ErrorText    string            `xml:"ErrorText"`
	Detail       *ErrorTraceDetail `xml:"Detail,omitempty"`
}

type ErrorTraceDetail struct {
	XMLName  xml.Name `xml:"http://ws.gematik.de/tel/error/v2.0 Detail"`
	Encoding string   `xml:"Encoding,attr,omitempty"`
	CharData string   `xml:"chardata"`
}
