Output images/cli.gif
Set Shell zsh
Type "ti"
Enter
Sleep 2
Type "ti kon get info"
Enter
Sleep 2
Type "ti kon get info -k tig"
Enter
Sleep 2
Type "ti kon get services"
Enter
Sleep 2
Type "ti kon get services --raw"
Enter
Sleep 2
Type "ti kon get cards"
Enter
Sleep 2
Type "ti kon get cards -k tig"
Enter
Sleep 2
Type "ti kon get certificates dbfc5453-28dd-4959-a465-1ad0cff8f329"
Enter
Sleep 2
Type "ti kon describe card dbfc5453-28dd-4959-a465-1ad0cff8f329"
Enter
Sleep 5
