// Code generated by wsdl2openapi; DO NOT EDIT.

package cardterminalinfo80

import (
	"encoding/xml"
	connectorcommon50 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/connectorcommon50"
	productinformation11 "github.com/gematik/zero-lab/go/kon/api/gematik/int/version/productinformation11"
)

type CardTerminal struct {
	XMLName            xml.Name                                `xml:"http://ws.gematik.de/conn/CardTerminalInfo/v8.0 CardTerminal"`
	ProductInformation productinformation11.ProductInformation `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductInformation"`
	CtId               string                                  `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CtId"`
	WorkplaceIds       connectorcommon50.WorkplaceIds          `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 WorkplaceIds"`
	Name               string                                  `xml:"Name"`
	MacAddress         string                                  `xml:"MacAddress"`
	IPAddress          *CardTerminalInfoTypeIPAddress          `xml:"IPAddress,omitempty"`
	Slots              int                                     `xml:"Slots"`
	IsPhysical         bool                                    `xml:"IS_PHYSICAL"`
	Connected          bool                                    `xml:"Connected"`
}

type CardTerminals struct {
	XMLName      xml.Name       `xml:"http://ws.gematik.de/conn/CardTerminalInfo/v8.0 CardTerminals"`
	CardTerminal []CardTerminal `xml:"CardTerminal"`
}

type CardTerminalInfoType struct {
	ProductInformation productinformation11.ProductInformation `xml:"http://ws.gematik.de/int/version/ProductInformation/v1.1 ProductInformation"`
	CtId               string                                  `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CtId"`
	WorkplaceIds       connectorcommon50.WorkplaceIds          `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 WorkplaceIds"`
	Name               string                                  `xml:"http://ws.gematik.de/conn/CardTerminalInfo/v8.0 Name"`
	MacAddress         string                                  `xml:"http://ws.gematik.de/conn/CardTerminalInfo/v8.0 MacAddress"`
	IPAddress          *CardTerminalInfoTypeIPAddress          `xml:"http://ws.gematik.de/conn/CardTerminalInfo/v8.0 IPAddress,omitempty"`
	Slots              int                                     `xml:"http://ws.gematik.de/conn/CardTerminalInfo/v8.0 Slots"`
	IsPhysical         bool                                    `xml:"http://ws.gematik.de/conn/CardTerminalInfo/v8.0 IS_PHYSICAL"`
	Connected          bool                                    `xml:"http://ws.gematik.de/conn/CardTerminalInfo/v8.0 Connected"`
}

// Interface for types that extend CardTerminalInfoType
type ICardTerminalInfoType interface {
	IsCardTerminalInfo80CardTerminalInfoType()
}

// The type itself implements ICardTerminalInfoType
func (CardTerminalInfoType) IsCardTerminalInfo80CardTerminalInfoType() {}

type CardTerminalInfoTypeIPAddress struct {
	XMLName     xml.Name `xml:"http://ws.gematik.de/conn/CardTerminalInfo/v8.0 IPAddress"`
	IPV4Address string   `xml:"IPV4Address,omitempty"`
	IPV6Address string   `xml:"IPV6Address,omitempty"`
}
