url: https://zerobin.zt.dev.ccs.gematik.solutions
fed_master_jwks:
  keys:
    - kty: EC
      crv: P-256
      x: cdIR8dLbqaGrzfgyu365KM5s00zjFq8DFaUFqBvrWLs
      y: XVp1ySJ2kjEInpjTZy0wD59afEXELpck0fk7vrMWrbw
      kid: puk_fedmaster_sig
      use: sig
      alg: ES256
fed_master_url: https://app-ref.federationmaster.de
sign_kid: reg_sig_puk
sign_private_key_path: ../../../../secrets/reg/sig_prk.pem
enc_kid: reg_enc_puk
enc_private_key_path: ../../../../secrets/reg/enc_prk.pem
client_kid: reg_client_puk
client_private_key_path: ../../../../secrets/reg/client_prk.pem
client_cert_path: ../../../../secrets/reg/client_cert.pem
metadata:
  federation_entity:
    name: Zero Trust Lab
    contacts: 
      - https://github.com/gematik/zero-lab
    homepage_uri: https://github.com/gematik/zero-lab
  openid_relying_party:
    organization_name: gematik GmbH
    client_name: Zero Trust Lab
    logo_uri: https://raw.githubusercontent.com/gematik/api-vzd/main/images/gematik_logo.svg
    redirect_uris:
      - https://zerobin.zt.dev.ccs.gematik.solutions/reg/auth/gematik-fed/callback
    response_types:
      - code
    client_registration_types:
      - automatic
    grant_types:
      - authorization_code
    require_pushed_authorization_requests: true
    token_endpoint_auth_method: self_signed_tls_client_auth
    default_acr_values:
      - gematik-ehealth-loa-high
    id_token_signed_response_alg: ES256
    id_token_encrypted_response_alg: ECDH-ES
    id_token_encrypted_response_enc: A256GCM
    scope: openid urn:telematik:alter urn:telematik:display_name urn:telematik:email urn:telematik:geschlecht urn:telematik:geburtsdatum urn:telematik:given_name urn:telematik:family_name
    signed_jwks_uri: https://zerobin.zt.dev.ccs.gematik.solutions/oidf-relying-party-jwks
