// Code generated by wsdl2openapi; DO NOT EDIT.

package cardservicecommon20

import connectorcommon50 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/connectorcommon50"

type CardType string

// Enum values for CardType
const (
	CardTypeEgk     CardType = "EGK"
	CardTypeHBAQSig CardType = "HBA-qSig"
	CardTypeHba     CardType = "HBA"
	CardTypeSmcB    CardType = "SMC-B"
	CardTypeHsmB    CardType = "HSM-B"
	CardTypeSmcKt   CardType = "SMC-KT"
	CardTypeKvk     CardType = "KVK"
	CardTypeZod20   CardType = "ZOD_2.0"
	CardTypeUnknown CardType = "UNKNOWN"
	CardTypeHBAx    CardType = "HBAx"
	CardTypeSmB     CardType = "SM-B"
)

func (v CardType) IsValid() bool {
	switch v {
	case CardTypeEgk:
		return true
	case CardTypeHBAQSig:
		return true
	case CardTypeHba:
		return true
	case CardTypeSmcB:
		return true
	case CardTypeHsmB:
		return true
	case CardTypeSmcKt:
		return true
	case CardTypeKvk:
		return true
	case CardTypeZod20:
		return true
	case CardTypeUnknown:
		return true
	case CardTypeHBAx:
		return true
	case CardTypeSmB:
		return true
	default:
		return false
	}
}

type PinResult string

// Enum values for PinResult
const (
	PinResultError        PinResult = "ERROR"
	PinResultOk           PinResult = "OK"
	PinResultRejected     PinResult = "REJECTED"
	PinResultWasblocked   PinResult = "WASBLOCKED"
	PinResultNowblocked   PinResult = "NOWBLOCKED"
	PinResultTransportPin PinResult = "TRANSPORT_PIN"
)

func (v PinResult) IsValid() bool {
	switch v {
	case PinResultError:
		return true
	case PinResultOk:
		return true
	case PinResultRejected:
		return true
	case PinResultWasblocked:
		return true
	case PinResultNowblocked:
		return true
	case PinResultTransportPin:
		return true
	default:
		return false
	}
}

type CardTypeType string

// Enum values for CardTypeType
const (
	CardTypeTypeEgk     CardTypeType = "EGK"
	CardTypeTypeHBAQSig CardTypeType = "HBA-qSig"
	CardTypeTypeHba     CardTypeType = "HBA"
	CardTypeTypeSmcB    CardTypeType = "SMC-B"
	CardTypeTypeHsmB    CardTypeType = "HSM-B"
	CardTypeTypeSmcKt   CardTypeType = "SMC-KT"
	CardTypeTypeKvk     CardTypeType = "KVK"
	CardTypeTypeZod20   CardTypeType = "ZOD_2.0"
	CardTypeTypeUnknown CardTypeType = "UNKNOWN"
	CardTypeTypeHBAx    CardTypeType = "HBAx"
	CardTypeTypeSmB     CardTypeType = "SM-B"
)

func (v CardTypeType) IsValid() bool {
	switch v {
	case CardTypeTypeEgk:
		return true
	case CardTypeTypeHBAQSig:
		return true
	case CardTypeTypeHba:
		return true
	case CardTypeTypeSmcB:
		return true
	case CardTypeTypeHsmB:
		return true
	case CardTypeTypeSmcKt:
		return true
	case CardTypeTypeKvk:
		return true
	case CardTypeTypeZod20:
		return true
	case CardTypeTypeUnknown:
		return true
	case CardTypeTypeHBAx:
		return true
	case CardTypeTypeSmB:
		return true
	default:
		return false
	}
}

type PinResponseType struct {
	Status    connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	PinResult PinResult                `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinResult"`
	LeftTries int                      `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 LeftTries,omitempty"`
}

// Interface for types that extend PinResponseType
type IPinResponseType interface {
	IsCardServiceCommon20PinResponseType()
}

// The type itself implements IPinResponseType
func (PinResponseType) IsCardServiceCommon20PinResponseType() {}

type PinResultEnum string

// Enum values for PinResultEnum
const (
	PinResultEnumError        PinResultEnum = "ERROR"
	PinResultEnumOk           PinResultEnum = "OK"
	PinResultEnumRejected     PinResultEnum = "REJECTED"
	PinResultEnumWasblocked   PinResultEnum = "WASBLOCKED"
	PinResultEnumNowblocked   PinResultEnum = "NOWBLOCKED"
	PinResultEnumTransportPin PinResultEnum = "TRANSPORT_PIN"
)

func (v PinResultEnum) IsValid() bool {
	switch v {
	case PinResultEnumError:
		return true
	case PinResultEnumOk:
		return true
	case PinResultEnumRejected:
		return true
	case PinResultEnumWasblocked:
		return true
	case PinResultEnumNowblocked:
		return true
	case PinResultEnumTransportPin:
		return true
	default:
		return false
	}
}
