// Package bp256 implements constant-time arithmetic for the brainpoolP256r1
// elliptic curve (RFC 5639 §3.4), used by the parent brainpool package for the
// secret-scalar operations that must resist timing side channels: ECDSA signing
// and ECDH.
//
// The design mirrors the Go standard library's crypto/internal/fips140/nistec:
// the field layer (package fiat) is machine-checked code generated by Fiat
// Cryptography, point arithmetic uses the exception-free complete addition
// formulas of Renes–Costello–Batina (2016) over homogeneous projective
// coordinates, and scalar multiplication uses a constant-time Montgomery ladder.
//
// brainpoolP256r1 is a prime-order curve (cofactor 1) with a general
// coefficient a (a ≠ −3), so the general complete formula (RCB 2016, Algorithm
// 1) is used rather than the a = −3 specialization that nistec uses for the NIST
// curves.
//
// This package is internal: callers go through the parent brainpool package.
package bp256
