// Code generated by wsdl2openapi; DO NOT EDIT.

pub type PostalAddresses = PostalAddressListType;

pub type PostalAddress = PostalAddressType;

pub type ElectronicAddress = ElectronicAddressType;

pub type Extension = ExtensionType;

pub type TrustServiceProviderList = TrustServiceProviderListType;

pub type SchemeInformation = TslSchemeInformationType;

pub type SchemeOperatorName = InternationalNamesType;

pub type SchemeName = InternationalNamesType;

pub type SchemeInformationUri = NonEmptyMultiLangUriListType;

pub type SchemeTypeCommunityRules = NonEmptyUriListType;

pub type PolicyOrLegalNotice = PolicyOrLegalnoticeType;

pub type NextUpdate = NextUpdateType;

pub type PointersToOtherTsl = OtherTslPointersType;

pub type OtherTslPointer = OtherTslPointerType;

pub type ServiceDigitalIdentities = ServiceDigitalIdentityListType;

pub type AdditionalInformation = AdditionalInformationType;

pub type DistributionPoints = ElectronicAddressType;

pub type TrustServiceProvider = TspType;

pub type TspInformation = TspInformationType;

pub type TspServices = TspServicesListType;

pub type TspService = TspServiceType;

pub type ServiceInformation = TspServiceInformationType;

pub type ServiceSupplyPoints = ServiceSupplyPointsType;

pub type ServiceDigitalIdentity = DigitalIdentityListType;

pub type ServiceHistory = ServiceHistoryType;

pub type ServiceHistoryInstance = ServiceHistoryInstanceType;

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct InternationalNamesType {
    #[serde(rename = "Name", default, skip_serializing_if = "Vec::is_empty")]
    pub name: Vec<MultiLangNormStringType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct MultiLangNormStringType {
    #[serde(rename = "@xml:lang", default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(rename = "$text", default)]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct MultiLangStringType {
    #[serde(rename = "@xml:lang", default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(rename = "$text", default)]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct AddressType {
    #[serde(rename = "PostalAddresses")]
    pub postal_addresses: PostalAddresses,
    #[serde(rename = "ElectronicAddress")]
    pub electronic_address: ElectronicAddress,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct PostalAddressListType {
    #[serde(
        rename = "PostalAddress",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub postal_address: Vec<PostalAddress>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct PostalAddressType {
    #[serde(rename = "@xml:lang", default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(rename = "StreetAddress")]
    pub street_address: String,
    #[serde(rename = "Locality")]
    pub locality: String,
    #[serde(
        rename = "StateOrProvince",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub state_or_province: Option<String>,
    #[serde(
        rename = "PostalCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub postal_code: Option<String>,
    #[serde(rename = "CountryName")]
    pub country_name: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ElectronicAddressType {
    #[serde(rename = "URI", default, skip_serializing_if = "Vec::is_empty")]
    pub uri: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct AnyType {
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ExtensionType {
    #[serde(rename = "@Critical")]
    pub critical: bool,
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ExtensionsListType {
    #[serde(rename = "Extension", default, skip_serializing_if = "Vec::is_empty")]
    pub extension: Vec<Extension>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct NonEmptyMultiLangUriType {
    #[serde(rename = "@xml:lang", default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(rename = "$text", default)]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct NonEmptyMultiLangUriListType {
    #[serde(rename = "URI", default, skip_serializing_if = "Vec::is_empty")]
    pub uri: Vec<NonEmptyMultiLangUriType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct NonEmptyUriListType {
    #[serde(rename = "URI", default, skip_serializing_if = "Vec::is_empty")]
    pub uri: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TslTagType {
    HttpUriEtsiOrg02231TslTag,
}

impl TslTagType {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::HttpUriEtsiOrg02231TslTag => "http://uri.etsi.org/02231/TSLTag",
        }
    }
}

impl ::std::fmt::Display for TslTagType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl ::std::str::FromStr for TslTagType {
    type Err = crate::api::soap::UnknownEnumValue;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "http://uri.etsi.org/02231/TSLTag" => Ok(Self::HttpUriEtsiOrg02231TslTag),
            _ => Err(crate::api::soap::UnknownEnumValue {
                type_name: "TslTagType",
                value: value.to_owned(),
            }),
        }
    }
}

impl<'de> ::serde::Deserialize<'de> for TslTagType {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <String as ::serde::Deserialize>::deserialize(deserializer)?;
        value.parse().map_err(::serde::de::Error::custom)
    }
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct TrustServiceProviderListType {
    #[serde(
        rename = "TrustServiceProvider",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub trust_service_provider: Vec<TrustServiceProvider>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct TslSchemeInformationType {
    #[serde(rename = "TSLVersionIdentifier")]
    pub tsl_version_identifier: i64,
    #[serde(rename = "TSLSequenceNumber")]
    pub tsl_sequence_number: i64,
    #[serde(rename = "TSLType")]
    pub tsl_type: String,
    #[serde(rename = "SchemeOperatorName")]
    pub scheme_operator_name: SchemeOperatorName,
    #[serde(rename = "SchemeOperatorAddress")]
    pub scheme_operator_address: AddressType,
    #[serde(rename = "SchemeName")]
    pub scheme_name: SchemeName,
    #[serde(rename = "SchemeInformationURI")]
    pub scheme_information_uri: SchemeInformationUri,
    #[serde(rename = "StatusDeterminationApproach")]
    pub status_determination_approach: String,
    #[serde(
        rename = "SchemeTypeCommunityRules",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub scheme_type_community_rules: Option<SchemeTypeCommunityRules>,
    #[serde(
        rename = "SchemeTerritory",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub scheme_territory: Option<String>,
    #[serde(
        rename = "PolicyOrLegalNotice",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub policy_or_legal_notice: Option<PolicyOrLegalNotice>,
    #[serde(rename = "HistoricalInformationPeriod")]
    pub historical_information_period: i64,
    #[serde(
        rename = "PointersToOtherTSL",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pointers_to_other_tsl: Option<PointersToOtherTsl>,
    #[serde(rename = "ListIssueDateTime")]
    pub list_issue_date_time: String,
    #[serde(rename = "NextUpdate")]
    pub next_update: NextUpdate,
    #[serde(
        rename = "DistributionPoints",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub distribution_points: Option<DistributionPoints>,
    #[serde(
        rename = "SchemeExtensions",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub scheme_extensions: Option<ExtensionsListType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct PolicyOrLegalnoticeType {
    #[serde(rename = "TSLPolicy", default, skip_serializing_if = "Vec::is_empty")]
    pub tsl_policy: Vec<NonEmptyMultiLangUriType>,
    #[serde(
        rename = "TSLLegalNotice",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub tsl_legal_notice: Vec<MultiLangStringType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct NextUpdateType {
    #[serde(rename = "dateTime", default, skip_serializing_if = "Option::is_none")]
    pub date_time: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct OtherTslPointersType {
    #[serde(
        rename = "OtherTSLPointer",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub other_tsl_pointer: Vec<OtherTslPointer>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct OtherTslPointerType {
    #[serde(
        rename = "ServiceDigitalIdentities",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub service_digital_identities: Option<ServiceDigitalIdentities>,
    #[serde(rename = "TSLLocation")]
    pub tsl_location: String,
    #[serde(
        rename = "AdditionalInformation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_information: Option<AdditionalInformation>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ServiceDigitalIdentityListType {
    #[serde(
        rename = "ServiceDigitalIdentity",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub service_digital_identity: Vec<ServiceDigitalIdentity>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct AdditionalInformationType {
    #[serde(
        rename = "TextualInformation",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub textual_information: Vec<MultiLangStringType>,
    #[serde(
        rename = "OtherInformation",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub other_information: Vec<AnyType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct TspType {
    #[serde(rename = "TSPInformation")]
    pub tsp_information: TspInformation,
    #[serde(rename = "TSPServices")]
    pub tsp_services: TspServices,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct TspInformationType {
    #[serde(rename = "TSPName")]
    pub tsp_name: InternationalNamesType,
    #[serde(
        rename = "TSPTradeName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub tsp_trade_name: Option<InternationalNamesType>,
    #[serde(rename = "TSPAddress")]
    pub tsp_address: AddressType,
    #[serde(rename = "TSPInformationURI")]
    pub tsp_information_uri: NonEmptyMultiLangUriListType,
    #[serde(
        rename = "TSPInformationExtensions",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub tsp_information_extensions: Option<ExtensionsListType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct TspServicesListType {
    #[serde(rename = "TSPService", default, skip_serializing_if = "Vec::is_empty")]
    pub tsp_service: Vec<TspService>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct TspServiceType {
    #[serde(rename = "ServiceInformation")]
    pub service_information: ServiceInformation,
    #[serde(
        rename = "ServiceHistory",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub service_history: Option<ServiceHistory>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct TspServiceInformationType {
    #[serde(rename = "ServiceTypeIdentifier")]
    pub service_type_identifier: String,
    #[serde(rename = "ServiceName")]
    pub service_name: InternationalNamesType,
    #[serde(rename = "ServiceDigitalIdentity")]
    pub service_digital_identity: ServiceDigitalIdentity,
    #[serde(rename = "ServiceStatus")]
    pub service_status: String,
    #[serde(rename = "StatusStartingTime")]
    pub status_starting_time: String,
    #[serde(
        rename = "SchemeServiceDefinitionURI",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub scheme_service_definition_uri: Option<NonEmptyMultiLangUriListType>,
    #[serde(
        rename = "ServiceSupplyPoints",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub service_supply_points: Option<ServiceSupplyPoints>,
    #[serde(
        rename = "TSPServiceDefinitionURI",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub tsp_service_definition_uri: Option<NonEmptyMultiLangUriListType>,
    #[serde(
        rename = "ServiceInformationExtensions",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub service_information_extensions: Option<ExtensionsListType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ServiceSupplyPointsType {
    #[serde(
        rename = "ServiceSupplyPoint",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub service_supply_point: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct DigitalIdentityListType {
    #[serde(rename = "DigitalId", default, skip_serializing_if = "Vec::is_empty")]
    pub digital_id: Vec<DigitalIdentityType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct DigitalIdentityType {
    #[serde(
        rename = "X509Certificate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x509_certificate: Option<crate::api::soap::Base64Binary>,
    #[serde(
        rename = "X509SubjectName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x509_subject_name: Option<String>,
    #[serde(rename = "KeyValue", default, skip_serializing_if = "Option::is_none")]
    pub key_value: Option<crate::api::w3200009::xmldsig::KeyValue>,
    #[serde(rename = "X509SKI", default, skip_serializing_if = "Option::is_none")]
    pub x509_ski: Option<crate::api::soap::Base64Binary>,
    #[serde(rename = "Other", default, skip_serializing_if = "Option::is_none")]
    pub other: Option<AnyType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ServiceHistoryType {
    #[serde(
        rename = "ServiceHistoryInstance",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub service_history_instance: Vec<ServiceHistoryInstance>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ServiceHistoryInstanceType {
    #[serde(rename = "ServiceTypeIdentifier")]
    pub service_type_identifier: String,
    #[serde(rename = "ServiceName")]
    pub service_name: InternationalNamesType,
    #[serde(rename = "ServiceDigitalIdentity")]
    pub service_digital_identity: ServiceDigitalIdentity,
    #[serde(rename = "ServiceStatus")]
    pub service_status: String,
    #[serde(rename = "StatusStartingTime")]
    pub status_starting_time: String,
    #[serde(
        rename = "ServiceInformationExtensions",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub service_information_extensions: Option<ExtensionsListType>,
}
