// Code generated by wsdl2openapi; DO NOT EDIT.

pub type SigningCertificate = CertIdListType;

pub type SignaturePolicyIdentifier = SignaturePolicyIdentifierType;

pub type DataObjectFormat = DataObjectFormatType;

pub type CommitmentTypeIndication = CommitmentTypeIndicationType;

pub type SignatureProductionPlace = SignatureProductionPlaceType;

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct AnyType {
    #[serde(
        rename = "@anyAttribute",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_attributes: Option<crate::api::soap::AnyXml>,
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ObjectIdentifierType {
    #[serde(rename = "Identifier")]
    pub identifier: IdentifierType,
    #[serde(
        rename = "Description",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<String>,
    #[serde(
        rename = "DocumentationReferences",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub documentation_references: Option<DocumentationReferencesType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct IdentifierType {
    #[serde(
        rename = "@Qualifier",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub qualifier: Option<QualifierType>,
    #[serde(rename = "$text", default)]
    pub char_data: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum QualifierType {
    OidAsUri,
    OidAsUrn,
}

impl QualifierType {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::OidAsUri => "OIDAsURI",
            Self::OidAsUrn => "OIDAsURN",
        }
    }
}

impl ::std::fmt::Display for QualifierType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl ::std::str::FromStr for QualifierType {
    type Err = crate::api::soap::UnknownEnumValue;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "OIDAsURI" => Ok(Self::OidAsUri),
            "OIDAsURN" => Ok(Self::OidAsUrn),
            _ => Err(crate::api::soap::UnknownEnumValue {
                type_name: "QualifierType",
                value: value.to_owned(),
            }),
        }
    }
}

impl<'de> ::serde::Deserialize<'de> for QualifierType {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <String as ::serde::Deserialize>::deserialize(deserializer)?;
        value.parse().map_err(::serde::de::Error::custom)
    }
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct DocumentationReferencesType {
    #[serde(
        rename = "DocumentationReference",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub documentation_reference: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct CertIdListType {
    #[serde(rename = "Cert", default, skip_serializing_if = "Vec::is_empty")]
    pub cert: Vec<CertIdType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct CertIdType {
    #[serde(rename = "@URI", default, skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    #[serde(rename = "CertDigest")]
    pub cert_digest: DigestAlgAndValueType,
    #[serde(rename = "IssuerSerial")]
    pub issuer_serial: crate::api::w3200009::xmldsig::X509IssuerSerialType,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct DigestAlgAndValueType {
    #[serde(rename(serialize = "ns-xmldsig:DigestMethod", deserialize = "DigestMethod"))]
    pub digest_method: crate::api::w3200009::xmldsig::DigestMethod,
    #[serde(rename(serialize = "ns-xmldsig:DigestValue", deserialize = "DigestValue"))]
    pub digest_value: crate::api::soap::Base64Binary,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct SignaturePolicyIdentifierType {
    #[serde(
        rename = "SignaturePolicyId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signature_policy_id: Option<SignaturePolicyIdType>,
    #[serde(
        rename = "SignaturePolicyImplied",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signature_policy_implied: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct SignaturePolicyIdType {
    #[serde(rename = "SigPolicyId")]
    pub sig_policy_id: ObjectIdentifierType,
    #[serde(
        rename = "Transforms",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub transforms: Option<crate::api::w3200009::xmldsig::Transforms>,
    #[serde(rename = "SigPolicyHash")]
    pub sig_policy_hash: DigestAlgAndValueType,
    #[serde(
        rename = "SigPolicyQualifiers",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub sig_policy_qualifiers: Option<SigPolicyQualifiersListType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct SigPolicyQualifiersListType {
    #[serde(
        rename = "SigPolicyQualifier",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub sig_policy_qualifier: Vec<AnyType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct DataObjectFormatType {
    #[serde(rename = "@ObjectReference")]
    pub object_reference: String,
    #[serde(
        rename = "Description",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<String>,
    #[serde(
        rename = "ObjectIdentifier",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub object_identifier: Option<ObjectIdentifierType>,
    #[serde(rename = "MimeType", default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[serde(rename = "Encoding", default, skip_serializing_if = "Option::is_none")]
    pub encoding: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct CommitmentTypeIndicationType {
    #[serde(rename = "CommitmentTypeId")]
    pub commitment_type_id: ObjectIdentifierType,
    #[serde(
        rename = "ObjectReference",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub object_reference: Vec<String>,
    #[serde(
        rename = "AllSignedDataObjects",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub all_signed_data_objects: Option<crate::api::soap::AnyXml>,
    #[serde(
        rename = "CommitmentTypeQualifiers",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub commitment_type_qualifiers: Option<CommitmentTypeQualifiersListType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct CommitmentTypeQualifiersListType {
    #[serde(
        rename = "CommitmentTypeQualifier",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub commitment_type_qualifier: Vec<AnyType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct SignatureProductionPlaceType {
    #[serde(rename = "City", default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(
        rename = "StateOrProvince",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub state_or_province: Option<String>,
    #[serde(
        rename = "PostalCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub postal_code: Option<String>,
    #[serde(
        rename = "CountryName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub country_name: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ClaimedRolesListType {
    #[serde(rename = "ClaimedRole", default, skip_serializing_if = "Vec::is_empty")]
    pub claimed_role: Vec<AnyType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct CrlIdentifierType {
    #[serde(rename = "@URI", default, skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    #[serde(rename = "Issuer")]
    pub issuer: String,
    #[serde(rename = "IssueTime")]
    pub issue_time: String,
    #[serde(rename = "Number", default, skip_serializing_if = "Option::is_none")]
    pub number: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ResponderIdType {
    #[serde(rename = "ByName", default, skip_serializing_if = "Option::is_none")]
    pub by_name: Option<String>,
    #[serde(rename = "ByKey", default, skip_serializing_if = "Option::is_none")]
    pub by_key: Option<crate::api::soap::Base64Binary>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct OcspIdentifierType {
    #[serde(rename = "@URI", default, skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    #[serde(rename = "ResponderID")]
    pub responder_id: ResponderIdType,
    #[serde(rename = "ProducedAt")]
    pub produced_at: String,
}
