// Code generated by wsdl2openapi; DO NOT EDIT.

package signaturepolicy

import (
	"encoding/xml"
	etsi01903132 "github.com/gematik/zero-lab/go/kon/api/etsi01903132"
	dss10core "github.com/gematik/zero-lab/go/kon/api/oasis/dss10core"
	verificationreport "github.com/gematik/zero-lab/go/kon/api/oasis/dssx10profiles/verificationreport"
	xmldsig "github.com/gematik/zero-lab/go/kon/api/w3200009/xmldsig"
)

type GenerateUnderSignaturePolicy struct {
	XMLName                   xml.Name                            `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# GenerateUnderSignaturePolicy"`
	SignaturePolicyIdentifier string                              `xml:"SignaturePolicyIdentifier"`
	SignaturePolicyLocation   string                              `xml:"SignaturePolicyLocation,omitempty"`
	DigestAndAlgorithm        *etsi01903132.DigestAlgAndValueType `xml:"DigestAndAlgorithm,omitempty"`
}

type UsedSignaturePolicy struct {
	XMLName                   xml.Name                            `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# UsedSignaturePolicy"`
	SignaturePolicyIdentifier string                              `xml:"SignaturePolicyIdentifier"`
	SignaturePolicyLocation   string                              `xml:"SignaturePolicyLocation,omitempty"`
	DigestAndAlgorithm        *etsi01903132.DigestAlgAndValueType `xml:"DigestAndAlgorithm,omitempty"`
}

type SupportedSignaturePolicies struct {
	XMLName                  xml.Name                     `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# SupportedSignaturePolicies"`
	SupportedSignaturePolicy []SignaturePolicyDetailsType `xml:"SupportedSignaturePolicy"`
}

type VerifyUnderSignaturePolicy struct {
	XMLName          xml.Name                    `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# VerifyUnderSignaturePolicy"`
	DefaultPolicy    *SignaturePolicyDetailsType `xml:"DefaultPolicy,omitempty"`
	ExplicitPolicies *ExplicitPolicies           `xml:"ExplicitPolicies,omitempty"`
}

type ExplicitPolicies struct {
	XMLName             xml.Name              `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# ExplicitPolicies"`
	PolicySignaturePair []PolicySignaturePair `xml:"PolicySignaturePair"`
}

type PolicySignaturePair struct {
	XMLName             xml.Name            `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# PolicySignaturePair"`
	SignatureIdentifier SignatureIdentifier `xml:"SignatureIdentifier"`
	SignaturePolicy     SignaturePolicy     `xml:"SignaturePolicy"`
}

type SignaturePolicy struct {
	XMLName                   xml.Name                            `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# SignaturePolicy"`
	SignaturePolicyIdentifier string                              `xml:"SignaturePolicyIdentifier"`
	SignaturePolicyLocation   string                              `xml:"SignaturePolicyLocation,omitempty"`
	DigestAndAlgorithm        *etsi01903132.DigestAlgAndValueType `xml:"DigestAndAlgorithm,omitempty"`
}

type SignatureIdentifier struct {
	XMLName                xml.Name                                 `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# SignatureIdentifier"`
	WhichDocument          string                                   `xml:"WhichDocument,attr,omitempty"`
	XPath                  string                                   `xml:"XPath,attr,omitempty"`
	Offset                 int                                      `xml:"Offset,attr,omitempty"`
	FieldName              string                                   `xml:"FieldName,attr,omitempty"`
	DigestAlgAndValue      *etsi01903132.DigestAlgAndValueType      `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# DigestAlgAndValue,omitempty"`
	CanonicalizationMethod *xmldsig.CanonicalizationMethod          `xml:"http://www.w3.org/2000/09/xmldsig# CanonicalizationMethod,omitempty"`
	SignedProperties       *verificationreport.SignedPropertiesType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignedProperties,omitempty"`
	SignatureValue         *xmldsig.SignatureValue                  `xml:"http://www.w3.org/2000/09/xmldsig# SignatureValue,omitempty"`
	Other                  *dss10core.AnyType                       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Other,omitempty"`
}

type VerifiedUnderSignaturePolicy struct {
	XMLName             xml.Name             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# VerifiedUnderSignaturePolicy"`
	SignaturePolicy     SignaturePolicy      `xml:"SignaturePolicy"`
	SignatureIdentifier *SignatureIdentifier `xml:"SignatureIdentifier,omitempty"`
}

type SignaturePolicyDetailsType struct {
	SignaturePolicyIdentifier string                              `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# SignaturePolicyIdentifier"`
	SignaturePolicyLocation   string                              `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# SignaturePolicyLocation,omitempty"`
	DigestAndAlgorithm        *etsi01903132.DigestAlgAndValueType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# DigestAndAlgorithm,omitempty"`
}

// Interface for types that extend SignaturePolicyDetailsType
type ISignaturePolicyDetailsType interface {
	IsSignaturePolicySignaturePolicyDetailsType()
}

// The type itself implements ISignaturePolicyDetailsType
func (SignaturePolicyDetailsType) IsSignaturePolicySignaturePolicyDetailsType() {}

type VerifyUnderSignaturePolicyType struct {
	DefaultPolicy    *SignaturePolicyDetailsType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# DefaultPolicy,omitempty"`
	ExplicitPolicies *ExplicitPolicies           `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# ExplicitPolicies,omitempty"`
}

// Interface for types that extend VerifyUnderSignaturePolicyType
type IVerifyUnderSignaturePolicyType interface {
	IsSignaturePolicyVerifyUnderSignaturePolicyType()
}

// The type itself implements IVerifyUnderSignaturePolicyType
func (VerifyUnderSignaturePolicyType) IsSignaturePolicyVerifyUnderSignaturePolicyType() {}

type PolicySignaturePairsType struct {
	PolicySignaturePair []PolicySignaturePair `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# PolicySignaturePair"`
}

// Interface for types that extend PolicySignaturePairsType
type IPolicySignaturePairsType interface {
	IsSignaturePolicyPolicySignaturePairsType()
}

// The type itself implements IPolicySignaturePairsType
func (PolicySignaturePairsType) IsSignaturePolicyPolicySignaturePairsType() {}

type PolicySignaturePairType struct {
	SignatureIdentifier SignatureIdentifier `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# SignatureIdentifier"`
	SignaturePolicy     SignaturePolicy     `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# SignaturePolicy"`
}

// Interface for types that extend PolicySignaturePairType
type IPolicySignaturePairType interface {
	IsSignaturePolicyPolicySignaturePairType()
}

// The type itself implements IPolicySignaturePairType
func (PolicySignaturePairType) IsSignaturePolicyPolicySignaturePairType() {}

type VerifiedUnderSignaturePolicyType struct {
	SignaturePolicy     SignaturePolicy      `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# SignaturePolicy"`
	SignatureIdentifier *SignatureIdentifier `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# SignatureIdentifier,omitempty"`
}

// Interface for types that extend VerifiedUnderSignaturePolicyType
type IVerifiedUnderSignaturePolicyType interface {
	IsSignaturePolicyVerifiedUnderSignaturePolicyType()
}

// The type itself implements IVerifiedUnderSignaturePolicyType
func (VerifiedUnderSignaturePolicyType) IsSignaturePolicyVerifiedUnderSignaturePolicyType() {}
