#!/usr/bin/env bash
# A TEST-ONLY SMC-B-like identity for the `ti identity` tests: a brainpoolP256r1 CA and
# three end entities with the key usages a gematik SMC-B carries (AUT: digitalSignature,
# OSIG: digitalSignature + contentCommitment, ENC: keyEncipherment), each with its key,
# as PEM and as a single-pair PKCS#12 (password 00, like gematik's test cards). The
# tests merge the PKCS#12 files into one when they need several pairs in a file.
#
# Also data.bin and its ECDSA-SHA256 signature by the AUT key, DER-encoded, for
# `ti pki verify-signature`.
#
# Needs an OpenSSL with brainpool (3.x/4.x). Keys are random: running this again
# changes every file; PROVENANCE.md is rewritten with the new digests.
set -euo pipefail
cd "$(dirname "$0")"

NOW=20260101000000Z
TEN_YEARS=20360101000000Z
FIVE_YEARS=20310101000000Z

cat > ext.cnf <<'CNF'
[ca]
basicConstraints = critical, CA:true
keyUsage = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always

[aut]
keyUsage = critical, digitalSignature
extendedKeyUsage = clientAuth
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
1.3.36.8.3.3 = ASN1:SEQUENCE:admission_syntax

[osig]
keyUsage = critical, digitalSignature, nonRepudiation
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
1.3.36.8.3.3 = ASN1:SEQUENCE:admission_syntax

[enc]
keyUsage = critical, keyEncipherment, keyAgreement
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
1.3.36.8.3.3 = ASN1:SEQUENCE:admission_syntax

[admission_syntax]
contents = SEQUENCE:contents_of_admissions
[contents_of_admissions]
admissions = SEQUENCE:admissions
[admissions]
profession_infos = SEQUENCE:profession_infos
[profession_infos]
info = SEQUENCE:profession_info
[profession_info]
items = SEQUENCE:profession_items
oids = SEQUENCE:profession_oids
registration_number = PRINTABLESTRING:1-2-ARZTPRAXIS-TESTONLY01
[profession_items]
item = UTF8String:Betriebsstaette Arzt
[profession_oids]
oid = OID:1.2.276.0.76.4.50
CNF

key() { # name
    openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:brainpoolP256r1 \
        -pkeyopt ec_param_enc:named_curve -out "$1.key" 2>/dev/null
}

serial=100
cert() { # name cn issuer(name|self) section
    local name=$1 cn=$2 issuer=$3 section=$4
    serial=$((serial + 1))
    openssl req -new -key "$name.key" -subj "/C=DE/O=gematik TEST-ONLY/CN=$cn" -out "$name.csr"
    local signer=(-key "$name.key")
    local to=$FIVE_YEARS
    if [ "$issuer" = self ]; then
        to=$TEN_YEARS
    else
        signer=(-CA "$issuer.pem" -CAkey "$issuer.key")
    fi
    openssl x509 -req -in "$name.csr" "${signer[@]}" -set_serial "$serial" \
        -not_before "$NOW" -not_after "$to" -extfile ext.cnf -extensions "$section" \
        -out "$name.pem" 2>/dev/null
    rm "$name.csr"
}

p12() { # name
    openssl pkcs12 -export -inkey "$1.key" -in "$1.pem" -certfile ca.pem \
        -name "$1" -passout pass:00 -out "$1.p12"
}

key ca;   cert ca "GEM.SMCB-CA TEST-ONLY" self ca
key aut;  cert aut "Arztpraxis TEST-ONLY" ca aut
key osig; cert osig "Arztpraxis TEST-ONLY" ca osig
key enc;  cert enc "Arztpraxis TEST-ONLY" ca enc
p12 aut; p12 osig; p12 enc
rm ca.key ext.cnf

# The AUT certificate and the CA in one PEM, as `--cert` takes a chain.
cat aut.pem ca.pem > aut-chain.pem

printf 'VAU signed_pub_keys TEST-ONLY\n' > data.bin
openssl dgst -sha256 -sign aut.key -out sig.der data.bin
openssl x509 -in aut.pem -pubkey -noout > aut-pub.pem
openssl dgst -sha256 -verify aut-pub.pem -signature sig.der data.bin >/dev/null
rm aut-pub.pem

{
    echo "# Provenance"
    echo
    echo "Generated by generate.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) with $(openssl version)."
    echo "TEST-ONLY material: random keys, a self-made CA, no relation to any TI PKI."
    echo
    echo "| File | SHA-256 |"
    echo "|---|---|"
    for f in ca.pem aut.pem aut.key aut-chain.pem aut.p12 osig.pem osig.key osig.p12 enc.pem enc.key enc.p12 data.bin sig.der; do
        printf '| `%s` | `%s` |\n' "$f" "$(openssl dgst -sha256 -r "$f" | cut -d' ' -f1)"
    done
} > PROVENANCE.md
