// Code generated by wsdl2openapi go generator. DO NOT EDIT.

package eventservice72

import (
	"encoding/xml"
	error20 "github.com/gematik/zero-lab/go/kon/api/gematik/tel/error20"
)

type soapOperation struct {
	name        string
	soapAction  string
	bindingType string
}

func (op *soapOperation) Name() string {
	return op.name
}

func (op *soapOperation) SOAPAction() string {
	return op.soapAction
}

func (op *soapOperation) BindingType() string {
	return op.bindingType
}

var OperationSubscribe = soapOperation{
	bindingType: "soap11",
	name:        "Subscribe",
	soapAction:  "http://ws.gematik.de/conn/EventService/v7.2#Subscribe",
}

type SubscribeEnvelope struct {
	XMLName   xml.Name   `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	Subscribe *Subscribe `xml:"Body>Subscribe"`
}

func (e *SubscribeEnvelope) IsFault() bool {
	return false
}

type SubscribeResponseEnvelope struct {
	XMLName           xml.Name           `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	SubscribeResponse *SubscribeResponse `xml:"Body>SubscribeResponse"`
	Fault             *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *SubscribeResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationUnsubscribe = soapOperation{
	bindingType: "soap11",
	name:        "Unsubscribe",
	soapAction:  "http://ws.gematik.de/conn/EventService/v7.2#Unsubscribe",
}

type UnsubscribeEnvelope struct {
	XMLName     xml.Name     `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	Unsubscribe *Unsubscribe `xml:"Body>Unsubscribe"`
}

func (e *UnsubscribeEnvelope) IsFault() bool {
	return false
}

type UnsubscribeResponseEnvelope struct {
	XMLName             xml.Name             `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	UnsubscribeResponse *UnsubscribeResponse `xml:"Body>UnsubscribeResponse"`
	Fault               *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *UnsubscribeResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationGetSubscription = soapOperation{
	bindingType: "soap11",
	name:        "GetSubscription",
	soapAction:  "http://ws.gematik.de/conn/EventService/v7.2#GetSubscription",
}

type GetSubscriptionEnvelope struct {
	XMLName         xml.Name         `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetSubscription *GetSubscription `xml:"Body>GetSubscription"`
}

func (e *GetSubscriptionEnvelope) IsFault() bool {
	return false
}

type GetSubscriptionResponseEnvelope struct {
	XMLName                 xml.Name                 `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetSubscriptionResponse *GetSubscriptionResponse `xml:"Body>GetSubscriptionResponse"`
	Fault                   *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *GetSubscriptionResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationGetResourceInformation = soapOperation{
	bindingType: "soap11",
	name:        "GetResourceInformation",
	soapAction:  "http://ws.gematik.de/conn/EventService/v7.2#GetResourceInformation",
}

type GetResourceInformationEnvelope struct {
	XMLName                xml.Name                `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetResourceInformation *GetResourceInformation `xml:"Body>GetResourceInformation"`
}

func (e *GetResourceInformationEnvelope) IsFault() bool {
	return false
}

type GetResourceInformationResponseEnvelope struct {
	XMLName                        xml.Name                        `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetResourceInformationResponse *GetResourceInformationResponse `xml:"Body>GetResourceInformationResponse"`
	Fault                          *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *GetResourceInformationResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationGetCardTerminals = soapOperation{
	bindingType: "soap11",
	name:        "GetCardTerminals",
	soapAction:  "http://ws.gematik.de/conn/EventService/v7.2#GetCardTerminals",
}

type GetCardTerminalsEnvelope struct {
	XMLName          xml.Name          `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetCardTerminals *GetCardTerminals `xml:"Body>GetCardTerminals"`
}

func (e *GetCardTerminalsEnvelope) IsFault() bool {
	return false
}

type GetCardTerminalsResponseEnvelope struct {
	XMLName                  xml.Name                  `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetCardTerminalsResponse *GetCardTerminalsResponse `xml:"Body>GetCardTerminalsResponse"`
	Fault                    *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *GetCardTerminalsResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationGetCards = soapOperation{
	bindingType: "soap11",
	name:        "GetCards",
	soapAction:  "http://ws.gematik.de/conn/EventService/v7.2#GetCards",
}

type GetCardsEnvelope struct {
	XMLName  xml.Name  `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetCards *GetCards `xml:"Body>GetCards"`
}

func (e *GetCardsEnvelope) IsFault() bool {
	return false
}

type GetCardsResponseEnvelope struct {
	XMLName          xml.Name          `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetCardsResponse *GetCardsResponse `xml:"Body>GetCardsResponse"`
	Fault            *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *GetCardsResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationRenewSubscriptions = soapOperation{
	bindingType: "soap11",
	name:        "RenewSubscriptions",
	soapAction:  "http://ws.gematik.de/conn/EventService/v7.2#RenewSubscriptions",
}

type RenewSubscriptionsEnvelope struct {
	XMLName            xml.Name            `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	RenewSubscriptions *RenewSubscriptions `xml:"Body>RenewSubscriptions"`
}

func (e *RenewSubscriptionsEnvelope) IsFault() bool {
	return false
}

type RenewSubscriptionsResponseEnvelope struct {
	XMLName                    xml.Name                    `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	RenewSubscriptionsResponse *RenewSubscriptionsResponse `xml:"Body>RenewSubscriptionsResponse"`
	Fault                      *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *RenewSubscriptionsResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}
