// Code generated by wsdl2openapi; DO NOT EDIT.

package eventservice72

import (
	"encoding/xml"
	cardservice81 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/cardservice81"
	cardservicecommon20 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/cardservicecommon20"
	cardterminalinfo80 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/cardterminalinfo80"
	connectorcommon50 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/connectorcommon50"
	connectorcontext20 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/connectorcontext20"
)

type Event struct {
	XMLName        xml.Name          `xml:"http://ws.gematik.de/conn/EventService/v7.2 Event"`
	Topic          string            `xml:"Topic"`
	Type           EventType         `xml:"Type"`
	Severity       EventSeverityType `xml:"Severity"`
	SubscriptionID string            `xml:"SubscriptionID"`
	Message        EventMessage      `xml:"Message"`
}

type Subscribe struct {
	XMLName      xml.Name                   `xml:"http://ws.gematik.de/conn/EventService/v7.2 Subscribe"`
	Context      connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	Subscription Subscription               `xml:"Subscription"`
}

type SubscribeResponse struct {
	XMLName         xml.Name                 `xml:"http://ws.gematik.de/conn/EventService/v7.2 SubscribeResponse"`
	Status          connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	SubscriptionID  string                   `xml:"SubscriptionID"`
	TerminationTime string                   `xml:"TerminationTime"`
}

type SubscriptionRenewal struct {
	XMLName         xml.Name `xml:"http://ws.gematik.de/conn/EventService/v7.2 SubscriptionRenewal"`
	SubscriptionID  string   `xml:"SubscriptionID"`
	TerminationTime string   `xml:"TerminationTime"`
}

type Unsubscribe struct {
	XMLName        xml.Name                   `xml:"http://ws.gematik.de/conn/EventService/v7.2 Unsubscribe"`
	Context        connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	SubscriptionID string                     `xml:"SubscriptionID,omitempty"`
	EventTo        string                     `xml:"EventTo,omitempty"`
}

type UnsubscribeResponse struct {
	XMLName xml.Name                 `xml:"http://ws.gematik.de/conn/EventService/v7.2 UnsubscribeResponse"`
	Status  connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
}

type GetSubscription struct {
	XMLName        xml.Name                   `xml:"http://ws.gematik.de/conn/EventService/v7.2 GetSubscription"`
	MandantWide    bool                       `xml:"mandant-wide,attr,omitempty"`
	Context        connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	SubscriptionID string                     `xml:"SubscriptionID,omitempty"`
}

type GetSubscriptionResponse struct {
	XMLName       xml.Name                             `xml:"http://ws.gematik.de/conn/EventService/v7.2 GetSubscriptionResponse"`
	Status        connectorcommon50.Status             `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	Subscriptions GetSubscriptionResponseSubscriptions `xml:"Subscriptions"`
}

type GetResourceInformation struct {
	XMLName    xml.Name                   `xml:"http://ws.gematik.de/conn/EventService/v7.2 GetResourceInformation"`
	Context    connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CtId       string                     `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CtId,omitempty"`
	SlotId     int                        `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 SlotId,omitempty"`
	Iccsn      string                     `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 Iccsn,omitempty"`
	CardHandle string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle,omitempty"`
}

type GetResourceInformationResponse struct {
	XMLName      xml.Name                         `xml:"http://ws.gematik.de/conn/EventService/v7.2 GetResourceInformationResponse"`
	Status       connectorcommon50.Status         `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	Card         *cardservice81.Card              `xml:"http://ws.gematik.de/conn/CardService/v8.1 Card,omitempty"`
	CardTerminal *cardterminalinfo80.CardTerminal `xml:"http://ws.gematik.de/conn/CardTerminalInfo/v8.0 CardTerminal,omitempty"`
	Connector    *connectorcommon50.Connector     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Connector,omitempty"`
}

type GetCards struct {
	XMLName     xml.Name                     `xml:"http://ws.gematik.de/conn/EventService/v7.2 GetCards"`
	MandantWide bool                         `xml:"mandant-wide,attr,omitempty"`
	Context     connectorcontext20.Context   `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CtId        string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CtId,omitempty"`
	SlotId      int                          `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 SlotId,omitempty"`
	CardType    cardservicecommon20.CardType `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CardType,omitempty"`
}

type GetCardsResponse struct {
	XMLName xml.Name                 `xml:"http://ws.gematik.de/conn/EventService/v7.2 GetCardsResponse"`
	Status  connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	Cards   cardservice81.Cards      `xml:"http://ws.gematik.de/conn/CardService/v8.1 Cards"`
}

type GetCardTerminals struct {
	XMLName     xml.Name                   `xml:"http://ws.gematik.de/conn/EventService/v7.2 GetCardTerminals"`
	MandantWide bool                       `xml:"mandant-wide,attr,omitempty"`
	Context     connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
}

type GetCardTerminalsResponse struct {
	XMLName       xml.Name                         `xml:"http://ws.gematik.de/conn/EventService/v7.2 GetCardTerminalsResponse"`
	Status        connectorcommon50.Status         `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	CardTerminals cardterminalinfo80.CardTerminals `xml:"http://ws.gematik.de/conn/CardTerminalInfo/v8.0 CardTerminals"`
}

type Subscription struct {
	XMLName         xml.Name `xml:"http://ws.gematik.de/conn/EventService/v7.2 Subscription"`
	SubscriptionID  string   `xml:"SubscriptionID,omitempty"`
	TerminationTime string   `xml:"TerminationTime,omitempty"`
	EventTo         string   `xml:"EventTo"`
	Topic           string   `xml:"Topic"`
	Filter          string   `xml:"Filter,omitempty"`
}

type RenewSubscriptions struct {
	XMLName        xml.Name                   `xml:"http://ws.gematik.de/conn/EventService/v7.2 RenewSubscriptions"`
	Context        connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	SubscriptionID []string                   `xml:"SubscriptionID"`
}

type RenewSubscriptionsResponse struct {
	XMLName           xml.Name                                    `xml:"http://ws.gematik.de/conn/EventService/v7.2 RenewSubscriptionsResponse"`
	Status            connectorcommon50.Status                    `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	SubscribeRenewals RenewSubscriptionsResponseSubscribeRenewals `xml:"SubscribeRenewals"`
}

type EventType string

// Enum values for EventType
const (
	EventTypeOperation      EventType = "Operation"
	EventTypeSecurity       EventType = "Security"
	EventTypeInfrastructure EventType = "Infrastructure"
	EventTypeBusiness       EventType = "Business"
	EventTypeOther          EventType = "Other"
)

func (v EventType) IsValid() bool {
	switch v {
	case EventTypeOperation:
		return true
	case EventTypeSecurity:
		return true
	case EventTypeInfrastructure:
		return true
	case EventTypeBusiness:
		return true
	case EventTypeOther:
		return true
	default:
		return false
	}
}

type EventSeverityType string

// Enum values for EventSeverityType
const (
	EventSeverityTypeInfo    EventSeverityType = "Info"
	EventSeverityTypeWarning EventSeverityType = "Warning"
	EventSeverityTypeError   EventSeverityType = "Error"
	EventSeverityTypeFatal   EventSeverityType = "Fatal"
)

func (v EventSeverityType) IsValid() bool {
	switch v {
	case EventSeverityTypeInfo:
		return true
	case EventSeverityTypeWarning:
		return true
	case EventSeverityTypeError:
		return true
	case EventSeverityTypeFatal:
		return true
	default:
		return false
	}
}

type SubscriptionType struct {
	SubscriptionID  string `xml:"http://ws.gematik.de/conn/EventService/v7.2 SubscriptionID,omitempty"`
	TerminationTime string `xml:"http://ws.gematik.de/conn/EventService/v7.2 TerminationTime,omitempty"`
	EventTo         string `xml:"http://ws.gematik.de/conn/EventService/v7.2 EventTo"`
	Topic           string `xml:"http://ws.gematik.de/conn/EventService/v7.2 Topic"`
	Filter          string `xml:"http://ws.gematik.de/conn/EventService/v7.2 Filter,omitempty"`
}

// Interface for types that extend SubscriptionType
type ISubscriptionType interface {
	IsEventService72SubscriptionType()
}

// The type itself implements ISubscriptionType
func (SubscriptionType) IsEventService72SubscriptionType() {}

type EventMessage struct {
	XMLName   xml.Name                `xml:"http://ws.gematik.de/conn/EventService/v7.2 Message"`
	Parameter []EventMessageParameter `xml:"Parameter"`
}

type GetSubscriptionResponseSubscriptions struct {
	XMLName      xml.Name       `xml:"http://ws.gematik.de/conn/EventService/v7.2 Subscriptions"`
	Subscription []Subscription `xml:"Subscription"`
}

type RenewSubscriptionsResponseSubscribeRenewals struct {
	XMLName             xml.Name              `xml:"http://ws.gematik.de/conn/EventService/v7.2 SubscribeRenewals"`
	SubscriptionRenewal []SubscriptionRenewal `xml:"SubscriptionRenewal"`
}

type EventMessageParameter struct {
	XMLName xml.Name `xml:"http://ws.gematik.de/conn/EventService/v7.2 Parameter"`
	Key     string   `xml:"Key"`
	Value   string   `xml:"Value"`
}
