// Code generated by wsdl2openapi; DO NOT EDIT.

package xmldsig

import "encoding/xml"

type Signature struct {
	XMLName        xml.Name       `xml:"http://www.w3.org/2000/09/xmldsig# Signature"`
	Id             string         `xml:"Id,attr,omitempty"`
	SignedInfo     SignedInfo     `xml:"SignedInfo"`
	SignatureValue SignatureValue `xml:"SignatureValue"`
	KeyInfo        *KeyInfo       `xml:"KeyInfo,omitempty"`
	Object         []Object       `xml:"Object"`
}

type SignatureValue struct {
	XMLName  xml.Name `xml:"http://www.w3.org/2000/09/xmldsig# SignatureValue"`
	Id       string   `xml:"Id,attr,omitempty"`
	CharData string   `xml:"chardata"`
}

type SignedInfo struct {
	XMLName                xml.Name               `xml:"http://www.w3.org/2000/09/xmldsig# SignedInfo"`
	Id                     string                 `xml:"Id,attr,omitempty"`
	CanonicalizationMethod CanonicalizationMethod `xml:"CanonicalizationMethod"`
	SignatureMethod        SignatureMethod        `xml:"SignatureMethod"`
	Reference              []Reference            `xml:"Reference"`
}

type CanonicalizationMethod struct {
	XMLName        xml.Name `xml:"http://www.w3.org/2000/09/xmldsig# CanonicalizationMethod"`
	Algorithm      string   `xml:"Algorithm,attr"`
	UnknownContent string
}

type SignatureMethod struct {
	XMLName          xml.Name `xml:"http://www.w3.org/2000/09/xmldsig# SignatureMethod"`
	Algorithm        string   `xml:"Algorithm,attr"`
	HMACOutputLength int      `xml:"HMACOutputLength,omitempty"`
	UnknownContent   string
}

type Reference struct {
	XMLName      xml.Name     `xml:"http://www.w3.org/2000/09/xmldsig# Reference"`
	Id           string       `xml:"Id,attr,omitempty"`
	Uri          string       `xml:"URI,attr,omitempty"`
	Type         string       `xml:"Type,attr,omitempty"`
	Transforms   *Transforms  `xml:"Transforms,omitempty"`
	DigestMethod DigestMethod `xml:"DigestMethod"`
	DigestValue  string       `xml:"DigestValue"`
}

type Transforms struct {
	XMLName   xml.Name    `xml:"http://www.w3.org/2000/09/xmldsig# Transforms"`
	Transform []Transform `xml:"Transform"`
}

type Transform struct {
	XMLName        xml.Name `xml:"http://www.w3.org/2000/09/xmldsig# Transform"`
	Algorithm      string   `xml:"Algorithm,attr"`
	UnknownContent string
	XPath          []string `xml:"XPath"`
}

type DigestMethod struct {
	XMLName        xml.Name `xml:"http://www.w3.org/2000/09/xmldsig# DigestMethod"`
	Algorithm      string   `xml:"Algorithm,attr"`
	UnknownContent string
}

type KeyInfo struct {
	XMLName         xml.Name          `xml:"http://www.w3.org/2000/09/xmldsig# KeyInfo"`
	Id              string            `xml:"Id,attr,omitempty"`
	KeyName         []string          `xml:"KeyName,omitempty"`
	KeyValue        []KeyValue        `xml:"KeyValue"`
	RetrievalMethod []RetrievalMethod `xml:"RetrievalMethod"`
	X509Data        []X509Data        `xml:"X509Data"`
	PGPData         []PGPData         `xml:"PGPData"`
	SPKIData        []SPKIData        `xml:"SPKIData"`
	MgmtData        []string          `xml:"MgmtData,omitempty"`
	UnknownContent  string
}

type KeyValue struct {
	XMLName        xml.Name     `xml:"http://www.w3.org/2000/09/xmldsig# KeyValue"`
	DSAKeyValue    *DSAKeyValue `xml:"DSAKeyValue,omitempty"`
	RSAKeyValue    *RSAKeyValue `xml:"RSAKeyValue,omitempty"`
	UnknownContent string
}

type RetrievalMethod struct {
	XMLName    xml.Name    `xml:"http://www.w3.org/2000/09/xmldsig# RetrievalMethod"`
	Uri        string      `xml:"URI,attr,omitempty"`
	Type       string      `xml:"Type,attr,omitempty"`
	Transforms *Transforms `xml:"Transforms,omitempty"`
}

type X509Data struct {
	XMLName          xml.Name              `xml:"http://www.w3.org/2000/09/xmldsig# X509Data"`
	X509IssuerSerial *X509IssuerSerialType `xml:"X509IssuerSerial,omitempty"`
	X509ski          string                `xml:"X509SKI,omitempty"`
	X509SubjectName  string                `xml:"X509SubjectName,omitempty"`
	X509Certificate  string                `xml:"X509Certificate,omitempty"`
	X509crl          string                `xml:"X509CRL,omitempty"`
	UnknownContent   string
}

type PGPData struct {
	XMLName        xml.Name `xml:"http://www.w3.org/2000/09/xmldsig# PGPData"`
	PGPKeyID       string   `xml:"PGPKeyID"`
	PGPKeyPacket   string   `xml:"PGPKeyPacket,omitempty"`
	UnknownContent string
}

type SPKIData struct {
	XMLName        xml.Name `xml:"http://www.w3.org/2000/09/xmldsig# SPKIData"`
	SPKISexp       []string `xml:"SPKISexp"`
	UnknownContent string
}

type Object struct {
	XMLName        xml.Name `xml:"http://www.w3.org/2000/09/xmldsig# Object"`
	Id             string   `xml:"Id,attr,omitempty"`
	MimeType       string   `xml:"MimeType,attr,omitempty"`
	Encoding       string   `xml:"Encoding,attr,omitempty"`
	UnknownContent string
}

type Manifest struct {
	XMLName   xml.Name    `xml:"http://www.w3.org/2000/09/xmldsig# Manifest"`
	Id        string      `xml:"Id,attr,omitempty"`
	Reference []Reference `xml:"Reference"`
}

type SignatureProperties struct {
	XMLName           xml.Name            `xml:"http://www.w3.org/2000/09/xmldsig# SignatureProperties"`
	Id                string              `xml:"Id,attr,omitempty"`
	SignatureProperty []SignatureProperty `xml:"SignatureProperty"`
}

type SignatureProperty struct {
	XMLName        xml.Name `xml:"http://www.w3.org/2000/09/xmldsig# SignatureProperty"`
	Target         string   `xml:"Target,attr"`
	Id             string   `xml:"Id,attr,omitempty"`
	UnknownContent string
}

type DSAKeyValue struct {
	XMLName     xml.Name `xml:"http://www.w3.org/2000/09/xmldsig# DSAKeyValue"`
	P           string   `xml:"P"`
	Q           string   `xml:"Q"`
	G           string   `xml:"G,omitempty"`
	Y           string   `xml:"Y"`
	J           string   `xml:"J,omitempty"`
	Seed        string   `xml:"Seed"`
	PgenCounter string   `xml:"PgenCounter"`
}

type RSAKeyValue struct {
	XMLName  xml.Name `xml:"http://www.w3.org/2000/09/xmldsig# RSAKeyValue"`
	Modulus  string   `xml:"Modulus"`
	Exponent string   `xml:"Exponent"`
}

type SignatureType struct {
	Id             string         `xml:"Id,attr,omitempty"`
	SignedInfo     SignedInfo     `xml:"http://www.w3.org/2000/09/xmldsig# SignedInfo"`
	SignatureValue SignatureValue `xml:"http://www.w3.org/2000/09/xmldsig# SignatureValue"`
	KeyInfo        *KeyInfo       `xml:"http://www.w3.org/2000/09/xmldsig# KeyInfo,omitempty"`
	Object         []Object       `xml:"http://www.w3.org/2000/09/xmldsig# Object"`
}

// Interface for types that extend SignatureType
type ISignatureType interface {
	IsXmldsigSignatureType()
}

// The type itself implements ISignatureType
func (SignatureType) IsXmldsigSignatureType() {}

type SignatureValueType struct {
	Id       string `xml:"Id,attr,omitempty"`
	CharData string `xml:"chardata"`
}

// Interface for types that extend SignatureValueType
type ISignatureValueType interface {
	IsXmldsigSignatureValueType()
}

// The type itself implements ISignatureValueType
func (SignatureValueType) IsXmldsigSignatureValueType() {}

type SignedInfoType struct {
	Id                     string                 `xml:"Id,attr,omitempty"`
	CanonicalizationMethod CanonicalizationMethod `xml:"http://www.w3.org/2000/09/xmldsig# CanonicalizationMethod"`
	SignatureMethod        SignatureMethod        `xml:"http://www.w3.org/2000/09/xmldsig# SignatureMethod"`
	Reference              []Reference            `xml:"http://www.w3.org/2000/09/xmldsig# Reference"`
}

// Interface for types that extend SignedInfoType
type ISignedInfoType interface {
	IsXmldsigSignedInfoType()
}

// The type itself implements ISignedInfoType
func (SignedInfoType) IsXmldsigSignedInfoType() {}

type CanonicalizationMethodType struct {
	Algorithm      string `xml:"Algorithm,attr"`
	UnknownContent string
}

// Interface for types that extend CanonicalizationMethodType
type ICanonicalizationMethodType interface {
	IsXmldsigCanonicalizationMethodType()
}

// The type itself implements ICanonicalizationMethodType
func (CanonicalizationMethodType) IsXmldsigCanonicalizationMethodType() {}

type SignatureMethodType struct {
	Algorithm        string `xml:"Algorithm,attr"`
	HMACOutputLength int    `xml:"http://www.w3.org/2000/09/xmldsig# HMACOutputLength,omitempty"`
	UnknownContent   string
}

// Interface for types that extend SignatureMethodType
type ISignatureMethodType interface {
	IsXmldsigSignatureMethodType()
}

// The type itself implements ISignatureMethodType
func (SignatureMethodType) IsXmldsigSignatureMethodType() {}

type ReferenceType struct {
	Id           string       `xml:"Id,attr,omitempty"`
	Uri          string       `xml:"URI,attr,omitempty"`
	Type         string       `xml:"Type,attr,omitempty"`
	Transforms   *Transforms  `xml:"http://www.w3.org/2000/09/xmldsig# Transforms,omitempty"`
	DigestMethod DigestMethod `xml:"http://www.w3.org/2000/09/xmldsig# DigestMethod"`
	DigestValue  string       `xml:"http://www.w3.org/2000/09/xmldsig# DigestValue"`
}

// Interface for types that extend ReferenceType
type IReferenceType interface {
	IsXmldsigReferenceType()
}

// The type itself implements IReferenceType
func (ReferenceType) IsXmldsigReferenceType() {}

type TransformsType struct {
	Transform []Transform `xml:"http://www.w3.org/2000/09/xmldsig# Transform"`
}

// Interface for types that extend TransformsType
type ITransformsType interface {
	IsXmldsigTransformsType()
}

// The type itself implements ITransformsType
func (TransformsType) IsXmldsigTransformsType() {}

type TransformType struct {
	Algorithm      string `xml:"Algorithm,attr"`
	UnknownContent string
	XPath          []string `xml:"http://www.w3.org/2000/09/xmldsig# XPath"`
}

// Interface for types that extend TransformType
type ITransformType interface {
	IsXmldsigTransformType()
}

// The type itself implements ITransformType
func (TransformType) IsXmldsigTransformType() {}

type DigestMethodType struct {
	Algorithm      string `xml:"Algorithm,attr"`
	UnknownContent string
}

// Interface for types that extend DigestMethodType
type IDigestMethodType interface {
	IsXmldsigDigestMethodType()
}

// The type itself implements IDigestMethodType
func (DigestMethodType) IsXmldsigDigestMethodType() {}

type KeyInfoType struct {
	Id              string            `xml:"Id,attr,omitempty"`
	KeyName         []string          `xml:"http://www.w3.org/2000/09/xmldsig# KeyName,omitempty"`
	KeyValue        []KeyValue        `xml:"http://www.w3.org/2000/09/xmldsig# KeyValue"`
	RetrievalMethod []RetrievalMethod `xml:"http://www.w3.org/2000/09/xmldsig# RetrievalMethod"`
	X509Data        []X509Data        `xml:"http://www.w3.org/2000/09/xmldsig# X509Data"`
	PGPData         []PGPData         `xml:"http://www.w3.org/2000/09/xmldsig# PGPData"`
	SPKIData        []SPKIData        `xml:"http://www.w3.org/2000/09/xmldsig# SPKIData"`
	MgmtData        []string          `xml:"http://www.w3.org/2000/09/xmldsig# MgmtData,omitempty"`
	UnknownContent  string
}

// Interface for types that extend KeyInfoType
type IKeyInfoType interface {
	IsXmldsigKeyInfoType()
}

// The type itself implements IKeyInfoType
func (KeyInfoType) IsXmldsigKeyInfoType() {}

type KeyValueType struct {
	DSAKeyValue    *DSAKeyValue `xml:"http://www.w3.org/2000/09/xmldsig# DSAKeyValue,omitempty"`
	RSAKeyValue    *RSAKeyValue `xml:"http://www.w3.org/2000/09/xmldsig# RSAKeyValue,omitempty"`
	UnknownContent string
}

// Interface for types that extend KeyValueType
type IKeyValueType interface {
	IsXmldsigKeyValueType()
}

// The type itself implements IKeyValueType
func (KeyValueType) IsXmldsigKeyValueType() {}

type RetrievalMethodType struct {
	Uri        string      `xml:"URI,attr,omitempty"`
	Type       string      `xml:"Type,attr,omitempty"`
	Transforms *Transforms `xml:"http://www.w3.org/2000/09/xmldsig# Transforms,omitempty"`
}

// Interface for types that extend RetrievalMethodType
type IRetrievalMethodType interface {
	IsXmldsigRetrievalMethodType()
}

// The type itself implements IRetrievalMethodType
func (RetrievalMethodType) IsXmldsigRetrievalMethodType() {}

type X509DataType struct {
	X509IssuerSerial *X509IssuerSerialType `xml:"http://www.w3.org/2000/09/xmldsig# X509IssuerSerial,omitempty"`
	X509ski          string                `xml:"http://www.w3.org/2000/09/xmldsig# X509SKI,omitempty"`
	X509SubjectName  string                `xml:"http://www.w3.org/2000/09/xmldsig# X509SubjectName,omitempty"`
	X509Certificate  string                `xml:"http://www.w3.org/2000/09/xmldsig# X509Certificate,omitempty"`
	X509crl          string                `xml:"http://www.w3.org/2000/09/xmldsig# X509CRL,omitempty"`
	UnknownContent   string
}

// Interface for types that extend X509DataType
type IX509DataType interface {
	IsXmldsigX509DataType()
}

// The type itself implements IX509DataType
func (X509DataType) IsXmldsigX509DataType() {}

type X509IssuerSerialType struct {
	X509IssuerName   string `xml:"http://www.w3.org/2000/09/xmldsig# X509IssuerName"`
	X509SerialNumber int    `xml:"http://www.w3.org/2000/09/xmldsig# X509SerialNumber"`
}

type PGPDataType struct {
	PGPKeyID       string `xml:"http://www.w3.org/2000/09/xmldsig# PGPKeyID"`
	PGPKeyPacket   string `xml:"http://www.w3.org/2000/09/xmldsig# PGPKeyPacket,omitempty"`
	UnknownContent string
}

// Interface for types that extend PGPDataType
type IPGPDataType interface {
	IsXmldsigPGPDataType()
}

// The type itself implements IPGPDataType
func (PGPDataType) IsXmldsigPGPDataType() {}

type SPKIDataType struct {
	SPKISexp       []string `xml:"http://www.w3.org/2000/09/xmldsig# SPKISexp"`
	UnknownContent string
}

// Interface for types that extend SPKIDataType
type ISPKIDataType interface {
	IsXmldsigSPKIDataType()
}

// The type itself implements ISPKIDataType
func (SPKIDataType) IsXmldsigSPKIDataType() {}

type ObjectType struct {
	Id             string `xml:"Id,attr,omitempty"`
	MimeType       string `xml:"MimeType,attr,omitempty"`
	Encoding       string `xml:"Encoding,attr,omitempty"`
	UnknownContent string
}

// Interface for types that extend ObjectType
type IObjectType interface {
	IsXmldsigObjectType()
}

// The type itself implements IObjectType
func (ObjectType) IsXmldsigObjectType() {}

type ManifestType struct {
	Id        string      `xml:"Id,attr,omitempty"`
	Reference []Reference `xml:"http://www.w3.org/2000/09/xmldsig# Reference"`
}

// Interface for types that extend ManifestType
type IManifestType interface {
	IsXmldsigManifestType()
}

// The type itself implements IManifestType
func (ManifestType) IsXmldsigManifestType() {}

type SignaturePropertiesType struct {
	Id                string              `xml:"Id,attr,omitempty"`
	SignatureProperty []SignatureProperty `xml:"http://www.w3.org/2000/09/xmldsig# SignatureProperty"`
}

// Interface for types that extend SignaturePropertiesType
type ISignaturePropertiesType interface {
	IsXmldsigSignaturePropertiesType()
}

// The type itself implements ISignaturePropertiesType
func (SignaturePropertiesType) IsXmldsigSignaturePropertiesType() {}

type SignaturePropertyType struct {
	Target         string `xml:"Target,attr"`
	Id             string `xml:"Id,attr,omitempty"`
	UnknownContent string
}

// Interface for types that extend SignaturePropertyType
type ISignaturePropertyType interface {
	IsXmldsigSignaturePropertyType()
}

// The type itself implements ISignaturePropertyType
func (SignaturePropertyType) IsXmldsigSignaturePropertyType() {}

type DSAKeyValueType struct {
	P           string `xml:"http://www.w3.org/2000/09/xmldsig# P"`
	Q           string `xml:"http://www.w3.org/2000/09/xmldsig# Q"`
	G           string `xml:"http://www.w3.org/2000/09/xmldsig# G,omitempty"`
	Y           string `xml:"http://www.w3.org/2000/09/xmldsig# Y"`
	J           string `xml:"http://www.w3.org/2000/09/xmldsig# J,omitempty"`
	Seed        string `xml:"http://www.w3.org/2000/09/xmldsig# Seed"`
	PgenCounter string `xml:"http://www.w3.org/2000/09/xmldsig# PgenCounter"`
}

// Interface for types that extend DSAKeyValueType
type IDSAKeyValueType interface {
	IsXmldsigDSAKeyValueType()
}

// The type itself implements IDSAKeyValueType
func (DSAKeyValueType) IsXmldsigDSAKeyValueType() {}

type RSAKeyValueType struct {
	Modulus  string `xml:"http://www.w3.org/2000/09/xmldsig# Modulus"`
	Exponent string `xml:"http://www.w3.org/2000/09/xmldsig# Exponent"`
}

// Interface for types that extend RSAKeyValueType
type IRSAKeyValueType interface {
	IsXmldsigRSAKeyValueType()
}

// The type itself implements IRSAKeyValueType
func (RSAKeyValueType) IsXmldsigRSAKeyValueType() {}
