
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.anstream]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.14"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.1.5"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.11"
criteria = "safe-to-deploy"

[[exemptions.arc-swap]]
version = "1.9.2"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.5.1"
criteria = "safe-to-deploy"

[[exemptions.base16ct]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.23.1"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.8.3"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.13.2"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.bp256]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.bp384]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.12.1"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.6.7"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.6.7"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.6.7"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.cmov]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.cpubits]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.crypto-bigint]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.crypto-primes]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.ctutils]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.defmt]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.defmt-macros]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.defmt-parser]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.der_derive]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.displaydoc]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.ecdsa]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.elliptic-curve]]
version = "0.14.1"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.ff]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.flagset]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.34"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.34"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.34"
criteria = "safe-to-run"

[[exemptions.futures-lite]]
version = "2.6.1"
criteria = "safe-to-run"

[[exemptions.futures-task]]
version = "0.3.34"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.34"
criteria = "safe-to-deploy"

[[exemptions.group]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.hmac]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.http-body-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.hybrid-array]]
version = "0.4.15"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.hyper-util]]
version = "0.1.20"
criteria = "safe-to-deploy"

[[exemptions.icu_collections]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.icu_locale_core]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.icu_normalizer]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.icu_normalizer_data]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.icu_properties]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.icu_properties_data]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.icu_provider]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.idna]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.idna_adapter]]
version = "1.2.2"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.12.2"
criteria = "safe-to-deploy"

[[exemptions.is_terminal_polyfill]]
version = "1.70.2"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.jiff]]
version = "0.2.37"
criteria = "safe-to-deploy"

[[exemptions.jiff-core]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.jiff-static]]
version = "0.2.37"
criteria = "safe-to-deploy"

[[exemptions.jiff-tzdb]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.jiff-tzdb-platform]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.105"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.189"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.litemap]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.34"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.8.3"
criteria = "safe-to-deploy"

[[exemptions.minicbor]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.2.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell_polyfill]]
version = "1.70.2"
criteria = "safe-to-deploy"

[[exemptions.p256]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.p384]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.pem-rfc7468]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.pkcs1]]
version = "0.8.0-rc.4"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic-util]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.potential_utf]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.primefield]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.primeorder]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.107"
criteria = "safe-to-deploy"

[[exemptions.quick-xml]]
version = "0.42.0"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.reqwest]]
version = "0.13.5"
criteria = "safe-to-deploy"

[[exemptions.rfc6979]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.rsa]]
version = "0.10.0-rc.18"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.1.5"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.15.1"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.23"
criteria = "safe-to-deploy"

[[exemptions.sec1]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.229"
criteria = "safe-to-deploy"

[[exemptions.serde_core]]
version = "1.0.229"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.229"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.151"
criteria = "safe-to-deploy"

[[exemptions.serdect]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.sha1]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.8"
criteria = "safe-to-deploy"

[[exemptions.signature]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.16.1"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.119"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "3.0.6"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.synstructure]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.terminal_size]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.20"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.20"
criteria = "safe-to-deploy"

[[exemptions.tinystr]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.tls_codec]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.tls_codec_derive]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.53.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.7.2"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.tower-http]]
version = "0.6.11"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.44"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.36"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.20.1"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.26"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.5.8"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.128"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.78"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.128"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.128"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.128"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.105"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.wnaf]]
version = "0.14.1"
criteria = "safe-to-deploy"

[[exemptions.writeable]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.x509-cert]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.yoke]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.yoke-derive]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.zerofrom]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.zerofrom-derive]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.zeroize_derive]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.zerotrie]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.zerovec]]
version = "0.11.8"
criteria = "safe-to-deploy"

[[exemptions.zerovec-derive]]
version = "0.11.6"
criteria = "safe-to-deploy"

[[exemptions.zmij]]
version = "1.0.23"
criteria = "safe-to-deploy"
