
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.anstyle]]
version = "1.0.14"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.8.3"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.6.7"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.6.7"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.6.7"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.der_derive]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.flagset]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.18"
criteria = "safe-to-run"

[[exemptions.memchr]]
version = "2.8.3"
criteria = "safe-to-run"

[[exemptions.pem-rfc7468]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.107"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.229"
criteria = "safe-to-deploy"

[[exemptions.serde_core]]
version = "1.0.229"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.229"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.151"
criteria = "safe-to-run"

[[exemptions.spki]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.119"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "3.0.6"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.20"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.20"
criteria = "safe-to-deploy"

[[exemptions.tls_codec]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.tls_codec_derive]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.26"
criteria = "safe-to-deploy"

[[exemptions.x509-cert]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.zeroize_derive]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.zmij]]
version = "1.0.23"
criteria = "safe-to-run"
