// Code generated by wsdl2openapi go generator. DO NOT EDIT.

package cardterminalservice11

import (
	"encoding/xml"
	error20 "github.com/gematik/zero-lab/go/kon/api/gematik/tel/error20"
)

type soapOperation struct {
	name        string
	soapAction  string
	bindingType string
}

func (op *soapOperation) Name() string {
	return op.name
}

func (op *soapOperation) SOAPAction() string {
	return op.soapAction
}

func (op *soapOperation) BindingType() string {
	return op.bindingType
}

var OperationRequestCard = soapOperation{
	bindingType: "soap11",
	name:        "RequestCard",
	soapAction:  "http://ws.gematik.de/conn/CardTerminalService/v1.1#RequestCard",
}

type RequestCardEnvelope struct {
	XMLName     xml.Name     `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	RequestCard *RequestCard `xml:"Body>RequestCard"`
}

func (e *RequestCardEnvelope) IsFault() bool {
	return false
}

type RequestCardResponseEnvelope struct {
	XMLName             xml.Name             `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	RequestCardResponse *RequestCardResponse `xml:"Body>RequestCardResponse"`
	Fault               *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *RequestCardResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationEjectCard = soapOperation{
	bindingType: "soap11",
	name:        "EjectCard",
	soapAction:  "http://ws.gematik.de/conn/CardTerminalService/v1.1#EjectCard",
}

type EjectCardEnvelope struct {
	XMLName   xml.Name   `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	EjectCard *EjectCard `xml:"Body>EjectCard"`
}

func (e *EjectCardEnvelope) IsFault() bool {
	return false
}

type EjectCardResponseEnvelope struct {
	XMLName           xml.Name           `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	EjectCardResponse *EjectCardResponse `xml:"Body>EjectCardResponse"`
	Fault             *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *EjectCardResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}
