version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-insecure}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-zero}
      MONGO_DATABASE: ${MONGO_DATABASE:-zero}
      MONGO_USERNAME: ${MONGO_USERNAME:-mongo}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-mongo}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

