#![doc = include_str!("../README.md")]

#[allow(
    missing_docs,
    clippy::all,
    clippy::pedantic,
    rustdoc::all,
    reason = "generated by wsdl2openapi from api.select.json; `just generate-connector`"
)]
pub mod api;
mod cards;
mod connector;
mod dotkon;
mod error;
mod sds;
mod soap;

pub use cards::Cards;
pub use connector::Connector;
pub use dotkon::{Credentials, Dotkon, DotkonError};
pub use error::{DiscoveryError, Error, Fault, TraceEntry};
pub use sds::{Binding, Product, Service, ServiceDirectory, ServiceVersion, Target, sds_url};
pub use soap::{Method, Request, Response, Timeouts, Transport, TransportError};

/// The services and `major.minor` versions this crate has bindings for, as
/// [`ServiceDirectory::resolve`] takes them; newer versions first.
pub const BINDINGS: &[(&str, &[&str])] = &[
    ("EventService", &["7.2"]),
    ("CardService", &["8.2", "8.1"]),
    ("CertificateService", &["6.0"]),
    ("AuthSignatureService", &["7.4"]),
    ("SignatureService", &["7.5", "7.4"]),
    ("EncryptionService", &["6.1"]),
];

/// The generated types callers see, under names that do not change with the service
/// version that produced them.
pub mod types {
    pub use crate::api::gematik::conn::cardservice81::{
        Card, CardInfoTypeCardVersion as CardVersion, VersionInfoType,
    };
    pub use crate::api::gematik::conn::cardservicecommon20::CardType;
    pub use crate::api::soap::{SoapOperation, Timeout};
}
