// Code generated by wsdl2openapi; DO NOT EDIT.

pub type GenerateUnderSignaturePolicy = SignaturePolicyDetailsType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
pub struct SignaturePolicyDetailsType {
    #[serde(rename = "signaturepolicy:SignaturePolicyIdentifier")]
    pub signature_policy_identifier: String,
    #[serde(
        rename = "signaturepolicy:SignaturePolicyLocation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signature_policy_location: Option<String>,
    #[serde(
        rename = "signaturepolicy:DigestAndAlgorithm",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub digest_and_algorithm: Option<crate::api::etsi01903132::DigestAlgAndValueType>,
}
