// Code generated by wsdl2openapi; DO NOT EDIT.

package verificationreport

import (
	"encoding/xml"
	etsi01903132 "github.com/gematik/zero-lab/go/kon/api/etsi01903132"
	etsi022312 "github.com/gematik/zero-lab/go/kon/api/etsi022312"
	dss10core "github.com/gematik/zero-lab/go/kon/api/oasis/dss10core"
	saml10assertion "github.com/gematik/zero-lab/go/kon/api/oasis/saml10assertion"
	saml20assertion "github.com/gematik/zero-lab/go/kon/api/oasis/saml20assertion"
	xmldsig "github.com/gematik/zero-lab/go/kon/api/w3200009/xmldsig"
)

type ReturnVerificationReport struct {
	XMLName                  xml.Name `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ReturnVerificationReport"`
	IncludeVerifier          bool     `xml:"IncludeVerifier,omitempty"`
	IncludeCertificateValues bool     `xml:"IncludeCertificateValues,omitempty"`
	IncludeRevocationValues  bool     `xml:"IncludeRevocationValues,omitempty"`
	ExpandBinaryValues       bool     `xml:"ExpandBinaryValues,omitempty"`
	ReportDetailLevel        string   `xml:"ReportDetailLevel,omitempty"`
}

type VerificationReport struct {
	XMLName              xml.Name                        `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# VerificationReport"`
	VerificationTimeInfo *dss10core.VerificationTimeInfo `xml:"urn:oasis:names:tc:dss:1.0:core:schema VerificationTimeInfo,omitempty"`
	VerifierIdentity     *IdentifierType                 `xml:"VerifierIdentity,omitempty"`
	IndividualReport     []IndividualReportType          `xml:"IndividualReport"`
}

type DetailedSignatureReport struct {
	XMLName                    xml.Name                         `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# DetailedSignatureReport"`
	FormatOK                   VerificationResultType           `xml:"FormatOK"`
	Properties                 *PropertiesType                  `xml:"Properties,omitempty"`
	VerifyManifestResults      *dss10core.VerifyManifestResults `xml:"urn:oasis:names:tc:dss:1.0:core:schema VerifyManifestResults,omitempty"`
	SignatureHasVisibleContent bool                             `xml:"SignatureHasVisibleContent,omitempty"`
	SignatureOK                SignatureValidityType            `xml:"SignatureOK"`
	CertificatePathValidity    CertificatePathValidityType      `xml:"CertificatePathValidity"`
}

type IndividualTimeStampReport struct {
	XMLName                 xml.Name                    `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# IndividualTimeStampReport"`
	Id                      string                      `xml:"Id,attr,omitempty"`
	FormatOK                VerificationResultType      `xml:"FormatOK"`
	TimeStampContent        *TstContentType             `xml:"TimeStampContent,omitempty"`
	MessageHashAlgorithm    *AlgorithmValidityType      `xml:"MessageHashAlgorithm,omitempty"`
	SignatureOK             SignatureValidityType       `xml:"SignatureOK"`
	CertificatePathValidity CertificatePathValidityType `xml:"CertificatePathValidity"`
}

type IndividualCertificateReport struct {
	XMLName               xml.Name                     `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# IndividualCertificateReport"`
	CertificateIdentifier xmldsig.X509IssuerSerialType `xml:"CertificateIdentifier"`
	Subject               string                       `xml:"Subject"`
	ChainingOK            VerificationResultType       `xml:"ChainingOK"`
	ValidityPeriodOK      VerificationResultType       `xml:"ValidityPeriodOK"`
	ExtensionsOK          VerificationResultType       `xml:"ExtensionsOK"`
	CertificateValue      string                       `xml:"CertificateValue,omitempty"`
	CertificateContent    *CertificateContentType      `xml:"CertificateContent,omitempty"`
	SignatureOK           SignatureValidityType        `xml:"SignatureOK"`
	CertificateStatus     CertificateStatusType        `xml:"CertificateStatus"`
}

type IndividualAttributeCertificateReport struct {
	XMLName                        xml.Name                         `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# IndividualAttributeCertificateReport"`
	AttributeCertificateIdentifier AttrCertIDType                   `xml:"AttributeCertificateIdentifier"`
	AttributeCertificateValue      string                           `xml:"AttributeCertificateValue,omitempty"`
	AttributeCertificateContent    *AttributeCertificateContentType `xml:"AttributeCertificateContent,omitempty"`
	SignatureOK                    SignatureValidityType            `xml:"SignatureOK"`
	CertificatePathValidity        CertificatePathValidityType      `xml:"CertificatePathValidity"`
}

type IndividualCRLReport struct {
	XMLName                 xml.Name                       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# IndividualCRLReport"`
	Id                      string                         `xml:"Id,attr,omitempty"`
	CRLIdentifier           etsi01903132.CRLIdentifierType `xml:"CRLIdentifier"`
	CRLValue                string                         `xml:"CRLValue,omitempty"`
	CRLContent              *CRLContentType                `xml:"CRLContent,omitempty"`
	SignatureOK             SignatureValidityType          `xml:"SignatureOK"`
	CertificatePathValidity CertificatePathValidityType    `xml:"CertificatePathValidity"`
}

type IndividualOCSPReport struct {
	XMLName                 xml.Name                        `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# IndividualOCSPReport"`
	Id                      string                          `xml:"Id,attr,omitempty"`
	OCSPIdentifier          etsi01903132.OCSPIdentifierType `xml:"OCSPIdentifier"`
	OCSPValue               string                          `xml:"OCSPValue,omitempty"`
	OCSPContent             *OCSPContentType                `xml:"OCSPContent,omitempty"`
	SignatureOK             SignatureValidityType           `xml:"SignatureOK"`
	CertificatePathValidity CertificatePathValidityType     `xml:"CertificatePathValidity"`
}

type EvidenceRecordReport struct {
	XMLName                  xml.Name                                           `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# EvidenceRecordReport"`
	Id                       string                                             `xml:"Id,attr,omitempty"`
	FormatOK                 VerificationResultType                             `xml:"FormatOK"`
	Version                  int                                                `xml:"Version,omitempty"`
	DigestAlgorithm          []AlgorithmValidityType                            `xml:"DigestAlgorithm"`
	CryptoInfos              *EvidenceRecordValidityTypeCryptoInfos             `xml:"CryptoInfos,omitempty"`
	EncryptionInfo           *EvidenceRecordValidityTypeEncryptionInfo          `xml:"EncryptionInfo,omitempty"`
	ArchiveTimeStampSequence EvidenceRecordValidityTypeArchiveTimeStampSequence `xml:"ArchiveTimeStampSequence"`
}

type VerificationReportType struct {
	VerificationTimeInfo *dss10core.VerificationTimeInfo `xml:"urn:oasis:names:tc:dss:1.0:core:schema VerificationTimeInfo,omitempty"`
	VerifierIdentity     *IdentifierType                 `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# VerifierIdentity,omitempty"`
	IndividualReport     []IndividualReportType          `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# IndividualReport"`
}

// Interface for types that extend VerificationReportType
type IVerificationReportType interface {
	IsVerificationreportVerificationReportType()
}

// The type itself implements IVerificationReportType
func (VerificationReportType) IsVerificationreportVerificationReportType() {}

type IdentifierType struct {
	X509Data         *xmldsig.X509Data                   `xml:"http://www.w3.org/2000/09/xmldsig# X509Data,omitempty"`
	SAMLv1Identifier *saml10assertion.NameIdentifierType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SAMLv1Identifier,omitempty"`
	SAMLv2Identifier *saml20assertion.NameIDType         `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SAMLv2Identifier,omitempty"`
	Other            *dss10core.AnyType                  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Other,omitempty"`
}

type IndividualReportType struct {
	SignedObjectIdentifier SignedObjectIdentifierType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignedObjectIdentifier"`
	Result                 dss10core.Result           `xml:"urn:oasis:names:tc:dss:1.0:core:schema Result"`
	Details                *dss10core.AnyType         `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Details,omitempty"`
}

type SignedObjectIdentifierType struct {
	WhichDocument          string                              `xml:"WhichDocument,attr,omitempty"`
	XPath                  string                              `xml:"XPath,attr,omitempty"`
	Offset                 int                                 `xml:"Offset,attr,omitempty"`
	FieldName              string                              `xml:"FieldName,attr,omitempty"`
	DigestAlgAndValue      *etsi01903132.DigestAlgAndValueType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# DigestAlgAndValue,omitempty"`
	CanonicalizationMethod *xmldsig.CanonicalizationMethod     `xml:"http://www.w3.org/2000/09/xmldsig# CanonicalizationMethod,omitempty"`
	SignedProperties       *SignedPropertiesType               `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignedProperties,omitempty"`
	SignatureValue         *xmldsig.SignatureValue             `xml:"http://www.w3.org/2000/09/xmldsig# SignatureValue,omitempty"`
	Other                  *dss10core.AnyType                  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Other,omitempty"`
}

// Interface for types that extend SignedObjectIdentifierType
type ISignedObjectIdentifierType interface {
	IsVerificationreportSignedObjectIdentifierType()
}

// The type itself implements ISignedObjectIdentifierType
func (SignedObjectIdentifierType) IsVerificationreportSignedObjectIdentifierType() {}

type VerificationResultType struct {
	ResultMajor    string                             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ResultMajor"`
	ResultMinor    string                             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ResultMinor,omitempty"`
	ResultMessage  *dss10core.InternationalStringType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ResultMessage,omitempty"`
	UnknownContent string
}

type DetailedSignatureReportType struct {
	FormatOK                   VerificationResultType           `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# FormatOK"`
	Properties                 *PropertiesType                  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Properties,omitempty"`
	VerifyManifestResults      *dss10core.VerifyManifestResults `xml:"urn:oasis:names:tc:dss:1.0:core:schema VerifyManifestResults,omitempty"`
	SignatureHasVisibleContent bool                             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignatureHasVisibleContent,omitempty"`
	SignatureOK                SignatureValidityType            `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignatureOK"`
	CertificatePathValidity    CertificatePathValidityType      `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertificatePathValidity"`
}

// Interface for types that extend DetailedSignatureReportType
type IDetailedSignatureReportType interface {
	IsVerificationreportDetailedSignatureReportType()
}

// The type itself implements IDetailedSignatureReportType
func (DetailedSignatureReportType) IsVerificationreportDetailedSignatureReportType() {}

type PropertiesType struct {
	Target             string                  `xml:"Target,attr,omitempty"`
	Id                 string                  `xml:"Id,attr,omitempty"`
	SignedProperties   *SignedPropertiesType   `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignedProperties,omitempty"`
	UnsignedProperties *UnsignedPropertiesType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# UnsignedProperties,omitempty"`
}

type SignedPropertiesType struct {
	Id                         string                          `xml:"Id,attr,omitempty"`
	SignedSignatureProperties  *SignedSignaturePropertiesType  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignedSignatureProperties,omitempty"`
	SignedDataObjectProperties *SignedDataObjectPropertiesType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignedDataObjectProperties,omitempty"`
	Other                      *dss10core.AnyType              `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Other,omitempty"`
}

type SignedSignaturePropertiesType struct {
	SigningTime               string                                  `xml:"http://uri.etsi.org/01903/v1.3.2# SigningTime,omitempty"`
	SigningCertificate        *etsi01903132.SigningCertificate        `xml:"http://uri.etsi.org/01903/v1.3.2# SigningCertificate,omitempty"`
	SignaturePolicyIdentifier *etsi01903132.SignaturePolicyIdentifier `xml:"http://uri.etsi.org/01903/v1.3.2# SignaturePolicyIdentifier,omitempty"`
	SignatureProductionPlace  *etsi01903132.SignatureProductionPlace  `xml:"http://uri.etsi.org/01903/v1.3.2# SignatureProductionPlace,omitempty"`
	Location                  string                                  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Location,omitempty"`
	SignerRole                *SignerRoleType                         `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignerRole,omitempty"`
}

type SignerRoleType struct {
	ClaimedRoles   *etsi01903132.ClaimedRolesListType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ClaimedRoles,omitempty"`
	CertifiedRoles *CertifiedRolesListType            `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertifiedRoles,omitempty"`
}

type CertifiedRolesListType struct {
	AttributeCertificateValidity []AttributeCertificateValidityType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# AttributeCertificateValidity"`
}

type AttributeCertificateValidityType struct {
	AttributeCertificateIdentifier AttrCertIDType                   `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# AttributeCertificateIdentifier"`
	AttributeCertificateValue      string                           `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# AttributeCertificateValue,omitempty"`
	AttributeCertificateContent    *AttributeCertificateContentType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# AttributeCertificateContent,omitempty"`
	SignatureOK                    SignatureValidityType            `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignatureOK"`
	CertificatePathValidity        CertificatePathValidityType      `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertificatePathValidity"`
}

// Interface for types that extend AttributeCertificateValidityType
type IAttributeCertificateValidityType interface {
	IsVerificationreportAttributeCertificateValidityType()
}

// The type itself implements IAttributeCertificateValidityType
func (AttributeCertificateValidityType) IsVerificationreportAttributeCertificateValidityType() {}

type AttrCertIDType struct {
	Holder       *EntityType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Holder,omitempty"`
	Issuer       EntityType  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Issuer"`
	SerialNumber int         `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SerialNumber"`
}

type EntityType struct {
	BaseCertificateID *xmldsig.X509IssuerSerialType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# BaseCertificateID,omitempty"`
	Name              string                        `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Name,omitempty"`
	Other             *dss10core.AnyType            `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Other,omitempty"`
}

type AttributeCertificateContentType struct {
	Version               int                                       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Version,omitempty"`
	Holder                EntityType                                `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Holder"`
	Issuer                EntityType                                `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Issuer"`
	SignatureAlgorithm    string                                    `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignatureAlgorithm"`
	SerialNumber          int                                       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SerialNumber"`
	AttCertValidityPeriod ValidityPeriodType                        `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# AttCertValidityPeriod"`
	Attributes            AttributeCertificateContentTypeAttributes `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Attributes"`
	IssuerUniqueID        string                                    `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# IssuerUniqueID,omitempty"`
	Extensions            *ExtensionsType                           `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Extensions,omitempty"`
}

type ValidityPeriodType struct {
	NotBefore string `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# NotBefore"`
	NotAfter  string `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# NotAfter"`
}

type AttributeType struct {
	Type  VerificationResultType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Type"`
	Value []dss10core.AnyType    `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Value"`
}

type ExtensionsType struct {
	Extension []ExtensionType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Extension"`
}

type ExtensionType struct {
	ExtnId      etsi01903132.ObjectIdentifierType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ExtnId"`
	Critical    bool                              `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Critical"`
	ExtnValue   *dss10core.AnyType                `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ExtnValue,omitempty"`
	ExtensionOK VerificationResultType            `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ExtensionOK"`
}

type SignedDataObjectPropertiesType struct {
	Id                             string                                  `xml:"Id,attr,omitempty"`
	DataObjectFormat               []etsi01903132.DataObjectFormat         `xml:"http://uri.etsi.org/01903/v1.3.2# DataObjectFormat"`
	CommitmentTypeIndication       []etsi01903132.CommitmentTypeIndication `xml:"http://uri.etsi.org/01903/v1.3.2# CommitmentTypeIndication"`
	Reason                         string                                  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Reason,omitempty"`
	AllDataObjectsTimeStamp        []TimeStampValidityType                 `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# AllDataObjectsTimeStamp"`
	IndividualDataObjectsTimeStamp []TimeStampValidityType                 `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# IndividualDataObjectsTimeStamp"`
}

type TimeStampValidityType struct {
	Id                      string                      `xml:"Id,attr,omitempty"`
	FormatOK                VerificationResultType      `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# FormatOK"`
	TimeStampContent        *TstContentType             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# TimeStampContent,omitempty"`
	MessageHashAlgorithm    *AlgorithmValidityType      `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# MessageHashAlgorithm,omitempty"`
	SignatureOK             SignatureValidityType       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignatureOK"`
	CertificatePathValidity CertificatePathValidityType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertificatePathValidity"`
}

// Interface for types that extend TimeStampValidityType
type ITimeStampValidityType interface {
	IsVerificationreportTimeStampValidityType()
}

// The type itself implements ITimeStampValidityType
func (TimeStampValidityType) IsVerificationreportTimeStampValidityType() {}

type TstContentType struct {
	TstInfo *dss10core.TstInfo `xml:"urn:oasis:names:tc:dss:1.0:core:schema TstInfo,omitempty"`
	Other   *dss10core.AnyType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Other,omitempty"`
}

type SignatureValidityType struct {
	SigMathOK          VerificationResultType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SigMathOK"`
	SignatureAlgorithm *AlgorithmValidityType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignatureAlgorithm,omitempty"`
}

type AlgorithmValidityType struct {
	Algorithm   string                  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Algorithm"`
	Parameters  *dss10core.AnyType      `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Parameters,omitempty"`
	Suitability *VerificationResultType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Suitability,omitempty"`
}

type CertificatePathValidityType struct {
	PathValiditySummary   VerificationResultType                         `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# PathValiditySummary"`
	CertificateIdentifier xmldsig.X509IssuerSerialType                   `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertificateIdentifier"`
	PathValidityDetail    *CertificatePathValidityVerificationDetailType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# PathValidityDetail,omitempty"`
}

type CertificatePathValidityVerificationDetailType struct {
	CertificateValidity []CertificateValidityType    `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertificateValidity"`
	TSLValidity         *TrustStatusListValidityType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# TSLValidity,omitempty"`
	TrustAnchor         VerificationResultType       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# TrustAnchor"`
}

type CertificateValidityType struct {
	CertificateIdentifier xmldsig.X509IssuerSerialType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertificateIdentifier"`
	Subject               string                       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Subject"`
	ChainingOK            VerificationResultType       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ChainingOK"`
	ValidityPeriodOK      VerificationResultType       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ValidityPeriodOK"`
	ExtensionsOK          VerificationResultType       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ExtensionsOK"`
	CertificateValue      string                       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertificateValue,omitempty"`
	CertificateContent    *CertificateContentType      `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertificateContent,omitempty"`
	SignatureOK           SignatureValidityType        `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignatureOK"`
	CertificateStatus     CertificateStatusType        `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertificateStatus"`
}

// Interface for types that extend CertificateValidityType
type ICertificateValidityType interface {
	IsVerificationreportCertificateValidityType()
}

// The type itself implements ICertificateValidityType
func (CertificateValidityType) IsVerificationreportCertificateValidityType() {}

type CertificateContentType struct {
	Version            int                `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Version,omitempty"`
	SerialNumber       int                `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SerialNumber"`
	SignatureAlgorithm string             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignatureAlgorithm"`
	Issuer             string             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Issuer"`
	ValidityPeriod     ValidityPeriodType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ValidityPeriod"`
	Subject            string             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Subject"`
	Extensions         *ExtensionsType    `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Extensions,omitempty"`
}

type CertificateStatusType struct {
	CertStatusOK       VerificationResultType                   `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertStatusOK"`
	RevocationInfo     *CertificateStatusTypeRevocationInfo     `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# RevocationInfo,omitempty"`
	RevocationEvidence *CertificateStatusTypeRevocationEvidence `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# RevocationEvidence,omitempty"`
}

type CRLValidityType struct {
	Id                      string                         `xml:"Id,attr,omitempty"`
	CRLIdentifier           etsi01903132.CRLIdentifierType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CRLIdentifier"`
	CRLValue                string                         `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CRLValue,omitempty"`
	CRLContent              *CRLContentType                `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CRLContent,omitempty"`
	SignatureOK             SignatureValidityType          `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignatureOK"`
	CertificatePathValidity CertificatePathValidityType    `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertificatePathValidity"`
}

// Interface for types that extend CRLValidityType
type ICRLValidityType interface {
	IsVerificationreportCRLValidityType()
}

// The type itself implements ICRLValidityType
func (CRLValidityType) IsVerificationreportCRLValidityType() {}

type CRLContentType struct {
	Version             int                                `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Version,omitempty"`
	Signature           VerificationResultType             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Signature"`
	Issuer              string                             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Issuer"`
	ThisUpdate          string                             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ThisUpdate"`
	NextUpdate          string                             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# NextUpdate,omitempty"`
	RevokedCertificates *CRLContentTypeRevokedCertificates `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# RevokedCertificates,omitempty"`
	CrlExtensions       *ExtensionsType                    `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CrlExtensions,omitempty"`
}

type OCSPValidityType struct {
	Id                      string                          `xml:"Id,attr,omitempty"`
	OCSPIdentifier          etsi01903132.OCSPIdentifierType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# OCSPIdentifier"`
	OCSPValue               string                          `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# OCSPValue,omitempty"`
	OCSPContent             *OCSPContentType                `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# OCSPContent,omitempty"`
	SignatureOK             SignatureValidityType           `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignatureOK"`
	CertificatePathValidity CertificatePathValidityType     `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertificatePathValidity"`
}

// Interface for types that extend OCSPValidityType
type IOCSPValidityType interface {
	IsVerificationreportOCSPValidityType()
}

// The type itself implements IOCSPValidityType
func (OCSPValidityType) IsVerificationreportOCSPValidityType() {}

type OCSPContentType struct {
	Version            int                      `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Version"`
	ResponderID        string                   `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ResponderID"`
	ProducedAt         string                   `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# producedAt"`
	Responses          OCSPContentTypeResponses `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Responses"`
	ResponseExtensions *ExtensionsType          `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ResponseExtensions,omitempty"`
}

type SingleResponseType struct {
	CertID           SingleResponseTypeCertID `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertID"`
	CertStatus       VerificationResultType   `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertStatus"`
	ThisUpdate       string                   `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ThisUpdate"`
	NextUpdate       string                   `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# NextUpdate,omitempty"`
	SingleExtensions *ExtensionsType          `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SingleExtensions,omitempty"`
}

type TrustStatusListValidityType struct {
	TSLTag                   etsi022312.TSLTagType                `xml:"TSLTag,attr"`
	Id                       string                               `xml:"Id,attr,omitempty"`
	SchemeInformation        etsi022312.SchemeInformation         `xml:"http://uri.etsi.org/02231/v2# SchemeInformation"`
	TrustServiceProviderList *etsi022312.TrustServiceProviderList `xml:"http://uri.etsi.org/02231/v2# TrustServiceProviderList,omitempty"`
	SignatureOK              SignatureValidityType                `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignatureOK"`
}

type UnsignedPropertiesType struct {
	Id                           string                                     `xml:"Id,attr,omitempty"`
	UnsignedSignatureProperties  *UnsignedSignaturePropertiesType           `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# UnsignedSignatureProperties,omitempty"`
	UnsignedDataObjectProperties *etsi01903132.UnsignedDataObjectProperties `xml:"http://uri.etsi.org/01903/v1.3.2# UnsignedDataObjectProperties,omitempty"`
	Other                        *dss10core.AnyType                         `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Other,omitempty"`
}

type UnsignedSignaturePropertiesType struct {
	Id                        string                                  `xml:"Id,attr,omitempty"`
	CounterSignature          []SignatureValidityType                 `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CounterSignature"`
	SignatureTimeStamp        []TimeStampValidityType                 `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SignatureTimeStamp"`
	CompleteCertificateRefs   []etsi01903132.CompleteCertificateRefs  `xml:"http://uri.etsi.org/01903/v1.3.2# CompleteCertificateRefs"`
	CompleteRevocationRefs    []etsi01903132.CompleteRevocationRefs   `xml:"http://uri.etsi.org/01903/v1.3.2# CompleteRevocationRefs"`
	AttributeCertificateRefs  []etsi01903132.AttributeCertificateRefs `xml:"http://uri.etsi.org/01903/v1.3.2# AttributeCertificateRefs"`
	AttributeRevocationRefs   []etsi01903132.AttributeRevocationRefs  `xml:"http://uri.etsi.org/01903/v1.3.2# AttributeRevocationRefs"`
	SigAndRefsTimeStamp       []TimeStampValidityType                 `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# SigAndRefsTimeStamp"`
	RefsOnlyTimeStamp         []TimeStampValidityType                 `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# RefsOnlyTimeStamp"`
	CertificateValues         []CertificateValuesType                 `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertificateValues"`
	RevocationValues          []RevocationValuesType                  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# RevocationValues"`
	AttrAuthoritiesCertValues []CertificateValuesType                 `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# AttrAuthoritiesCertValues"`
	AttributeRevocationValues []RevocationValuesType                  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# AttributeRevocationValues"`
	ArchiveTimeStamp          []TimeStampValidityType                 `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ArchiveTimeStamp"`
}

type RevocationValuesType struct {
	Id          string                          `xml:"Id,attr,omitempty"`
	CRLValues   *RevocationValuesTypeCRLValues  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CRLValues,omitempty"`
	OCSPValues  *RevocationValuesTypeOCSPValues `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# OCSPValues,omitempty"`
	OtherValues *dss10core.AnyType              `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# OtherValues,omitempty"`
}

type CertificateValuesType struct {
	Id                          string                    `xml:"Id,attr,omitempty"`
	EncapsulatedX509Certificate []CertificateValidityType `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# EncapsulatedX509Certificate"`
	OtherCertificate            []string                  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# OtherCertificate"`
}

type EvidenceRecordValidityType struct {
	Id                       string                                             `xml:"Id,attr,omitempty"`
	FormatOK                 VerificationResultType                             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# FormatOK"`
	Version                  int                                                `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Version,omitempty"`
	DigestAlgorithm          []AlgorithmValidityType                            `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# DigestAlgorithm"`
	CryptoInfos              *EvidenceRecordValidityTypeCryptoInfos             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CryptoInfos,omitempty"`
	EncryptionInfo           *EvidenceRecordValidityTypeEncryptionInfo          `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# EncryptionInfo,omitempty"`
	ArchiveTimeStampSequence EvidenceRecordValidityTypeArchiveTimeStampSequence `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ArchiveTimeStampSequence"`
}

// Interface for types that extend EvidenceRecordValidityType
type IEvidenceRecordValidityType interface {
	IsVerificationreportEvidenceRecordValidityType()
}

// The type itself implements IEvidenceRecordValidityType
func (EvidenceRecordValidityType) IsVerificationreportEvidenceRecordValidityType() {}

type ArchiveTimeStampValidityType struct {
	Id              string                                       `xml:"Id,attr,omitempty"`
	FormatOK        VerificationResultType                       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# FormatOK"`
	DigestAlgorithm *AlgorithmValidityType                       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# DigestAlgorithm,omitempty"`
	Attributes      *ArchiveTimeStampValidityTypeAttributes      `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Attributes,omitempty"`
	ReducedHashTree *ArchiveTimeStampValidityTypeReducedHashTree `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ReducedHashTree,omitempty"`
	TimeStamp       TimeStampValidityType                        `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# TimeStamp"`
}

type HashValueType struct {
	HashedObject string `xml:"HashedObject,attr,omitempty"`
	HashValue    string `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# HashValue"`
}

type AttributeCertificateContentTypeAttributes struct {
	XMLName   xml.Name        `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Attributes"`
	Attribute []AttributeType `xml:"Attribute"`
}

type CertificateStatusTypeRevocationInfo struct {
	XMLName          xml.Name               `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# RevocationInfo"`
	RevocationDate   string                 `xml:"RevocationDate"`
	RevocationReason VerificationResultType `xml:"RevocationReason"`
}

type CertificateStatusTypeRevocationEvidence struct {
	XMLName       xml.Name                         `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# RevocationEvidence"`
	CRLValidity   *CRLValidityType                 `xml:"CRLValidity,omitempty"`
	CRLReference  *etsi01903132.CRLIdentifierType  `xml:"CRLReference,omitempty"`
	OCSPValidity  *OCSPValidityType                `xml:"OCSPValidity,omitempty"`
	OCSPReference *etsi01903132.OCSPIdentifierType `xml:"OCSPReference,omitempty"`
	Other         *dss10core.AnyType               `xml:"Other,omitempty"`
}

type CRLContentTypeRevokedCertificates struct {
	XMLName            xml.Name         `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# RevokedCertificates"`
	UserCertificate    []int            `xml:"UserCertificate"`
	RevocationDate     []string         `xml:"RevocationDate"`
	CrlEntryExtensions []ExtensionsType `xml:"CrlEntryExtensions"`
}

type OCSPContentTypeResponses struct {
	XMLName        xml.Name             `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Responses"`
	SingleResponse []SingleResponseType `xml:"SingleResponse"`
}

type SingleResponseTypeCertID struct {
	XMLName        xml.Name `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CertID"`
	HashAlgorithm  string   `xml:"HashAlgorithm"`
	IssuerNameHash string   `xml:"IssuerNameHash"`
	IssuerKeyHash  string   `xml:"IssuerKeyHash"`
	SerialNumber   int      `xml:"SerialNumber"`
}

type RevocationValuesTypeCRLValues struct {
	XMLName     xml.Name          `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CRLValues"`
	VerifiedCRL []CRLValidityType `xml:"VerifiedCRL"`
}

type RevocationValuesTypeOCSPValues struct {
	XMLName              xml.Name           `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# OCSPValues"`
	VerifiedOCSPResponse []OCSPValidityType `xml:"VerifiedOCSPResponse"`
}

type EvidenceRecordValidityTypeCryptoInfos struct {
	XMLName   xml.Name        `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# CryptoInfos"`
	Attribute []AttributeType `xml:"Attribute"`
}

type EvidenceRecordValidityTypeEncryptionInfo struct {
	XMLName             xml.Name              `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# EncryptionInfo"`
	EncryptionInfoType  AlgorithmValidityType `xml:"EncryptionInfoType"`
	EncryptionInfoValue dss10core.AnyType     `xml:"EncryptionInfoValue"`
}

type EvidenceRecordValidityTypeArchiveTimeStampSequence struct {
	XMLName               xml.Name                                                                  `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ArchiveTimeStampSequence"`
	ArchiveTimeStampChain []EvidenceRecordValidityTypeArchiveTimeStampSequenceArchiveTimeStampChain `xml:"ArchiveTimeStampChain"`
}

type ArchiveTimeStampValidityTypeAttributes struct {
	XMLName   xml.Name        `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# Attributes"`
	Attribute []AttributeType `xml:"Attribute"`
}

type ArchiveTimeStampValidityTypeReducedHashTree struct {
	XMLName         xml.Name                                                     `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ReducedHashTree"`
	PartialHashTree []ArchiveTimeStampValidityTypeReducedHashTreePartialHashTree `xml:"PartialHashTree"`
}

type EvidenceRecordValidityTypeArchiveTimeStampSequenceArchiveTimeStampChain struct {
	XMLName          xml.Name                       `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ArchiveTimeStampChain"`
	ArchiveTimeStamp []ArchiveTimeStampValidityType `xml:"ArchiveTimeStamp"`
}

type ArchiveTimeStampValidityTypeReducedHashTreePartialHashTree struct {
	XMLName   xml.Name        `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# PartialHashTree"`
	HashValue []HashValueType `xml:"HashValue"`
}
