issuer: http://127.0.0.1:8080
sign_private_key_path: ../secrets/authz-server/sig_prk.pem
enc_public_key_path: ../secrets/authz-server/enc_puk.pem
scopes_supported:
  - zero:register
  - zero:manage
  
oidc_providers:
  - issuer: https://accounts.google.com
    name: Sign in with Google
    logo_uri: https://raw.githubusercontent.com/gematik/zero-lab/main/static/images/signin-with-google-logo.svg
    client_id: 913653743908-9gno87t6gr9k8dqaoidgi4i1k9lbqp3g.apps.googleusercontent.com
    client_secret: ${GOOGLE_OIDC_CLIENT_SECRET}
    redirect_uri: http://127.0.0.1:8080/op-callback
    scopes:
      - openid
      - email
      - profile

gematik_idp:
  - environment: ref
    name: Gematik IDP-Dienst (Ref)
    logo_uri: https://raw.githubusercontent.com/gematik/zero-lab/main/gematik-g.png
    client_id: GEMgemaZeroHfF56gKiR
    redirect_uri: https://zerobin.zt.dev.ccs.gematik.solutions/gemidp-callback
    scopes:
      - openid
      - gmtik-zerotrust-poc
    authenticator_mode: true

clients_policy_path: clients-policy.yaml

metadata_template:
  service_documentation: https://gihub.com/gemazik/zero-lab
  ui_locales_supported: 
    - de
    - en
  # op_policy_uri:
  # op_tos_uri:

oidf_relying_party_path: oidf-relying-party.yaml
