// Code generated by wsdl2openapi; DO NOT EDIT.

pub type ProductInformation = ProductInformationElementType;

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ProductVersionLocal {
    #[serde(rename = "HWVersion")]
    pub hw_version: String,
    #[serde(rename = "FWVersion")]
    pub fw_version: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ProductVersion {
    #[serde(rename = "Local", default, skip_serializing_if = "Option::is_none")]
    pub local: Option<ProductVersionLocal>,
    #[serde(rename = "Central", default, skip_serializing_if = "Option::is_none")]
    pub central: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ProductTypeInformation {
    #[serde(rename = "ProductType")]
    pub product_type: String,
    #[serde(rename = "ProductTypeVersion")]
    pub product_type_version: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ProductIdentification {
    #[serde(rename = "ProductVendorID")]
    pub product_vendor_id: String,
    #[serde(rename = "ProductCode")]
    pub product_code: String,
    #[serde(rename = "ProductVersion")]
    pub product_version: ProductVersion,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ProductMiscellaneous {
    #[serde(rename = "ProductVendorName")]
    pub product_vendor_name: String,
    #[serde(rename = "ProductName")]
    pub product_name: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Deserialize)]
pub struct ProductInformationElementType {
    #[serde(rename = "InformationDate")]
    pub information_date: String,
    #[serde(rename = "ProductTypeInformation")]
    pub product_type_information: ProductTypeInformation,
    #[serde(rename = "ProductIdentification")]
    pub product_identification: ProductIdentification,
    #[serde(rename = "ProductMiscellaneous")]
    pub product_miscellaneous: ProductMiscellaneous,
}
