#!/usr/bin/env bash
# A TEST-ONLY IDP-Dienst signer for the ti-idpd tests: a brainpoolP256r1 key and a
# self-signed C.FD.SIG-like certificate (role oid_idpd in an admission statement, as
# gematik's IDP certificates carry it). The tests sign discovery documents and
# challenges with it. Random keys: running this again changes both files.
set -euo pipefail
cd "$(dirname "$0")"

cat > ext.cnf <<'CNF'
[idp_sig]
keyUsage = critical, digitalSignature
subjectKeyIdentifier = hash
1.3.36.8.3.3 = ASN1:SEQUENCE:admission_syntax

[admission_syntax]
contents = SEQUENCE:contents_of_admissions
[contents_of_admissions]
admissions = SEQUENCE:admissions
[admissions]
profession_infos = SEQUENCE:profession_infos
[profession_infos]
info = SEQUENCE:profession_info
[profession_info]
items = SEQUENCE:profession_items
oids = SEQUENCE:profession_oids
[profession_items]
item = UTF8String:IDP-Dienst
[profession_oids]
oid = OID:1.2.276.0.76.4.260
CNF

openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:brainpoolP256r1 \
    -pkeyopt ec_param_enc:named_curve -out idp-sig.p8 2>/dev/null
# As SEC1 "EC PRIVATE KEY": what the tests decode.
openssl ec -in idp-sig.p8 -out idp-sig.key 2>/dev/null
rm idp-sig.p8
openssl req -new -key idp-sig.key -subj "/C=DE/O=gematik TEST-ONLY/CN=IDP-Dienst Signer TEST-ONLY" -out idp-sig.csr
openssl x509 -req -in idp-sig.csr -key idp-sig.key -set_serial 7 \
    -not_before 20260101000000Z -not_after 20310101000000Z \
    -extfile ext.cnf -extensions idp_sig -out idp-sig.pem 2>/dev/null
rm idp-sig.csr ext.cnf

{
    echo "# Provenance"
    echo
    echo "Generated by generate.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) with $(openssl version)."
    echo "TEST-ONLY material: a random key and a self-signed certificate, no relation to any IDP."
    echo
    echo "| File | SHA-256 |"
    echo "|---|---|"
    for f in idp-sig.key idp-sig.pem; do
        printf '| `%s` | `%s` |\n' "$f" "$(openssl dgst -sha256 -r "$f" | cut -d' ' -f1)"
    done
} > PROVENANCE.md
