package gempki_test

import (
	"crypto/x509"
	"testing"

	"github.com/gematik/zero-lab/go/gempki"
	"github.com/gematik/zero-lab/go/gempki/internal/testca"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Cross-validation tests against the openssl CLI.
//
// These tests confirm gempki and openssl agree on chain-structural validity
// for both NIST and Brainpool chains. They are NOT integration tests against
// the gematik production endpoints — every chain is generated by testca and
// fully self-contained.
//
// What openssl actually checks: signature chain, validity windows, basic
// constraints, key usage on CAs. What gempki layers on top (role OIDs,
// gematik policies, revocation) is out of scope here — we use a minimal
// Validator with no profile-level checks so the comparison is apples-to-apples.
//
// Skip semantics:
//   - openssl not installed     → all tests skip (RequireOpenSSL).
//   - openssl lacks brainpool   → brainpool-touching tests skip
//                                 (RequireOpenSSLBrainpool).

func TestOpenSSLCross_NIST_HappyPath(t *testing.T) {
	t.Parallel()
	testca.RequireOpenSSL(t)

	pki, err := testca.New()
	require.NoError(t, err)
	rootPath := testca.WritePEMCert(t, "root.pem", pki.RCA7)
	chainPath := testca.WritePEMChain(t, "chain.pem", pki.SubCAKomp)
	leafPath := testca.WritePEMCert(t, "leaf.pem", pki.EEZeta)

	ok, out := testca.OpenSSLVerify(t, leafPath, chainPath, rootPath)
	assert.True(t, ok, "openssl verify NIST happy: %s", out)

	gempkiResult := validateChainBaseline(t, pki.RCA7.Cert, pki.EEZeta.Cert, pki.SubCAKomp.Cert)
	assert.True(t, gempkiResult.Valid, "gempki must agree: %v", gempkiResult.Errors)
}

func TestOpenSSLCross_Brainpool_HappyPath(t *testing.T) {
	t.Parallel()
	testca.RequireOpenSSLBrainpool(t)

	pki, err := testca.New()
	require.NoError(t, err)
	rootPath := testca.WritePEMCert(t, "root.pem", pki.RCA1)
	chainPath := testca.WritePEMChain(t, "chain.pem", pki.SubCAHBA)
	leafPath := testca.WritePEMCert(t, "leaf.pem", pki.EEArzt)

	ok, out := testca.OpenSSLVerify(t, leafPath, chainPath, rootPath)
	assert.True(t, ok, "openssl verify Brainpool happy: %s", out)

	gempkiResult := validateChainBaseline(t, pki.RCA1.Cert, pki.EEArzt.Cert, pki.SubCAHBA.Cert)
	assert.True(t, gempkiResult.Valid, "gempki must agree: %v", gempkiResult.Errors)
}

func TestOpenSSLCross_MixedCurve_HappyPath(t *testing.T) {
	t.Parallel()
	testca.RequireOpenSSLBrainpool(t)

	// Brainpool root → Brainpool SubCA → NIST EE.
	pki, err := testca.New()
	require.NoError(t, err)
	rootPath := testca.WritePEMCert(t, "root.pem", pki.RCA1)
	chainPath := testca.WritePEMChain(t, "chain.pem", pki.SubCAMixed)
	leafPath := testca.WritePEMCert(t, "leaf.pem", pki.EEMixed)

	ok, out := testca.OpenSSLVerify(t, leafPath, chainPath, rootPath)
	assert.True(t, ok, "openssl verify mixed-curve happy: %s", out)

	gempkiResult := validateChainBaseline(t, pki.RCA1.Cert, pki.EEMixed.Cert, pki.SubCAMixed.Cert)
	assert.True(t, gempkiResult.Valid, "gempki must agree: %v", gempkiResult.Errors)
}

func TestOpenSSLCross_WrongRoot_BothFail(t *testing.T) {
	t.Parallel()
	testca.RequireOpenSSL(t)

	pki, err := testca.New()
	require.NoError(t, err)
	// Trust RCA7 (NIST), but try to verify an EE under RCA1 (brainpool).
	rootPath := testca.WritePEMCert(t, "root.pem", pki.RCA7)
	chainPath := testca.WritePEMChain(t, "chain.pem", pki.SubCAKomp)
	leafPath := testca.WritePEMCert(t, "leaf.pem", pki.EEArzt)

	ok, out := testca.OpenSSLVerify(t, leafPath, chainPath, rootPath)
	assert.False(t, ok, "openssl should reject: %s", out)

	gempkiResult := validateChainBaseline(t, pki.RCA7.Cert, pki.EEArzt.Cert, pki.SubCAKomp.Cert)
	assert.False(t, gempkiResult.Valid, "gempki must agree to reject")
}

func TestOpenSSLCross_RogueRoot_BothFail(t *testing.T) {
	t.Parallel()
	testca.RequireOpenSSL(t)

	pki, err := testca.New()
	require.NoError(t, err)
	// Trust RCA7 (NIST). EERogue chains to RogueRoot, not in trust store.
	rootPath := testca.WritePEMCert(t, "root.pem", pki.RCA7)
	leafPath := testca.WritePEMCert(t, "leaf.pem", pki.EERogue)

	ok, out := testca.OpenSSLVerify(t, leafPath, "", rootPath)
	assert.False(t, ok, "openssl should reject rogue leaf: %s", out)

	gempkiResult := validateChainBaseline(t, pki.RCA7.Cert, pki.EERogue.Cert)
	assert.False(t, gempkiResult.Valid, "gempki must agree to reject")
}

func TestOpenSSLCross_Expired_BothFail(t *testing.T) {
	t.Parallel()
	testca.RequireOpenSSLBrainpool(t)

	pki, err := testca.New()
	require.NoError(t, err)
	rootPath := testca.WritePEMCert(t, "root.pem", pki.RCA1)
	chainPath := testca.WritePEMChain(t, "chain.pem", pki.SubCAHBA)
	leafPath := testca.WritePEMCert(t, "leaf.pem", pki.EEExpired)

	ok, out := testca.OpenSSLVerify(t, leafPath, chainPath, rootPath)
	assert.False(t, ok, "openssl should reject expired leaf: %s", out)

	gempkiResult := validateChainBaseline(t, pki.RCA1.Cert, pki.EEExpired.Cert, pki.SubCAHBA.Cert)
	assert.False(t, gempkiResult.Valid, "gempki must agree to reject")
	assert.True(t, gempkiResult.HasError(gempki.ErrCodeExpired))
}

// validateChainBaseline runs a minimal gempki.Validator (no profile-level
// checks, no revocation) against the given chain so the comparison with
// openssl verify stays at the chain-structural layer.
//
// trustRoot is the only trusted anchor; ee is the leaf; intermediates are
// optional candidate intermediates supplied to BuildChain.
func validateChainBaseline(t *testing.T, trustRoot, ee *x509.Certificate, intermediates ...*x509.Certificate) *gempki.ValidationResult {
	t.Helper()
	ts, err := gempki.NewTrustStore([]*x509.Certificate{trustRoot})
	require.NoError(t, err)
	v := gempki.NewValidator(
		gempki.WithTrustStore(ts),
		gempki.WithRevocationMode(gempki.RevocationModeDisabled),
	)
	chain := append([]*x509.Certificate{ee}, intermediates...)
	result, err := v.Validate(t.Context(), chain)
	require.NoError(t, err)
	return result
}
