// Code generated by wsdl2openapi; DO NOT EDIT.

package connectorcommon50

import (
	"encoding/xml"
	error20 "github.com/gematik/zero-lab/go/kon/api/gematik/tel/error20"
	dss10core "github.com/gematik/zero-lab/go/kon/api/oasis/dss10core"
)

type Status struct {
	XMLName xml.Name       `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	Result  Result         `xml:"Result"`
	Error   *error20.Error `xml:"http://ws.gematik.de/tel/error/v2.0 Error,omitempty"`
}

type Result string

// Enum values for Result
const (
	ResultOk      Result = "OK"
	ResultWarning Result = "Warning"
)

func (v Result) IsValid() bool {
	switch v {
	case ResultOk:
		return true
	case ResultWarning:
		return true
	default:
		return false
	}
}

type WorkplaceIds struct {
	XMLName     xml.Name `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 WorkplaceIds"`
	WorkplaceId []string `xml:"WorkplaceId"`
}

type Connector struct {
	XMLName        xml.Name              `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Connector"`
	VPNTIStatus    ConnectorVPNTIStatus  `xml:"VPNTIStatus"`
	VPNSISStatus   ConnectorVPNSISStatus `xml:"VPNSISStatus"`
	OperatingState OperatingState        `xml:"OperatingState"`
}

type ErrorState struct {
	XMLName        xml.Name `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 ErrorState"`
	ErrorCondition string   `xml:"ErrorCondition"`
	Severity       string   `xml:"Severity"`
	Type           string   `xml:"Type"`
	Value          bool     `xml:"Value"`
	ValidFrom      string   `xml:"ValidFrom"`
}

type Document struct {
	XMLName    xml.Name              `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Document"`
	Id         string                `xml:"ID,attr,omitempty"`
	RefURI     string                `xml:"RefURI,attr,omitempty"`
	RefType    string                `xml:"RefType,attr,omitempty"`
	SchemaRefs string                `xml:"SchemaRefs,attr,omitempty"`
	Base64XML  string                `xml:"Base64XML,omitempty"`
	Base64Data *dss10core.Base64Data `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data,omitempty"`
}

type OperatingState struct {
	XMLName    xml.Name     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 OperatingState"`
	ErrorState []ErrorState `xml:"ErrorState"`
}

type XmlSchema struct {
	XMLName xml.Name `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 XmlSchema"`
	Data    string   `xml:"Data"`
	RefURI  string   `xml:"RefURI"`
}

type XslStylesheet struct {
	XMLName xml.Name `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 XslStylesheet"`
	Data    string   `xml:"Data"`
	RefURI  string   `xml:"RefURI"`
}

type ResultEnum string

// Enum values for ResultEnum
const (
	ResultEnumError   ResultEnum = "ERROR"
	ResultEnumOk      ResultEnum = "OK"
	ResultEnumWarning ResultEnum = "WARNING"
)

func (v ResultEnum) IsValid() bool {
	switch v {
	case ResultEnumError:
		return true
	case ResultEnumOk:
		return true
	case ResultEnumWarning:
		return true
	default:
		return false
	}
}

type AttachmentType struct {
	Data   string `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Data"`
	RefURI string `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 RefURI"`
}

// Interface for types that extend AttachmentType
type IAttachmentType interface {
	IsConnectorCommon50AttachmentType()
}

// The type itself implements IAttachmentType
func (AttachmentType) IsConnectorCommon50AttachmentType() {}

type DocumentType struct {
	Id         string                `xml:"ID,attr,omitempty"`
	RefURI     string                `xml:"RefURI,attr,omitempty"`
	RefType    string                `xml:"RefType,attr,omitempty"`
	SchemaRefs string                `xml:"SchemaRefs,attr,omitempty"`
	Base64XML  string                `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Base64XML,omitempty"`
	Base64Data *dss10core.Base64Data `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data,omitempty"`
}

// extends #/components/schemas/oasis.names.tc.dss10.core/DocumentBaseType
func (DocumentType) IsCoreDocumentBaseType() {}

// Interface for types that extend DocumentType
type IDocumentType interface {
	IsConnectorCommon50DocumentType()
}

// The type itself implements IDocumentType
func (DocumentType) IsConnectorCommon50DocumentType() {}

type ConnectorVPNTIStatus struct {
	XMLName          xml.Name `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 VPNTIStatus"`
	ConnectionStatus string   `xml:"ConnectionStatus"`
	Timestamp        string   `xml:"Timestamp"`
}

type ConnectorVPNSISStatus struct {
	XMLName          xml.Name `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 VPNSISStatus"`
	ConnectionStatus string   `xml:"ConnectionStatus"`
	Timestamp        string   `xml:"Timestamp"`
}
