// Code generated by wsdl2openapi; DO NOT EDIT.

pub type Signature = SignatureType;

pub type SignatureValue = SignatureValueType;

pub type SignedInfo = SignedInfoType;

pub type CanonicalizationMethod = CanonicalizationMethodType;

pub type SignatureMethod = SignatureMethodType;

pub type Reference = ReferenceType;

pub type Transforms = TransformsType;

pub type Transform = TransformType;

pub type DigestMethod = DigestMethodType;

pub type KeyInfo = KeyInfoType;

pub type KeyValue = KeyValueType;

pub type RetrievalMethod = RetrievalMethodType;

pub type X509Data = X509DataType;

pub type PgpData = PgpDataType;

pub type SpkiData = SpkiDataType;

pub type Object = ObjectType;

pub type DsaKeyValue = DsaKeyValueType;

pub type RsaKeyValue = RsaKeyValueType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SignatureType {
    #[serde(rename = "@Id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename(serialize = "ns-xmldsig:SignedInfo", deserialize = "SignedInfo"))]
    pub signed_info: SignedInfo,
    #[serde(rename(
        serialize = "ns-xmldsig:SignatureValue",
        deserialize = "SignatureValue"
    ))]
    pub signature_value: SignatureValue,
    #[serde(
        rename(serialize = "ns-xmldsig:KeyInfo", deserialize = "KeyInfo"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub key_info: Option<KeyInfo>,
    #[serde(
        rename(serialize = "ns-xmldsig:Object", deserialize = "Object"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub object: Vec<Object>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SignatureValueType {
    #[serde(rename = "@Id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "$text")]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SignedInfoType {
    #[serde(rename = "@Id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename(
        serialize = "ns-xmldsig:CanonicalizationMethod",
        deserialize = "CanonicalizationMethod"
    ))]
    pub canonicalization_method: CanonicalizationMethod,
    #[serde(rename(
        serialize = "ns-xmldsig:SignatureMethod",
        deserialize = "SignatureMethod"
    ))]
    pub signature_method: SignatureMethod,
    #[serde(
        rename(serialize = "ns-xmldsig:Reference", deserialize = "Reference"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub reference: Vec<Reference>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct CanonicalizationMethodType {
    #[serde(rename = "@Algorithm")]
    pub algorithm: String,
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SignatureMethodType {
    #[serde(rename = "@Algorithm")]
    pub algorithm: String,
    #[serde(
        rename(
            serialize = "ns-xmldsig:HMACOutputLength",
            deserialize = "HMACOutputLength"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub hmac_output_length: Option<i64>,
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ReferenceType {
    #[serde(rename = "@Id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "@URI", default, skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    #[serde(rename = "@Type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(
        rename(serialize = "ns-xmldsig:Transforms", deserialize = "Transforms"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub transforms: Option<Transforms>,
    #[serde(rename(serialize = "ns-xmldsig:DigestMethod", deserialize = "DigestMethod"))]
    pub digest_method: DigestMethod,
    #[serde(rename(serialize = "ns-xmldsig:DigestValue", deserialize = "DigestValue"))]
    pub digest_value: crate::api::soap::Base64Binary,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TransformsType {
    #[serde(
        rename(serialize = "ns-xmldsig:Transform", deserialize = "Transform"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub transform: Vec<Transform>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TransformType {
    #[serde(rename = "@Algorithm")]
    pub algorithm: String,
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
    #[serde(
        rename(serialize = "ns-xmldsig:XPath", deserialize = "XPath"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub x_path: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct DigestMethodType {
    #[serde(rename = "@Algorithm")]
    pub algorithm: String,
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct KeyInfoType {
    #[serde(rename = "@Id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(
        rename(serialize = "ns-xmldsig:KeyName", deserialize = "KeyName"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub key_name: Vec<String>,
    #[serde(
        rename(serialize = "ns-xmldsig:KeyValue", deserialize = "KeyValue"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub key_value: Vec<KeyValue>,
    #[serde(
        rename(
            serialize = "ns-xmldsig:RetrievalMethod",
            deserialize = "RetrievalMethod"
        ),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub retrieval_method: Vec<RetrievalMethod>,
    #[serde(
        rename(serialize = "ns-xmldsig:X509Data", deserialize = "X509Data"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub x509_data: Vec<X509Data>,
    #[serde(
        rename(serialize = "ns-xmldsig:PGPData", deserialize = "PGPData"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub pgp_data: Vec<PgpData>,
    #[serde(
        rename(serialize = "ns-xmldsig:SPKIData", deserialize = "SPKIData"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub spki_data: Vec<SpkiData>,
    #[serde(
        rename(serialize = "ns-xmldsig:MgmtData", deserialize = "MgmtData"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub mgmt_data: Vec<String>,
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct KeyValueType {
    #[serde(
        rename(serialize = "ns-xmldsig:DSAKeyValue", deserialize = "DSAKeyValue"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dsa_key_value: Option<DsaKeyValue>,
    #[serde(
        rename(serialize = "ns-xmldsig:RSAKeyValue", deserialize = "RSAKeyValue"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub rsa_key_value: Option<RsaKeyValue>,
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct RetrievalMethodType {
    #[serde(rename = "@URI", default, skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    #[serde(rename = "@Type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(
        rename(serialize = "ns-xmldsig:Transforms", deserialize = "Transforms"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub transforms: Option<Transforms>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct X509DataType {
    #[serde(
        rename(
            serialize = "ns-xmldsig:X509IssuerSerial",
            deserialize = "X509IssuerSerial"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x509_issuer_serial: Option<X509IssuerSerialType>,
    #[serde(
        rename(serialize = "ns-xmldsig:X509SKI", deserialize = "X509SKI"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x509_ski: Option<crate::api::soap::Base64Binary>,
    #[serde(
        rename(
            serialize = "ns-xmldsig:X509SubjectName",
            deserialize = "X509SubjectName"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x509_subject_name: Option<String>,
    #[serde(
        rename(
            serialize = "ns-xmldsig:X509Certificate",
            deserialize = "X509Certificate"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x509_certificate: Option<crate::api::soap::Base64Binary>,
    #[serde(
        rename(serialize = "ns-xmldsig:X509CRL", deserialize = "X509CRL"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x509_crl: Option<crate::api::soap::Base64Binary>,
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct X509IssuerSerialType {
    #[serde(rename(
        serialize = "ns-xmldsig:X509IssuerName",
        deserialize = "X509IssuerName"
    ))]
    pub x509_issuer_name: String,
    #[serde(rename(
        serialize = "ns-xmldsig:X509SerialNumber",
        deserialize = "X509SerialNumber"
    ))]
    pub x509_serial_number: i64,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct PgpDataType {
    #[serde(rename(serialize = "ns-xmldsig:PGPKeyID", deserialize = "PGPKeyID"))]
    pub pgp_key_id: crate::api::soap::Base64Binary,
    #[serde(
        rename(serialize = "ns-xmldsig:PGPKeyPacket", deserialize = "PGPKeyPacket"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pgp_key_packet: Option<crate::api::soap::Base64Binary>,
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SpkiDataType {
    #[serde(
        rename(serialize = "ns-xmldsig:SPKISexp", deserialize = "SPKISexp"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub spki_sexp: Vec<crate::api::soap::Base64Binary>,
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ObjectType {
    #[serde(rename = "@Id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "@MimeType", default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[serde(rename = "@Encoding", default, skip_serializing_if = "Option::is_none")]
    pub encoding: Option<String>,
    #[serde(
        rename = "unknownContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_content: Option<crate::api::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct DsaKeyValueType {
    #[serde(rename(serialize = "ns-xmldsig:P", deserialize = "P"))]
    pub p: crate::api::soap::Base64Binary,
    #[serde(rename(serialize = "ns-xmldsig:Q", deserialize = "Q"))]
    pub q: crate::api::soap::Base64Binary,
    #[serde(
        rename(serialize = "ns-xmldsig:G", deserialize = "G"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub g: Option<crate::api::soap::Base64Binary>,
    #[serde(rename(serialize = "ns-xmldsig:Y", deserialize = "Y"))]
    pub y: crate::api::soap::Base64Binary,
    #[serde(
        rename(serialize = "ns-xmldsig:J", deserialize = "J"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub j: Option<crate::api::soap::Base64Binary>,
    #[serde(rename(serialize = "ns-xmldsig:Seed", deserialize = "Seed"))]
    pub seed: crate::api::soap::Base64Binary,
    #[serde(rename(serialize = "ns-xmldsig:PgenCounter", deserialize = "PgenCounter"))]
    pub pgen_counter: crate::api::soap::Base64Binary,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct RsaKeyValueType {
    #[serde(rename(serialize = "ns-xmldsig:Modulus", deserialize = "Modulus"))]
    pub modulus: crate::api::soap::Base64Binary,
    #[serde(rename(serialize = "ns-xmldsig:Exponent", deserialize = "Exponent"))]
    pub exponent: crate::api::soap::Base64Binary,
}
