// Code generated by wsdl2openapi; DO NOT EDIT.

package dss10core

import (
	"encoding/xml"
	saml10assertion "github.com/gematik/zero-lab/go/kon/api/oasis/saml10assertion"
	xmldsig "github.com/gematik/zero-lab/go/kon/api/w3200009/xmldsig"
)

type InputDocuments struct {
	XMLName         xml.Name          `xml:"urn:oasis:names:tc:dss:1.0:core:schema InputDocuments"`
	Document        []Document        `xml:"Document"`
	TransformedData []TransformedData `xml:"TransformedData"`
	DocumentHash    []DocumentHash    `xml:"DocumentHash"`
	Other           []AnyType         `xml:"Other"`
}

type Document struct {
	XMLName             xml.Name             `xml:"urn:oasis:names:tc:dss:1.0:core:schema Document"`
	Id                  string               `xml:"ID,attr,omitempty"`
	RefURI              string               `xml:"RefURI,attr,omitempty"`
	RefType             string               `xml:"RefType,attr,omitempty"`
	SchemaRefs          string               `xml:"SchemaRefs,attr,omitempty"`
	InlineXML           *InlineXMLType       `xml:"InlineXML,omitempty"`
	Base64XML           string               `xml:"Base64XML,omitempty"`
	EscapedXML          string               `xml:"EscapedXML,omitempty"`
	Base64Data          *Base64Data          `xml:"Base64Data,omitempty"`
	AttachmentReference *AttachmentReference `xml:"AttachmentReference,omitempty"`
}

type Base64Data struct {
	XMLName  xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data"`
	MimeType string   `xml:"MimeType,attr,omitempty"`
	CharData string   `xml:"chardata"`
}

type TransformedData struct {
	XMLName        xml.Name            `xml:"urn:oasis:names:tc:dss:1.0:core:schema TransformedData"`
	Id             string              `xml:"ID,attr,omitempty"`
	RefURI         string              `xml:"RefURI,attr,omitempty"`
	RefType        string              `xml:"RefType,attr,omitempty"`
	SchemaRefs     string              `xml:"SchemaRefs,attr,omitempty"`
	WhichReference int                 `xml:"WhichReference,attr,omitempty"`
	Transforms     *xmldsig.Transforms `xml:"http://www.w3.org/2000/09/xmldsig# Transforms,omitempty"`
	Base64Data     Base64Data          `xml:"Base64Data"`
}

// extends #/components/schemas/oasis.names.tc.dss10.core/DocumentBaseType
func (TransformedData) IsCoreDocumentBaseType() {}

type DocumentHash struct {
	XMLName        xml.Name              `xml:"urn:oasis:names:tc:dss:1.0:core:schema DocumentHash"`
	Id             string                `xml:"ID,attr,omitempty"`
	RefURI         string                `xml:"RefURI,attr,omitempty"`
	RefType        string                `xml:"RefType,attr,omitempty"`
	SchemaRefs     string                `xml:"SchemaRefs,attr,omitempty"`
	WhichReference int                   `xml:"WhichReference,attr,omitempty"`
	Transforms     *xmldsig.Transforms   `xml:"http://www.w3.org/2000/09/xmldsig# Transforms,omitempty"`
	DigestMethod   *xmldsig.DigestMethod `xml:"http://www.w3.org/2000/09/xmldsig# DigestMethod,omitempty"`
	DigestValue    string                `xml:"http://www.w3.org/2000/09/xmldsig# DigestValue"`
}

// extends #/components/schemas/oasis.names.tc.dss10.core/DocumentBaseType
func (DocumentHash) IsCoreDocumentBaseType() {}

type SignatureObject struct {
	XMLName         xml.Name           `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureObject"`
	SchemaRefs      string             `xml:"SchemaRefs,attr,omitempty"`
	Signature       *xmldsig.Signature `xml:"http://www.w3.org/2000/09/xmldsig# Signature,omitempty"`
	Timestamp       *Timestamp         `xml:"Timestamp,omitempty"`
	Base64Signature *Base64Signature   `xml:"Base64Signature,omitempty"`
	SignaturePtr    *SignaturePtr      `xml:"SignaturePtr,omitempty"`
	Other           *AnyType           `xml:"Other,omitempty"`
}

type Base64Signature struct {
	XMLName  xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Signature"`
	Type     string   `xml:"Type,attr,omitempty"`
	CharData string   `xml:"chardata"`
}

type SignaturePtr struct {
	XMLName       xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignaturePtr"`
	WhichDocument string   `xml:"WhichDocument,attr,omitempty"`
	XPath         string   `xml:"XPath,attr,omitempty"`
}

type Result struct {
	XMLName       xml.Name                 `xml:"urn:oasis:names:tc:dss:1.0:core:schema Result"`
	ResultMajor   string                   `xml:"ResultMajor"`
	ResultMinor   string                   `xml:"ResultMinor,omitempty"`
	ResultMessage *InternationalStringType `xml:"ResultMessage,omitempty"`
}

type OptionalInputs struct {
	XMLName        xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema OptionalInputs"`
	UnknownContent string
}

type OptionalOutputs struct {
	XMLName        xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema OptionalOutputs"`
	UnknownContent string
}

type ClaimedIdentity struct {
	XMLName        xml.Name                           `xml:"urn:oasis:names:tc:dss:1.0:core:schema ClaimedIdentity"`
	Name           saml10assertion.NameIdentifierType `xml:"Name"`
	SupportingInfo *AnyType                           `xml:"SupportingInfo,omitempty"`
}

type Schemas struct {
	XMLName xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema Schemas"`
	Schema  []Schema `xml:"Schema"`
}

type Schema struct {
	XMLName             xml.Name             `xml:"urn:oasis:names:tc:dss:1.0:core:schema Schema"`
	Id                  string               `xml:"ID,attr,omitempty"`
	RefURI              string               `xml:"RefURI,attr,omitempty"`
	RefType             string               `xml:"RefType,attr,omitempty"`
	SchemaRefs          string               `xml:"SchemaRefs,attr,omitempty"`
	InlineXML           *InlineXMLType       `xml:"InlineXML,omitempty"`
	Base64XML           string               `xml:"Base64XML,omitempty"`
	EscapedXML          string               `xml:"EscapedXML,omitempty"`
	Base64Data          *Base64Data          `xml:"Base64Data,omitempty"`
	AttachmentReference *AttachmentReference `xml:"AttachmentReference,omitempty"`
}

type Response struct {
	XMLName         xml.Name         `xml:"urn:oasis:names:tc:dss:1.0:core:schema Response"`
	RequestID       string           `xml:"RequestID,attr,omitempty"`
	Profile         string           `xml:"Profile,attr"`
	Result          Result           `xml:"Result"`
	OptionalOutputs *OptionalOutputs `xml:"OptionalOutputs,omitempty"`
}

type SignRequest struct {
	XMLName        xml.Name        `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignRequest"`
	RequestID      string          `xml:"RequestID,attr,omitempty"`
	Profile        string          `xml:"Profile,attr,omitempty"`
	OptionalInputs *OptionalInputs `xml:"OptionalInputs,omitempty"`
	InputDocuments *InputDocuments `xml:"InputDocuments,omitempty"`
}

// extends #/components/schemas/oasis.names.tc.dss10.core/RequestBaseType
func (SignRequest) IsCoreRequestBaseType() {}

type SignResponse struct {
	XMLName         xml.Name         `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignResponse"`
	RequestID       string           `xml:"RequestID,attr,omitempty"`
	Profile         string           `xml:"Profile,attr"`
	Result          Result           `xml:"Result"`
	OptionalOutputs *OptionalOutputs `xml:"OptionalOutputs,omitempty"`
	SignatureObject *SignatureObject `xml:"SignatureObject,omitempty"`
}

// extends #/components/schemas/oasis.names.tc.dss10.core/ResponseBaseType
func (SignResponse) IsCoreResponseBaseType() {}

type AddTimestamp struct {
	XMLName xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema AddTimestamp"`
	Type    string   `xml:"Type,attr,omitempty"`
}

type IntendedAudience struct {
	XMLName   xml.Name                             `xml:"urn:oasis:names:tc:dss:1.0:core:schema IntendedAudience"`
	Recipient []saml10assertion.NameIdentifierType `xml:"Recipient"`
}

type KeySelector struct {
	XMLName xml.Name         `xml:"urn:oasis:names:tc:dss:1.0:core:schema KeySelector"`
	KeyInfo *xmldsig.KeyInfo `xml:"http://www.w3.org/2000/09/xmldsig# KeyInfo,omitempty"`
	Other   *AnyType         `xml:"Other,omitempty"`
}

type Properties struct {
	XMLName            xml.Name        `xml:"urn:oasis:names:tc:dss:1.0:core:schema Properties"`
	SignedProperties   *PropertiesType `xml:"SignedProperties,omitempty"`
	UnsignedProperties *PropertiesType `xml:"UnsignedProperties,omitempty"`
}

type Property struct {
	XMLName    xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema Property"`
	Identifier string   `xml:"Identifier"`
	Value      *AnyType `xml:"Value,omitempty"`
}

type IncludeObject struct {
	XMLName                       xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema IncludeObject"`
	WhichDocument                 string   `xml:"WhichDocument,attr,omitempty"`
	HasObjectTagsAndAttributesSet bool     `xml:"hasObjectTagsAndAttributesSet,attr,omitempty"`
	ObjId                         string   `xml:"ObjId,attr,omitempty"`
	CreateReference               bool     `xml:"createReference,attr,omitempty"`
}

type SignaturePlacement struct {
	XMLName                  xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignaturePlacement"`
	WhichDocument            string   `xml:"WhichDocument,attr,omitempty"`
	CreateEnvelopedSignature bool     `xml:"CreateEnvelopedSignature,attr,omitempty"`
	XPathAfter               string   `xml:"XPathAfter,omitempty"`
	XPathFirstChildOf        string   `xml:"XPathFirstChildOf,omitempty"`
}

type DocumentWithSignature struct {
	XMLName  xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema DocumentWithSignature"`
	Document Document `xml:"Document"`
}

type SignedReferences struct {
	XMLName         xml.Name          `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignedReferences"`
	SignedReference []SignedReference `xml:"SignedReference"`
}

type SignedReference struct {
	XMLName       xml.Name            `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignedReference"`
	WhichDocument string              `xml:"WhichDocument,attr"`
	RefURI        string              `xml:"RefURI,attr,omitempty"`
	RefId         string              `xml:"RefId,attr,omitempty"`
	Transforms    *xmldsig.Transforms `xml:"http://www.w3.org/2000/09/xmldsig# Transforms,omitempty"`
}

type VerifyRequest struct {
	XMLName         xml.Name         `xml:"urn:oasis:names:tc:dss:1.0:core:schema VerifyRequest"`
	RequestID       string           `xml:"RequestID,attr,omitempty"`
	Profile         string           `xml:"Profile,attr,omitempty"`
	OptionalInputs  *OptionalInputs  `xml:"OptionalInputs,omitempty"`
	InputDocuments  *InputDocuments  `xml:"InputDocuments,omitempty"`
	SignatureObject *SignatureObject `xml:"SignatureObject,omitempty"`
}

// extends #/components/schemas/oasis.names.tc.dss10.core/RequestBaseType
func (VerifyRequest) IsCoreRequestBaseType() {}

type VerifyResponse struct {
	XMLName         xml.Name         `xml:"urn:oasis:names:tc:dss:1.0:core:schema VerifyResponse"`
	RequestID       string           `xml:"RequestID,attr,omitempty"`
	Profile         string           `xml:"Profile,attr"`
	Result          Result           `xml:"Result"`
	OptionalOutputs *OptionalOutputs `xml:"OptionalOutputs,omitempty"`
}

type VerifyManifestResults struct {
	XMLName        xml.Name         `xml:"urn:oasis:names:tc:dss:1.0:core:schema VerifyManifestResults"`
	ManifestResult []ManifestResult `xml:"ManifestResult"`
}

type ManifestResult struct {
	XMLName        xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema ManifestResult"`
	ReferenceXpath string   `xml:"ReferenceXpath"`
	Status         string   `xml:"Status"`
}

type AdditionalTimeInfo struct {
	XMLName  xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema AdditionalTimeInfo"`
	Type     string   `xml:"Type,attr"`
	Ref      string   `xml:"Ref,attr,omitempty"`
	CharData string   `xml:"chardata"`
}

type VerificationTimeInfo struct {
	XMLName            xml.Name             `xml:"urn:oasis:names:tc:dss:1.0:core:schema VerificationTimeInfo"`
	VerificationTime   string               `xml:"VerificationTime"`
	AdditionalTimeInfo []AdditionalTimeInfo `xml:"AdditionalTimeInfo"`
}

type AdditionalKeyInfo struct {
	XMLName xml.Name        `xml:"urn:oasis:names:tc:dss:1.0:core:schema AdditionalKeyInfo"`
	KeyInfo xmldsig.KeyInfo `xml:"http://www.w3.org/2000/09/xmldsig# KeyInfo"`
}

type ProcessingDetails struct {
	XMLName             xml.Name     `xml:"urn:oasis:names:tc:dss:1.0:core:schema ProcessingDetails"`
	ValidDetail         []DetailType `xml:"ValidDetail"`
	IndeterminateDetail []DetailType `xml:"IndeterminateDetail"`
	InvalidDetail       []DetailType `xml:"InvalidDetail"`
}

type SigningTimeInfo struct {
	XMLName               xml.Name                                  `xml:"urn:oasis:names:tc:dss:1.0:core:schema SigningTimeInfo"`
	SigningTime           string                                    `xml:"SigningTime"`
	SigningTimeBoundaries *SigningTimeInfoTypeSigningTimeBoundaries `xml:"SigningTimeBoundaries,omitempty"`
}

type SignerIdentity struct {
	XMLName       xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignerIdentity"`
	NameQualifier string   `xml:"NameQualifier,attr,omitempty"`
	Format        string   `xml:"Format,attr,omitempty"`
	CharData      string   `xml:"chardata"`
}

type ReturnUpdatedSignature struct {
	XMLName xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema ReturnUpdatedSignature"`
	Type    string   `xml:"Type,attr,omitempty"`
}

type UpdatedSignature struct {
	XMLName         xml.Name        `xml:"urn:oasis:names:tc:dss:1.0:core:schema UpdatedSignature"`
	Type            string          `xml:"Type,attr,omitempty"`
	SignatureObject SignatureObject `xml:"SignatureObject"`
}

type ReturnTransformedDocument struct {
	XMLName        xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema ReturnTransformedDocument"`
	WhichReference int      `xml:"WhichReference,attr"`
}

type TransformedDocument struct {
	XMLName        xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema TransformedDocument"`
	WhichReference int      `xml:"WhichReference,attr"`
	Document       Document `xml:"Document"`
}

type ReturnTimestampedSignature struct {
	XMLName xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema ReturnTimestampedSignature"`
	Type    string   `xml:"Type,attr,omitempty"`
}

type TimestampedSignature struct {
	XMLName         xml.Name        `xml:"urn:oasis:names:tc:dss:1.0:core:schema TimestampedSignature"`
	Type            string          `xml:"Type,attr,omitempty"`
	SignatureObject SignatureObject `xml:"SignatureObject"`
}

type Timestamp struct {
	XMLName               xml.Name           `xml:"urn:oasis:names:tc:dss:1.0:core:schema Timestamp"`
	Signature             *xmldsig.Signature `xml:"http://www.w3.org/2000/09/xmldsig# Signature,omitempty"`
	RFC3161TimeStampToken string             `xml:"RFC3161TimeStampToken,omitempty"`
	Other                 *AnyType           `xml:"Other,omitempty"`
}

type TstInfo struct {
	XMLName      xml.Name                            `xml:"urn:oasis:names:tc:dss:1.0:core:schema TstInfo"`
	SerialNumber int                                 `xml:"SerialNumber"`
	CreationTime string                              `xml:"CreationTime"`
	Policy       string                              `xml:"Policy,omitempty"`
	ErrorBound   string                              `xml:"ErrorBound,omitempty"`
	Ordered      bool                                `xml:"Ordered,omitempty"`
	Tsa          *saml10assertion.NameIdentifierType `xml:"TSA,omitempty"`
}

type RequesterIdentity struct {
	XMLName        xml.Name                           `xml:"urn:oasis:names:tc:dss:1.0:core:schema RequesterIdentity"`
	Name           saml10assertion.NameIdentifierType `xml:"Name"`
	SupportingInfo *AnyType                           `xml:"SupportingInfo,omitempty"`
}

type AttachmentReference struct {
	XMLName      xml.Name             `xml:"urn:oasis:names:tc:dss:1.0:core:schema AttachmentReference"`
	AttRefURI    string               `xml:"AttRefURI,attr,omitempty"`
	MimeType     string               `xml:"MimeType,attr,omitempty"`
	DigestMethod xmldsig.DigestMethod `xml:"http://www.w3.org/2000/09/xmldsig# DigestMethod"`
	DigestValue  string               `xml:"http://www.w3.org/2000/09/xmldsig# DigestValue"`
}

type AnyType struct {
	UnknownContent string
}

// Interface for types that extend AnyType
type IAnyType interface {
	IsCoreAnyType()
}

// The type itself implements IAnyType
func (AnyType) IsCoreAnyType() {}

type InternationalStringType struct {
	Lang     string `xml:"http://www.w3.org/XML/1998/namespace lang,attr,omitempty"`
	CharData string `xml:"chardata"`
}

type DocumentBaseType struct {
	Id         string `xml:"ID,attr,omitempty"`
	RefURI     string `xml:"RefURI,attr,omitempty"`
	RefType    string `xml:"RefType,attr,omitempty"`
	SchemaRefs string `xml:"SchemaRefs,attr,omitempty"`
}

// Interface for types that extend DocumentBaseType
type IDocumentBaseType interface {
	IsCoreDocumentBaseType()
}

// The type itself implements IDocumentBaseType
func (DocumentBaseType) IsCoreDocumentBaseType() {}

type DocumentType struct {
	Id                  string               `xml:"ID,attr,omitempty"`
	RefURI              string               `xml:"RefURI,attr,omitempty"`
	RefType             string               `xml:"RefType,attr,omitempty"`
	SchemaRefs          string               `xml:"SchemaRefs,attr,omitempty"`
	InlineXML           *InlineXMLType       `xml:"urn:oasis:names:tc:dss:1.0:core:schema InlineXML,omitempty"`
	Base64XML           string               `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64XML,omitempty"`
	EscapedXML          string               `xml:"urn:oasis:names:tc:dss:1.0:core:schema EscapedXML,omitempty"`
	Base64Data          *Base64Data          `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data,omitempty"`
	AttachmentReference *AttachmentReference `xml:"urn:oasis:names:tc:dss:1.0:core:schema AttachmentReference,omitempty"`
}

// extends #/components/schemas/oasis.names.tc.dss10.core/DocumentBaseType
func (DocumentType) IsCoreDocumentBaseType() {}

// Interface for types that extend DocumentType
type IDocumentType interface {
	IsCoreDocumentType()
}

// The type itself implements IDocumentType
func (DocumentType) IsCoreDocumentType() {}

type InlineXMLType struct {
	IgnorePIs      bool `xml:"ignorePIs,attr,omitempty"`
	IgnoreComments bool `xml:"ignoreComments,attr,omitempty"`
	UnknownContent string
}

type SchemasType struct {
	Schema []Schema `xml:"urn:oasis:names:tc:dss:1.0:core:schema Schema"`
}

// Interface for types that extend SchemasType
type ISchemasType interface {
	IsCoreSchemasType()
}

// The type itself implements ISchemasType
func (SchemasType) IsCoreSchemasType() {}

type RequestBaseType struct {
	RequestID      string          `xml:"RequestID,attr,omitempty"`
	Profile        string          `xml:"Profile,attr,omitempty"`
	OptionalInputs *OptionalInputs `xml:"urn:oasis:names:tc:dss:1.0:core:schema OptionalInputs,omitempty"`
	InputDocuments *InputDocuments `xml:"urn:oasis:names:tc:dss:1.0:core:schema InputDocuments,omitempty"`
}

// Interface for types that extend RequestBaseType
type IRequestBaseType interface {
	IsCoreRequestBaseType()
}

// The type itself implements IRequestBaseType
func (RequestBaseType) IsCoreRequestBaseType() {}

type ResponseBaseType struct {
	RequestID       string           `xml:"RequestID,attr,omitempty"`
	Profile         string           `xml:"Profile,attr"`
	Result          Result           `xml:"urn:oasis:names:tc:dss:1.0:core:schema Result"`
	OptionalOutputs *OptionalOutputs `xml:"urn:oasis:names:tc:dss:1.0:core:schema OptionalOutputs,omitempty"`
}

// Interface for types that extend ResponseBaseType
type IResponseBaseType interface {
	IsCoreResponseBaseType()
}

// The type itself implements IResponseBaseType
func (ResponseBaseType) IsCoreResponseBaseType() {}

type TimeSignatureInstructionType struct {
	Type                       string `xml:"Type,attr,omitempty"`
	TimeStampTheGivenSignature bool   `xml:"TimeStampTheGivenSignature,attr,omitempty"`
	CharData                   string `xml:"chardata"`
}

// extends #/components/schemas/oasis.names.tc.dss10.core/UpdateSignatureInstructionType
func (TimeSignatureInstructionType) IsCoreUpdateSignatureInstructionType() {}

type UpdateSignatureInstructionType struct {
	Type string `xml:"Type,attr,omitempty"`
}

// Interface for types that extend UpdateSignatureInstructionType
type IUpdateSignatureInstructionType interface {
	IsCoreUpdateSignatureInstructionType()
}

// The type itself implements IUpdateSignatureInstructionType
func (UpdateSignatureInstructionType) IsCoreUpdateSignatureInstructionType() {}

type PropertiesType struct {
	Property []Property `xml:"urn:oasis:names:tc:dss:1.0:core:schema Property"`
}

// Interface for types that extend PropertiesType
type IPropertiesType interface {
	IsCorePropertiesType()
}

// The type itself implements IPropertiesType
func (PropertiesType) IsCorePropertiesType() {}

type VerifyManifestResultsType struct {
	ManifestResult []ManifestResult `xml:"urn:oasis:names:tc:dss:1.0:core:schema ManifestResult"`
}

// Interface for types that extend VerifyManifestResultsType
type IVerifyManifestResultsType interface {
	IsCoreVerifyManifestResultsType()
}

// The type itself implements IVerifyManifestResultsType
func (VerifyManifestResultsType) IsCoreVerifyManifestResultsType() {}

type UseVerificationTimeType struct {
	CurrentTime    string `xml:"urn:oasis:names:tc:dss:1.0:core:schema CurrentTime,omitempty"`
	SpecificTime   string `xml:"urn:oasis:names:tc:dss:1.0:core:schema SpecificTime,omitempty"`
	UnknownContent string
}

// Interface for types that extend UseVerificationTimeType
type IUseVerificationTimeType interface {
	IsCoreUseVerificationTimeType()
}

// The type itself implements IUseVerificationTimeType
func (UseVerificationTimeType) IsCoreUseVerificationTimeType() {}

type AdditionalTimeInfoType struct {
	Type     string `xml:"Type,attr"`
	Ref      string `xml:"Ref,attr,omitempty"`
	CharData string `xml:"chardata"`
}

// Interface for types that extend AdditionalTimeInfoType
type IAdditionalTimeInfoType interface {
	IsCoreAdditionalTimeInfoType()
}

// The type itself implements IAdditionalTimeInfoType
func (AdditionalTimeInfoType) IsCoreAdditionalTimeInfoType() {}

type VerificationTimeInfoType struct {
	VerificationTime   string               `xml:"urn:oasis:names:tc:dss:1.0:core:schema VerificationTime"`
	AdditionalTimeInfo []AdditionalTimeInfo `xml:"urn:oasis:names:tc:dss:1.0:core:schema AdditionalTimeInfo"`
}

// Interface for types that extend VerificationTimeInfoType
type IVerificationTimeInfoType interface {
	IsCoreVerificationTimeInfoType()
}

// The type itself implements IVerificationTimeInfoType
func (VerificationTimeInfoType) IsCoreVerificationTimeInfoType() {}

type DetailType struct {
	Type           string                   `xml:"Type,attr"`
	Code           string                   `xml:"urn:oasis:names:tc:dss:1.0:core:schema Code,omitempty"`
	Message        *InternationalStringType `xml:"urn:oasis:names:tc:dss:1.0:core:schema Message,omitempty"`
	UnknownContent string
}

type SigningTimeInfoType struct {
	SigningTime           string                                    `xml:"urn:oasis:names:tc:dss:1.0:core:schema SigningTime"`
	SigningTimeBoundaries *SigningTimeInfoTypeSigningTimeBoundaries `xml:"urn:oasis:names:tc:dss:1.0:core:schema SigningTimeBoundaries,omitempty"`
}

// Interface for types that extend SigningTimeInfoType
type ISigningTimeInfoType interface {
	IsCoreSigningTimeInfoType()
}

// The type itself implements ISigningTimeInfoType
func (SigningTimeInfoType) IsCoreSigningTimeInfoType() {}

type UpdatedSignatureType struct {
	Type            string          `xml:"Type,attr,omitempty"`
	SignatureObject SignatureObject `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureObject"`
}

// Interface for types that extend UpdatedSignatureType
type IUpdatedSignatureType interface {
	IsCoreUpdatedSignatureType()
}

// The type itself implements IUpdatedSignatureType
func (UpdatedSignatureType) IsCoreUpdatedSignatureType() {}

type AttachmentReferenceType struct {
	AttRefURI    string               `xml:"AttRefURI,attr,omitempty"`
	MimeType     string               `xml:"MimeType,attr,omitempty"`
	DigestMethod xmldsig.DigestMethod `xml:"http://www.w3.org/2000/09/xmldsig# DigestMethod"`
	DigestValue  string               `xml:"http://www.w3.org/2000/09/xmldsig# DigestValue"`
}

// Interface for types that extend AttachmentReferenceType
type IAttachmentReferenceType interface {
	IsCoreAttachmentReferenceType()
}

// The type itself implements IAttachmentReferenceType
func (AttachmentReferenceType) IsCoreAttachmentReferenceType() {}

type SigningTimeInfoTypeSigningTimeBoundaries struct {
	XMLName       xml.Name `xml:"urn:oasis:names:tc:dss:1.0:core:schema SigningTimeBoundaries"`
	LowerBoundary string   `xml:"LowerBoundary,omitempty"`
	UpperBoundary string   `xml:"UpperBoundary,omitempty"`
}
