// Code generated by wsdl2openapi go generator. DO NOT EDIT.

package signatureservice74

import (
	"encoding/xml"
	error20 "github.com/gematik/zero-lab/go/kon/api/gematik/tel/error20"
)

type soapOperation struct {
	name        string
	soapAction  string
	bindingType string
}

func (op *soapOperation) Name() string {
	return op.name
}

func (op *soapOperation) SOAPAction() string {
	return op.soapAction
}

func (op *soapOperation) BindingType() string {
	return op.bindingType
}

var OperationVerifyDocument = soapOperation{
	bindingType: "soap11",
	name:        "VerifyDocument",
	soapAction:  "http://ws.gematik.de/conn/SignatureService/v7.4#VerifyDocument",
}

type VerifyDocumentEnvelope struct {
	XMLName        xml.Name        `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	VerifyDocument *VerifyDocument `xml:"Body>VerifyDocument"`
}

func (e *VerifyDocumentEnvelope) IsFault() bool {
	return false
}

type VerifyDocumentResponseEnvelope struct {
	XMLName                xml.Name                `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	VerifyDocumentResponse *VerifyDocumentResponse `xml:"Body>VerifyDocumentResponse"`
	Fault                  *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *VerifyDocumentResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationSignDocument = soapOperation{
	bindingType: "soap11",
	name:        "SignDocument",
	soapAction:  "http://ws.gematik.de/conn/SignatureService/v7.4#SignDocument",
}

type SignDocumentEnvelope struct {
	XMLName      xml.Name      `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	SignDocument *SignDocument `xml:"Body>SignDocument"`
}

func (e *SignDocumentEnvelope) IsFault() bool {
	return false
}

type SignDocumentResponseEnvelope struct {
	XMLName              xml.Name              `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	SignDocumentResponse *SignDocumentResponse `xml:"Body>SignDocumentResponse"`
	Fault                *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *SignDocumentResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationGetJobNumber = soapOperation{
	bindingType: "soap11",
	name:        "GetJobNumber",
	soapAction:  "http://ws.gematik.de/conn/SignatureService/v7.4#GetJobNumber",
}

type GetJobNumberEnvelope struct {
	XMLName      xml.Name      `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetJobNumber *GetJobNumber `xml:"Body>GetJobNumber"`
}

func (e *GetJobNumberEnvelope) IsFault() bool {
	return false
}

type GetJobNumberResponseEnvelope struct {
	XMLName              xml.Name              `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetJobNumberResponse *GetJobNumberResponse `xml:"Body>GetJobNumberResponse"`
	Fault                *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *GetJobNumberResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

var OperationStopSignature = soapOperation{
	bindingType: "soap11",
	name:        "StopSignature",
	soapAction:  "http://ws.gematik.de/conn/SignatureService/v7.4#StopSignature",
}

type StopSignatureEnvelope struct {
	XMLName       xml.Name       `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	StopSignature *StopSignature `xml:"Body>StopSignature"`
}

func (e *StopSignatureEnvelope) IsFault() bool {
	return false
}

type StopSignatureResponseEnvelope struct {
	XMLName               xml.Name               `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	StopSignatureResponse *StopSignatureResponse `xml:"Body>StopSignatureResponse"`
	Fault                 *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *StopSignatureResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}
