// Code generated by wsdl2openapi; DO NOT EDIT.

package signatureservice74

import (
	"encoding/xml"
	connectorcommon50 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/connectorcommon50"
	connectorcontext20 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/connectorcontext20"
	dss10core "github.com/gematik/zero-lab/go/kon/api/oasis/dss10core"
	signaturepolicy "github.com/gematik/zero-lab/go/kon/api/oasis/dssx10profiles/signaturepolicy"
	verificationreport "github.com/gematik/zero-lab/go/kon/api/oasis/dssx10profiles/verificationreport"
)

type SignDocument struct {
	XMLName     xml.Name                   `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 SignDocument"`
	CardHandle  string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	Context     connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	TvMode      TvMode                     `xml:"TvMode"`
	JobNumber   string                     `xml:"JobNumber,omitempty"`
	SignRequest []SignRequest              `xml:"SignRequest"`
}

type SignRequest struct {
	XMLName               xml.Name                   `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 SignRequest"`
	RequestID             string                     `xml:"RequestID,attr"`
	OptionalInputs        *SignRequestOptionalInputs `xml:"OptionalInputs,omitempty"`
	Document              Document                   `xml:"Document"`
	IncludeRevocationInfo bool                       `xml:"IncludeRevocationInfo"`
}

type SignatureSchemes string

// Enum values for SignatureSchemes
const (
	SignatureSchemesRsassaPss      SignatureSchemes = "RSASSA-PSS"
	SignatureSchemesRSASSAPKCS1V15 SignatureSchemes = "RSASSA-PKCS1-v1_5"
)

func (v SignatureSchemes) IsValid() bool {
	switch v {
	case SignatureSchemesRsassaPss:
		return true
	case SignatureSchemesRSASSAPKCS1V15:
		return true
	default:
		return false
	}
}

type DocumentWithSignature struct {
	XMLName    xml.Name              `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 DocumentWithSignature"`
	Id         string                `xml:"ID,attr,omitempty"`
	RefURI     string                `xml:"RefURI,attr,omitempty"`
	RefType    string                `xml:"RefType,attr,omitempty"`
	SchemaRefs string                `xml:"SchemaRefs,attr,omitempty"`
	ShortText  string                `xml:"ShortText,attr,omitempty"`
	Base64XML  string                `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Base64XML,omitempty"`
	Base64Data *dss10core.Base64Data `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data,omitempty"`
}

type SignDocumentResponse struct {
	XMLName      xml.Name       `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 SignDocumentResponse"`
	SignResponse []SignResponse `xml:"SignResponse"`
}

type SignResponse struct {
	XMLName         xml.Name                     `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 SignResponse"`
	RequestID       string                       `xml:"RequestID,attr"`
	Status          connectorcommon50.Status     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	OptionalOutputs *SignResponseOptionalOutputs `xml:"OptionalOutputs,omitempty"`
	SignatureObject *dss10core.SignatureObject   `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureObject,omitempty"`
}

type VerifyDocument struct {
	XMLName               xml.Name                      `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 VerifyDocument"`
	Context               connectorcontext20.Context    `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	TvMode                TvMode                        `xml:"TvMode,omitempty"`
	OptionalInputs        *VerifyDocumentOptionalInputs `xml:"OptionalInputs,omitempty"`
	Document              *Document                     `xml:"Document,omitempty"`
	SignatureObject       *dss10core.SignatureObject    `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureObject,omitempty"`
	IncludeRevocationInfo bool                          `xml:"IncludeRevocationInfo"`
}

type UseVerificationTime struct {
	XMLName        xml.Name `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 UseVerificationTime"`
	CurrentTime    string   `xml:"urn:oasis:names:tc:dss:1.0:core:schema CurrentTime,omitempty"`
	SpecificTime   string   `xml:"urn:oasis:names:tc:dss:1.0:core:schema SpecificTime,omitempty"`
	UnknownContent string
}

type VerifyDocumentResponse struct {
	XMLName            xml.Name                               `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 VerifyDocumentResponse"`
	Status             connectorcommon50.Status               `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	VerificationResult VerificationResultType                 `xml:"VerificationResult"`
	OptionalOutputs    *VerifyDocumentResponseOptionalOutputs `xml:"OptionalOutputs,omitempty"`
}

type GetJobNumber struct {
	XMLName xml.Name                   `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 GetJobNumber"`
	Context connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
}

type GetJobNumberResponse struct {
	XMLName   xml.Name `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 GetJobNumberResponse"`
	JobNumber string   `xml:"JobNumber"`
}

type ExternalAuthenticate struct {
	XMLName        xml.Name                            `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 ExternalAuthenticate"`
	CardHandle     string                              `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	Context        connectorcontext20.Context          `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	OptionalInputs *ExternalAuthenticateOptionalInputs `xml:"OptionalInputs,omitempty"`
	BinaryString   BinaryString                        `xml:"BinaryString"`
}

type ExternalAuthenticateResponse struct {
	XMLName         xml.Name                   `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 ExternalAuthenticateResponse"`
	Status          connectorcommon50.Status   `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	SignatureObject *dss10core.SignatureObject `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureObject,omitempty"`
}

type StopSignature struct {
	XMLName   xml.Name                   `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 StopSignature"`
	Context   connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	JobNumber string                     `xml:"JobNumber"`
}

type StopSignatureResponse struct {
	XMLName xml.Name                 `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 StopSignatureResponse"`
	Status  connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
}

type TvMode string

// Enum values for TvMode
const (
	TvModeNone        TvMode = "NONE"
	TvModeUnconfirmed TvMode = "UNCONFIRMED"
	TvModeConfirmed   TvMode = "CONFIRMED"
)

func (v TvMode) IsValid() bool {
	switch v {
	case TvModeNone:
		return true
	case TvModeUnconfirmed:
		return true
	case TvModeConfirmed:
		return true
	default:
		return false
	}
}

type ViewerInfo struct {
	XMLName        xml.Name                  `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 ViewerInfo"`
	XslStyleSheets *ViewerInfoXslStyleSheets `xml:"XslStyleSheets,omitempty"`
}

type SignatureForm string

// Enum values for SignatureForm
const (
	SignatureFormUrnOasisNamesTcDss10ProfilesAdESFormsBES  SignatureForm = "urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:BES"
	SignatureFormUrnOasisNamesTcDss10ProfilesAdESFormsEST  SignatureForm = "urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:ES-T"
	SignatureFormUrnOasisNamesTcDss10ProfilesAdESFormsESC  SignatureForm = "urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:ES-C"
	SignatureFormUrnOasisNamesTcDss10ProfilesAdESFormsESX  SignatureForm = "urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:ES-X"
	SignatureFormUrnOasisNamesTcDss10ProfilesAdESFormsESXL SignatureForm = "urn:oasis:names:tc:dss:1.0:profiles:AdES:forms:ES-X-L"
)

func (v SignatureForm) IsValid() bool {
	switch v {
	case SignatureFormUrnOasisNamesTcDss10ProfilesAdESFormsBES:
		return true
	case SignatureFormUrnOasisNamesTcDss10ProfilesAdESFormsEST:
		return true
	case SignatureFormUrnOasisNamesTcDss10ProfilesAdESFormsESC:
		return true
	case SignatureFormUrnOasisNamesTcDss10ProfilesAdESFormsESX:
		return true
	case SignatureFormUrnOasisNamesTcDss10ProfilesAdESFormsESXL:
		return true
	default:
		return false
	}
}

type Document struct {
	XMLName    xml.Name              `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 Document"`
	Id         string                `xml:"ID,attr,omitempty"`
	RefURI     string                `xml:"RefURI,attr,omitempty"`
	RefType    string                `xml:"RefType,attr,omitempty"`
	SchemaRefs string                `xml:"SchemaRefs,attr,omitempty"`
	ShortText  string                `xml:"ShortText,attr,omitempty"`
	Base64XML  string                `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Base64XML,omitempty"`
	Base64Data *dss10core.Base64Data `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data,omitempty"`
}

type BinaryString struct {
	XMLName    xml.Name             `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 BinaryString"`
	Id         string               `xml:"ID,attr,omitempty"`
	RefURI     string               `xml:"RefURI,attr,omitempty"`
	RefType    string               `xml:"RefType,attr,omitempty"`
	SchemaRefs string               `xml:"SchemaRefs,attr,omitempty"`
	Base64Data dss10core.Base64Data `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data"`
}

type CounterSignatureMarker struct {
	XMLName                 xml.Name                                        `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 CounterSignatureMarker"`
	SignatureValueReference []CounterSignatureMarkerSignatureValueReference `xml:"SignatureValueReference"`
}

type DisplayableAttributes struct {
	XMLName              xml.Name                                    `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 DisplayableAttributes"`
	DisplayableAttribute []DisplayableAttributesDisplayableAttribute `xml:"DisplayableAttribute"`
}

type DocumentType struct {
	Id         string                `xml:"ID,attr,omitempty"`
	RefURI     string                `xml:"RefURI,attr,omitempty"`
	RefType    string                `xml:"RefType,attr,omitempty"`
	SchemaRefs string                `xml:"SchemaRefs,attr,omitempty"`
	ShortText  string                `xml:"ShortText,attr,omitempty"`
	Base64XML  string                `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Base64XML,omitempty"`
	Base64Data *dss10core.Base64Data `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data,omitempty"`
}

// extends #/components/schemas/de.gematik.ws.conn.ConnectorCommon50/DocumentType
func (DocumentType) IsConnectorCommon50DocumentType() {}

// extends #/components/schemas/oasis.names.tc.dss10.core/DocumentBaseType
func (DocumentType) IsCoreDocumentBaseType() {}

// Interface for types that extend DocumentType
type IDocumentType interface {
	IsSignatureService74DocumentType()
}

// The type itself implements IDocumentType
func (DocumentType) IsSignatureService74DocumentType() {}

type BinaryDocumentType struct {
	Id         string               `xml:"ID,attr,omitempty"`
	RefURI     string               `xml:"RefURI,attr,omitempty"`
	RefType    string               `xml:"RefType,attr,omitempty"`
	SchemaRefs string               `xml:"SchemaRefs,attr,omitempty"`
	Base64Data dss10core.Base64Data `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data"`
}

// extends #/components/schemas/oasis.names.tc.dss10.core/DocumentBaseType
func (BinaryDocumentType) IsCoreDocumentBaseType() {}

// Interface for types that extend BinaryDocumentType
type IBinaryDocumentType interface {
	IsSignatureService74BinaryDocumentType()
}

// The type itself implements IBinaryDocumentType
func (BinaryDocumentType) IsSignatureService74BinaryDocumentType() {}

type VerificationResultType struct {
	HighLevelResult string `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 HighLevelResult"`
	TimestampType   string `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 TimestampType"`
	Timestamp       string `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 Timestamp"`
}

type SignRequestOptionalInputs struct {
	XMLName                      xml.Name                                      `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 OptionalInputs"`
	SignatureType                string                                        `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureType,omitempty"`
	Properties                   *dss10core.Properties                         `xml:"urn:oasis:names:tc:dss:1.0:core:schema Properties,omitempty"`
	IncludeEContent              bool                                          `xml:"IncludeEContent,omitempty"`
	IncludeObjects               *SignRequestOptionalInputsIncludeObjects      `xml:"IncludeObjects,omitempty"`
	SignaturePlacement           *dss10core.SignaturePlacement                 `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignaturePlacement,omitempty"`
	ReturnUpdatedSignature       *dss10core.ReturnUpdatedSignature             `xml:"urn:oasis:names:tc:dss:1.0:core:schema ReturnUpdatedSignature,omitempty"`
	Schemas                      *dss10core.Schemas                            `xml:"urn:oasis:names:tc:dss:1.0:core:schema Schemas,omitempty"`
	GenerateUnderSignaturePolicy *signaturepolicy.GenerateUnderSignaturePolicy `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# GenerateUnderSignaturePolicy,omitempty"`
	ViewerInfo                   *ViewerInfo                                   `xml:"ViewerInfo,omitempty"`
}

type SignResponseOptionalOutputs struct {
	XMLName               xml.Name                               `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 OptionalOutputs"`
	DocumentWithSignature *DocumentWithSignature                 `xml:"DocumentWithSignature,omitempty"`
	VerificationReport    *verificationreport.VerificationReport `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# VerificationReport,omitempty"`
}

type VerifyDocumentOptionalInputs struct {
	XMLName                  xml.Name                                     `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 OptionalInputs"`
	VerifyManifests          string                                       `xml:"VerifyManifests,omitempty"`
	UseVerificationTime      *UseVerificationTime                         `xml:"UseVerificationTime,omitempty"`
	AdditionalKeyInfo        *dss10core.AdditionalKeyInfo                 `xml:"urn:oasis:names:tc:dss:1.0:core:schema AdditionalKeyInfo,omitempty"`
	ReturnVerificationReport *verificationreport.ReturnVerificationReport `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ReturnVerificationReport,omitempty"`
	Schemas                  *dss10core.Schemas                           `xml:"urn:oasis:names:tc:dss:1.0:core:schema Schemas,omitempty"`
	ViewerInfo               *ViewerInfo                                  `xml:"ViewerInfo,omitempty"`
}

type VerifyDocumentResponseOptionalOutputs struct {
	XMLName               xml.Name                               `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 OptionalOutputs"`
	VerifyManifestResults *dss10core.VerifyManifestResults       `xml:"urn:oasis:names:tc:dss:1.0:core:schema VerifyManifestResults,omitempty"`
	DocumentWithSignature *DocumentWithSignature                 `xml:"DocumentWithSignature,omitempty"`
	UpdatedSignature      *dss10core.UpdatedSignature            `xml:"urn:oasis:names:tc:dss:1.0:core:schema UpdatedSignature,omitempty"`
	VerificationReport    *verificationreport.VerificationReport `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# VerificationReport,omitempty"`
}

type ExternalAuthenticateOptionalInputs struct {
	XMLName          xml.Name         `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 OptionalInputs"`
	SignatureType    string           `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureType,omitempty"`
	SignatureSchemes SignatureSchemes `xml:"SignatureSchemes,omitempty"`
}

type ViewerInfoXslStyleSheets struct {
	XMLName       xml.Name                          `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 XslStyleSheets"`
	XslStylesheet []connectorcommon50.XslStylesheet `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 XslStylesheet"`
}

type CounterSignatureMarkerSignatureValueReference struct {
	XMLName xml.Name `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 SignatureValueReference"`
	IdRef   string   `xml:"IdRef,attr,omitempty"`
}

type DisplayableAttributesDisplayableAttribute struct {
	XMLName xml.Name `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 DisplayableAttribute"`
	Key     string   `xml:"Key"`
	Value   string   `xml:"Value"`
}

type SignRequestOptionalInputsIncludeObjects struct {
	XMLName       xml.Name                  `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 IncludeObjects"`
	IncludeObject []dss10core.IncludeObject `xml:"urn:oasis:names:tc:dss:1.0:core:schema IncludeObject"`
}
