// Code generation driver for the brainpoolP256r1 field arithmetic.
//
// Run with: go run generate.go
//
// It produces two files in this directory:
//
//   - bp256_fiat64.go — the modular arithmetic, emitted by Fiat Cryptography
//     (machine-checked Coq → Go). Generated with the pinned fiat-crypto:v0.0.9
//     image, the same image and flags the Go standard library uses for its
//     nistec field elements (see $GOROOT/src/crypto/internal/fips140/nistec/fiat).
//     Build the image once from PROVENANCE.md before running this.
//
//   - bp256_invert.go — field inversion as an addition chain for x^(p-2),
//     emitted by mmcloughlin/addchain.
//
// The hand-written wrapper bp256.go (Element type) is NOT generated; it is
// curve-independent and adapted from the standard library template.

//go:build ignore

package main

import (
	"bytes"
	"go/format"
	"log"
	"os"
	"os/exec"
)

// brainpoolP256r1 field prime p (RFC 5639 §3.4). Passed to fiat-crypto as the
// modulus; it has no special reduction structure, so word-by-word Montgomery is
// the correct synthesizer. fiat-crypto accepts the hex form; addchain wants the
// decimal form, so primeDec carries the same value in base 10.
const (
	prime    = "0xA9FB57DBA1EEA9BC3E660A909D838D726E3BF623D52620282013481D1F6E5377"
	primeDec = "76884956397045344220809746629001649093037950200943055203735601445031516197751"
)

func main() {
	log.Println("Generating bp256_fiat64.go (fiat-crypto:v0.0.9)...")
	cmd := exec.Command("docker", "run", "--rm", "--platform", "linux/amd64",
		"--entrypoint", "word_by_word_montgomery", "fiat-crypto:v0.0.9",
		"--lang", "Go", "--no-wide-int", "--cmovznz-by-mul",
		"--relax-primitive-carry-to-bitwidth", "32,64", "--internal-static",
		"--public-function-case", "camelCase", "--public-type-case", "camelCase",
		"--private-function-case", "camelCase", "--private-type-case", "camelCase",
		"--doc-text-before-function-name", "", "--doc-newline-before-package-declaration",
		"--doc-prepend-header", "Code generated by Fiat Cryptography. DO NOT EDIT.",
		"--package-name", "fiat", "--no-prefix-fiat", "bp256", "64", prime,
		"mul", "square", "add", "sub", "one", "from_montgomery", "to_montgomery",
		"selectznz", "to_bytes", "from_bytes")
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		log.Fatal(err)
	}
	if out, err = format.Source(out); err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("bp256_fiat64.go", out, 0644); err != nil {
		log.Fatal(err)
	}

	log.Println("Generating bp256_invert.go (addchain)...")
	search := exec.Command("addchain", "search", primeDec+" - 2")
	search.Stderr = os.Stderr
	chain, err := search.Output()
	if err != nil {
		log.Fatal(err)
	}
	chainFile, err := os.CreateTemp("", "bp256-addchain")
	if err != nil {
		log.Fatal(err)
	}
	defer os.Remove(chainFile.Name())
	if _, err := chainFile.Write(chain); err != nil {
		log.Fatal(err)
	}
	if err := chainFile.Close(); err != nil {
		log.Fatal(err)
	}
	tmplFile, err := os.CreateTemp("", "bp256-invert-tmpl")
	if err != nil {
		log.Fatal(err)
	}
	defer os.Remove(tmplFile.Name())
	if err := os.WriteFile(tmplFile.Name(), []byte(invertTmpl), 0644); err != nil {
		log.Fatal(err)
	}
	gen := exec.Command("addchain", "gen", "-tmpl", tmplFile.Name(), chainFile.Name())
	gen.Stderr = os.Stderr
	out, err = gen.Output()
	if err != nil {
		log.Fatal(err)
	}
	out = bytes.ReplaceAll(out, []byte("Element"), []byte("Element"))
	if out, err = format.Source(out); err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("bp256_invert.go", out, 0644); err != nil {
		log.Fatal(err)
	}
	log.Println("Done.")
}

const invertTmpl = `// Code generated by {{ .Meta.Name }}. DO NOT EDIT.

package fiat

// Invert sets e = 1/x, and returns e.
//
// If x == 0, Invert returns e = 0.
func (e *Element) Invert(x *Element) *Element {
	// Inversion is implemented as exponentiation with exponent p − 2.
	// The sequence of {{ .Ops.Adds }} multiplications and {{ .Ops.Doubles }} squarings is derived from the
	// following addition chain generated with {{ .Meta.Module }} {{ .Meta.ReleaseTag }}.
	//
	{{- range lines (format .Script) }}
	//	{{ . }}
	{{- end }}
	//

	var z = new(Element).Set(e)
	{{- range .Program.Temporaries }}
	var {{ . }} = new(Element)
	{{- end }}
	{{ range $i := .Program.Instructions -}}
	{{- with add $i.Op }}
	{{ $i.Output }}.Mul({{ .X }}, {{ .Y }})
	{{- end -}}

	{{- with double $i.Op }}
	{{ $i.Output }}.Square({{ .X }})
	{{- end -}}

	{{- with shift $i.Op -}}
	{{- $first := 0 -}}
	{{- if ne $i.Output.Identifier .X.Identifier }}
	{{ $i.Output }}.Square({{ .X }})
	{{- $first = 1 -}}
	{{- end }}
	for s := {{ $first }}; s < {{ .S }}; s++ {
		{{ $i.Output }}.Square({{ $i.Output }})
	}
	{{- end -}}
	{{- end }}

	return e.Set(z)
}
`
