// Code generated by addchain. DO NOT EDIT.

package fiat

// Invert sets e = 1/x, and returns e.
//
// If x == 0, Invert returns e = 0.
func (e *Element) Invert(x *Element) *Element {
	// Inversion is implemented as exponentiation with exponent p − 2.
	// The sequence of 56 multiplications and 251 squarings is derived from the
	// following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
	//
	//	_10      = 2*1
	//	_100     = 2*_10
	//	_101     = 1 + _100
	//	_111     = _10 + _101
	//	_1000    = 1 + _111
	//	_1001    = 1 + _1000
	//	_1111    = _111 + _1000
	//	_10001   = _10 + _1111
	//	_10011   = _10 + _10001
	//	_10101   = _10 + _10011
	//	_10111   = _10 + _10101
	//	_11001   = _10 + _10111
	//	_11101   = _100 + _11001
	//	_11111   = _10 + _11101
	//	_100001  = _10 + _11111
	//	_101001  = _1000 + _100001
	//	_110001  = _1000 + _101001
	//	_110011  = _10 + _110001
	//	_110101  = _10 + _110011
	//	_110111  = _10 + _110101
	//	_111011  = _100 + _110111
	//	_111101  = _10 + _111011
	//	_1010100 = _10111 + _111101
	//	i39      = (_1010100 << 6 + _111101 + _10) << 7 + _110101
	//	i61      = ((i39 << 6 + _11111) << 7 + _110111) << 7
	//	i75      = ((_100001 + i61) << 6 + _111011) << 5 + _10101
	//	i97      = ((i75 << 6 + _10011) << 5 + _1111) << 9
	//	i118     = ((_11111 + i97) << 8 + _110011) << 10 + _10101
	//	i144     = ((i118 << 8 + _100001) << 8 + _111011) << 8
	//	i161     = ((_111 + i144) << 9 + _110101) << 5 + _11001
	//	i186     = ((i161 << 8 + _110111) << 9 + _111011) << 6
	//	i203     = ((_111101 + i186) << 5 + _10001) << 9 + _111101
	//	i230     = ((i203 << 7 + _101001) << 8 + _110001) << 10
	//	i252     = ((_101 + i230) << 6 + 1) << 13 + _10011
	//	i278     = ((i252 << 5 + _1001) << 11 + _11101) << 8
	//	i296     = ((_11111 + i278) << 7 + _110111) << 8 + _101001
	//	return     (i296 << 5 + _10111) << 4 + _101
	//

	var z = new(Element).Set(e)
	var t0 = new(Element)
	var t1 = new(Element)
	var t2 = new(Element)
	var t3 = new(Element)
	var t4 = new(Element)
	var t5 = new(Element)
	var t6 = new(Element)
	var t7 = new(Element)
	var t8 = new(Element)
	var t9 = new(Element)
	var t10 = new(Element)
	var t11 = new(Element)
	var t12 = new(Element)
	var t13 = new(Element)
	var t14 = new(Element)
	var t15 = new(Element)
	var t16 = new(Element)
	var t17 = new(Element)
	var t18 = new(Element)
	var t19 = new(Element)

	t18.Square(x)
	t8.Square(t18)
	z.Mul(x, t8)
	t13.Mul(t18, z)
	t2.Mul(x, t13)
	t5.Mul(x, t2)
	t17.Mul(t13, t2)
	t9.Mul(t18, t17)
	t6.Mul(t18, t9)
	t15.Mul(t18, t6)
	t0.Mul(t18, t15)
	t11.Mul(t18, t0)
	t4.Mul(t8, t11)
	t3.Mul(t18, t4)
	t14.Mul(t18, t3)
	t1.Mul(t2, t14)
	t7.Mul(t2, t1)
	t16.Mul(t18, t7)
	t12.Mul(t18, t16)
	t2.Mul(t18, t12)
	t10.Mul(t8, t2)
	t8.Mul(t18, t10)
	t19.Mul(t0, t8)
	for s := 0; s < 6; s++ {
		t19.Square(t19)
	}
	t19.Mul(t8, t19)
	t18.Mul(t18, t19)
	for s := 0; s < 7; s++ {
		t18.Square(t18)
	}
	t18.Mul(t12, t18)
	for s := 0; s < 6; s++ {
		t18.Square(t18)
	}
	t18.Mul(t3, t18)
	for s := 0; s < 7; s++ {
		t18.Square(t18)
	}
	t18.Mul(t2, t18)
	for s := 0; s < 7; s++ {
		t18.Square(t18)
	}
	t18.Mul(t14, t18)
	for s := 0; s < 6; s++ {
		t18.Square(t18)
	}
	t18.Mul(t10, t18)
	for s := 0; s < 5; s++ {
		t18.Square(t18)
	}
	t18.Mul(t15, t18)
	for s := 0; s < 6; s++ {
		t18.Square(t18)
	}
	t18.Mul(t6, t18)
	for s := 0; s < 5; s++ {
		t18.Square(t18)
	}
	t17.Mul(t17, t18)
	for s := 0; s < 9; s++ {
		t17.Square(t17)
	}
	t17.Mul(t3, t17)
	for s := 0; s < 8; s++ {
		t17.Square(t17)
	}
	t16.Mul(t16, t17)
	for s := 0; s < 10; s++ {
		t16.Square(t16)
	}
	t15.Mul(t15, t16)
	for s := 0; s < 8; s++ {
		t15.Square(t15)
	}
	t14.Mul(t14, t15)
	for s := 0; s < 8; s++ {
		t14.Square(t14)
	}
	t14.Mul(t10, t14)
	for s := 0; s < 8; s++ {
		t14.Square(t14)
	}
	t13.Mul(t13, t14)
	for s := 0; s < 9; s++ {
		t13.Square(t13)
	}
	t12.Mul(t12, t13)
	for s := 0; s < 5; s++ {
		t12.Square(t12)
	}
	t11.Mul(t11, t12)
	for s := 0; s < 8; s++ {
		t11.Square(t11)
	}
	t11.Mul(t2, t11)
	for s := 0; s < 9; s++ {
		t11.Square(t11)
	}
	t10.Mul(t10, t11)
	for s := 0; s < 6; s++ {
		t10.Square(t10)
	}
	t10.Mul(t8, t10)
	for s := 0; s < 5; s++ {
		t10.Square(t10)
	}
	t9.Mul(t9, t10)
	for s := 0; s < 9; s++ {
		t9.Square(t9)
	}
	t8.Mul(t8, t9)
	for s := 0; s < 7; s++ {
		t8.Square(t8)
	}
	t8.Mul(t1, t8)
	for s := 0; s < 8; s++ {
		t8.Square(t8)
	}
	t7.Mul(t7, t8)
	for s := 0; s < 10; s++ {
		t7.Square(t7)
	}
	t7.Mul(z, t7)
	for s := 0; s < 6; s++ {
		t7.Square(t7)
	}
	t7.Mul(x, t7)
	for s := 0; s < 13; s++ {
		t7.Square(t7)
	}
	t6.Mul(t6, t7)
	for s := 0; s < 5; s++ {
		t6.Square(t6)
	}
	t5.Mul(t5, t6)
	for s := 0; s < 11; s++ {
		t5.Square(t5)
	}
	t4.Mul(t4, t5)
	for s := 0; s < 8; s++ {
		t4.Square(t4)
	}
	t3.Mul(t3, t4)
	for s := 0; s < 7; s++ {
		t3.Square(t3)
	}
	t2.Mul(t2, t3)
	for s := 0; s < 8; s++ {
		t2.Square(t2)
	}
	t1.Mul(t1, t2)
	for s := 0; s < 5; s++ {
		t1.Square(t1)
	}
	t0.Mul(t0, t1)
	for s := 0; s < 4; s++ {
		t0.Square(t0)
	}
	z.Mul(z, t0)

	return e.Set(z)
}
