// Code generated by wsdl2openapi; DO NOT EDIT.

pub mod authsignatureservice741;
pub mod cardservice81;
pub mod cardservice812;
pub mod cardservice821;
pub mod cardservicecommon20;
pub mod cardterminalinfo80;
pub mod certificateservice602;
pub mod certificateservicecommon20;
pub mod connectorcommon50;
pub mod connectorcontext20;
pub mod encryptionservice611;
pub mod eventservice72;
pub mod signatureservice74;
pub mod signatureservice75;
