#!/usr/bin/env bash
# TLS test material for the ureq transport, generated by OpenSSL (never by Rust code):
#   ca.pem                P-256 CA, the .kon trust store in CA mode
#   server.pem/-key.pem   Konnektor server certificate, DNS:konnektor.test only
#   other.pem             an unrelated self-signed certificate, a wrong pin
#   client.p12            client certificate and key under ca.pem, password "00"
#   client-nopub.p12      the same without the optional public key in the private key,
#                         as Java keystores and some card vendors write it
# Test-only keys; validity is fixed around 2026 so the files never go stale.
set -euo pipefail
cd "$(dirname "$0")"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
days=(-not_before 20260101000000Z -not_after 20360101000000Z)

openssl ecparam -name prime256v1 -genkey -noout -out "$tmp/ca.key"
openssl req -x509 -new -key "$tmp/ca.key" -subj "/CN=Konnektor Test CA TEST-ONLY" \
    -addext "basicConstraints=critical,CA:TRUE" -addext "keyUsage=critical,keyCertSign" \
    "${days[@]}" -out ca.pem

openssl ecparam -name prime256v1 -genkey -noout -out server-key.pem
openssl req -new -key server-key.pem -subj "/CN=konnektor.test" -out "$tmp/server.csr"
printf 'subjectAltName=DNS:konnektor.test\nbasicConstraints=critical,CA:FALSE\nextendedKeyUsage=serverAuth\n' > "$tmp/server.ext"
openssl x509 -req -in "$tmp/server.csr" -CA ca.pem -CAkey "$tmp/ca.key" -set_serial 2 \
    "${days[@]}" -extfile "$tmp/server.ext" -out server.pem

openssl ecparam -name prime256v1 -genkey -noout -out "$tmp/other.key"
openssl req -x509 -new -key "$tmp/other.key" -subj "/CN=konnektor.test" \
    -addext "subjectAltName=DNS:konnektor.test" -addext "basicConstraints=critical,CA:FALSE" \
    "${days[@]}" -out other.pem

openssl ecparam -name prime256v1 -genkey -noout -out "$tmp/client.key"
openssl req -new -key "$tmp/client.key" -subj "/CN=Clientsystem TEST-ONLY" -out "$tmp/client.csr"
printf 'basicConstraints=critical,CA:FALSE\nextendedKeyUsage=clientAuth\n' > "$tmp/client.ext"
openssl x509 -req -in "$tmp/client.csr" -CA ca.pem -CAkey "$tmp/ca.key" -set_serial 3 \
    "${days[@]}" -extfile "$tmp/client.ext" -out "$tmp/client.pem"
openssl pkcs12 -export -inkey "$tmp/client.key" -in "$tmp/client.pem" -passout pass:00 -out client.p12
openssl ec -in "$tmp/client.key" -no_public -out "$tmp/client-nopub.key" 2>/dev/null
openssl pkcs12 -export -inkey "$tmp/client-nopub.key" -in "$tmp/client.pem" -passout pass:00 -out client-nopub.p12
