// Code generated by wsdl2openapi; DO NOT EDIT.

package cardservice820

import (
	"encoding/base64"
	"encoding/xml"
	cardservicecommon20 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/cardservicecommon20"
	connectorcommon50 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/connectorcommon50"
	connectorcontext20 "github.com/gematik/zero-lab/go/kon/api/gematik/conn/connectorcontext20"
	error20 "github.com/gematik/zero-lab/go/kon/api/gematik/tel/error20"
	dss10core "github.com/gematik/zero-lab/go/kon/api/oasis/dss10core"
)

type Cards struct {
	XMLName xml.Name `xml:"http://ws.gematik.de/conn/CardService/v8.2 Cards"`
	Card    []Card   `xml:"Card"`
}

type Card struct {
	XMLName                   xml.Name                     `xml:"http://ws.gematik.de/conn/CardService/v8.2 Card"`
	CardHandle                string                       `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	CardType                  cardservicecommon20.CardType `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CardType"`
	CardVersion               *CardInfoTypeCardVersion     `xml:"CardVersion,omitempty"`
	Iccsn                     string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 Iccsn,omitempty"`
	CtId                      string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CtId"`
	SlotId                    int                          `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 SlotId"`
	InsertTime                string                       `xml:"InsertTime"`
	CardHolderName            string                       `xml:"CardHolderName,omitempty"`
	Kvnr                      string                       `xml:"Kvnr,omitempty"`
	CertificateExpirationDate string                       `xml:"CertificateExpirationDate,omitempty"`
}

type VerifyPin struct {
	XMLName    xml.Name                   `xml:"http://ws.gematik.de/conn/CardService/v8.2 VerifyPin"`
	Context    connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CardHandle string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	PinTyp     string                     `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinTyp"`
}

type VerifyPinResponse struct {
	XMLName   xml.Name                      `xml:"http://ws.gematik.de/conn/CardService/v8.2 VerifyPinResponse"`
	Status    connectorcommon50.Status      `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	PinResult cardservicecommon20.PinResult `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinResult"`
	LeftTries int                           `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 LeftTries,omitempty"`
}

type ChangePin struct {
	XMLName    xml.Name                   `xml:"http://ws.gematik.de/conn/CardService/v8.2 ChangePin"`
	Context    connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CardHandle string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	PinTyp     string                     `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinTyp"`
}

type ChangePinResponse struct {
	XMLName   xml.Name                      `xml:"http://ws.gematik.de/conn/CardService/v8.2 ChangePinResponse"`
	Status    connectorcommon50.Status      `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	PinResult cardservicecommon20.PinResult `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinResult"`
	LeftTries int                           `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 LeftTries,omitempty"`
}

type GetPinStatus struct {
	XMLName    xml.Name                   `xml:"http://ws.gematik.de/conn/CardService/v8.2 GetPinStatus"`
	Context    connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CardHandle string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	PinTyp     string                     `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinTyp"`
}

type GetPinStatusResponse struct {
	XMLName   xml.Name                 `xml:"http://ws.gematik.de/conn/CardService/v8.2 GetPinStatusResponse"`
	Status    connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	PinStatus PinStatusEnum            `xml:"PinStatus,omitempty"`
	LeftTries int                      `xml:"LeftTries,omitempty"`
}

type UnblockPin struct {
	XMLName    xml.Name                   `xml:"http://ws.gematik.de/conn/CardService/v8.2 UnblockPin"`
	Context    connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CardHandle string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	PinTyp     string                     `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinTyp"`
	SetNewPin  bool                       `xml:"SetNewPin,omitempty"`
}

type UnblockPinResponse struct {
	XMLName   xml.Name                      `xml:"http://ws.gematik.de/conn/CardService/v8.2 UnblockPinResponse"`
	Status    connectorcommon50.Status      `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	PinResult cardservicecommon20.PinResult `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinResult"`
	LeftTries int                           `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 LeftTries,omitempty"`
}

type EnablePin struct {
	XMLName    xml.Name                   `xml:"http://ws.gematik.de/conn/CardService/v8.2 EnablePin"`
	Context    connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CardHandle string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	PinTyp     string                     `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinTyp"`
}

type EnablePinResponse struct {
	XMLName   xml.Name                      `xml:"http://ws.gematik.de/conn/CardService/v8.2 EnablePinResponse"`
	Status    connectorcommon50.Status      `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	PinResult cardservicecommon20.PinResult `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinResult"`
	LeftTries int                           `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 LeftTries,omitempty"`
}

type DisablePin struct {
	XMLName    xml.Name                   `xml:"http://ws.gematik.de/conn/CardService/v8.2 DisablePin"`
	Context    connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CardHandle string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	PinTyp     string                     `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinTyp"`
}

type DisablePinResponse struct {
	XMLName   xml.Name                      `xml:"http://ws.gematik.de/conn/CardService/v8.2 DisablePinResponse"`
	Status    connectorcommon50.Status      `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	PinResult cardservicecommon20.PinResult `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinResult"`
	LeftTries int                           `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 LeftTries,omitempty"`
}

type StartCardSession struct {
	XMLName    xml.Name                   `xml:"http://ws.gematik.de/conn/CardService/v8.2 StartCardSession"`
	Context    connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CardHandle string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
}

type StartCardSessionResponse struct {
	XMLName   xml.Name `xml:"http://ws.gematik.de/conn/CardService/v8.2 StartCardSessionResponse"`
	SessionId string   `xml:"SessionId"`
}

type SecureSendAPDU struct {
	XMLName         xml.Name                  `xml:"http://ws.gematik.de/conn/CardService/v8.2 SecureSendAPDU"`
	TransactionData Base64Bytes               `xml:"TransactionData"`
	SignatureObject dss10core.SignatureObject `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureObject"`
	X509Certificate Base64Bytes               `xml:"http://ws.gematik.de/conn/CertificateServiceCommon/v2.0 X509Certificate"`
}

type SecureSendAPDUResponse struct {
	XMLName           xml.Name                 `xml:"http://ws.gematik.de/conn/CardService/v8.2 SecureSendAPDUResponse"`
	Status            connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	TransactionResult Base64Bytes              `xml:"TransactionResult"`
	TimeSpan          int                      `xml:"TimeSpan"`
}

type StopCardSession struct {
	XMLName   xml.Name `xml:"http://ws.gematik.de/conn/CardService/v8.2 StopCardSession"`
	SessionId string   `xml:"SessionId"`
}

type StopCardSessionResponse struct {
	XMLName xml.Name                 `xml:"http://ws.gematik.de/conn/CardService/v8.2 StopCardSessionResponse"`
	Status  connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
}

type RequestCardResultEnum string

// Enum values for RequestCardResultEnum
const (
	RequestCardResultEnumError           RequestCardResultEnum = "ERROR"
	RequestCardResultEnumOk              RequestCardResultEnum = "OK"
	RequestCardResultEnumAlreadyInserted RequestCardResultEnum = "ALREADY_INSERTED"
)

func (v RequestCardResultEnum) IsValid() bool {
	switch v {
	case RequestCardResultEnumError:
		return true
	case RequestCardResultEnumOk:
		return true
	case RequestCardResultEnumAlreadyInserted:
		return true
	default:
		return false
	}
}

type PinStatusEnum string

// Enum values for PinStatusEnum
const (
	PinStatusEnumVerified     PinStatusEnum = "VERIFIED"
	PinStatusEnumTransportPin PinStatusEnum = "TRANSPORT_PIN"
	PinStatusEnumEmptyPin     PinStatusEnum = "EMPTY_PIN"
	PinStatusEnumBlocked      PinStatusEnum = "BLOCKED"
	PinStatusEnumVerifiable   PinStatusEnum = "VERIFIABLE"
	PinStatusEnumDisabled     PinStatusEnum = "DISABLED"
)

func (v PinStatusEnum) IsValid() bool {
	switch v {
	case PinStatusEnumVerified:
		return true
	case PinStatusEnumTransportPin:
		return true
	case PinStatusEnumEmptyPin:
		return true
	case PinStatusEnumBlocked:
		return true
	case PinStatusEnumVerifiable:
		return true
	case PinStatusEnumDisabled:
		return true
	default:
		return false
	}
}

type CommonStepsEnum string

// Enum values for CommonStepsEnum
const (
	CommonStepsEnumCheckCardHandle          CommonStepsEnum = "CheckCardHandle"
	CommonStepsEnumVerifyPin                CommonStepsEnum = "VerifyPin"
	CommonStepsEnumVerifyEhcPin             CommonStepsEnum = "VerifyEhcPin"
	CommonStepsEnumVerifyHpcPin             CommonStepsEnum = "VerifyHpcPin"
	CommonStepsEnumVerifySmcPin             CommonStepsEnum = "VerifySmcPin"
	CommonStepsEnumWriteToEhc               CommonStepsEnum = "WriteToEhc"
	CommonStepsEnumReadFromEhc              CommonStepsEnum = "ReadFromEhc"
	CommonStepsEnumLogging                  CommonStepsEnum = "Logging"
	CommonStepsEnumCheckEhcBlocking         CommonStepsEnum = "CheckEhcBlocking"
	CommonStepsEnumFullfillAccessConditions CommonStepsEnum = "FullfillAccessConditions"
	CommonStepsEnumCardToCard               CommonStepsEnum = "CardToCard"
)

func (v CommonStepsEnum) IsValid() bool {
	switch v {
	case CommonStepsEnumCheckCardHandle:
		return true
	case CommonStepsEnumVerifyPin:
		return true
	case CommonStepsEnumVerifyEhcPin:
		return true
	case CommonStepsEnumVerifyHpcPin:
		return true
	case CommonStepsEnumVerifySmcPin:
		return true
	case CommonStepsEnumWriteToEhc:
		return true
	case CommonStepsEnumReadFromEhc:
		return true
	case CommonStepsEnumLogging:
		return true
	case CommonStepsEnumCheckEhcBlocking:
		return true
	case CommonStepsEnumFullfillAccessConditions:
		return true
	case CommonStepsEnumCardToCard:
		return true
	default:
		return false
	}
}

type VersionInfoType struct {
	Major    int `xml:"http://ws.gematik.de/conn/CardService/v8.2 Major"`
	Minor    int `xml:"http://ws.gematik.de/conn/CardService/v8.2 Minor"`
	Revision int `xml:"http://ws.gematik.de/conn/CardService/v8.2 Revision"`
}

type CardInfoType struct {
	CardHandle                string                       `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	CardType                  cardservicecommon20.CardType `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CardType"`
	CardVersion               *CardInfoTypeCardVersion     `xml:"http://ws.gematik.de/conn/CardService/v8.2 CardVersion,omitempty"`
	Iccsn                     string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 Iccsn,omitempty"`
	CtId                      string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CtId"`
	SlotId                    int                          `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 SlotId"`
	InsertTime                string                       `xml:"http://ws.gematik.de/conn/CardService/v8.2 InsertTime"`
	CardHolderName            string                       `xml:"http://ws.gematik.de/conn/CardService/v8.2 CardHolderName,omitempty"`
	Kvnr                      string                       `xml:"http://ws.gematik.de/conn/CardService/v8.2 Kvnr,omitempty"`
	CertificateExpirationDate string                       `xml:"http://ws.gematik.de/conn/CardService/v8.2 CertificateExpirationDate,omitempty"`
}

// Interface for types that extend CardInfoType
type ICardInfoType interface {
	IsCardService820CardInfoType()
}

// The type itself implements ICardInfoType
func (CardInfoType) IsCardService820CardInfoType() {}

type CardInfoErrType struct {
	CardHandle                string                       `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	CardType                  cardservicecommon20.CardType `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CardType"`
	CardVersion               *CardInfoErrTypeCardVersion  `xml:"http://ws.gematik.de/conn/CardService/v8.2 CardVersion,omitempty"`
	Iccsn                     string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 Iccsn,omitempty"`
	CtId                      string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CtId"`
	SlotId                    int                          `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 SlotId"`
	InsertTime                string                       `xml:"http://ws.gematik.de/conn/CardService/v8.2 InsertTime"`
	CardHolderName            string                       `xml:"http://ws.gematik.de/conn/CardService/v8.2 CardHolderName,omitempty"`
	Kvnr                      string                       `xml:"http://ws.gematik.de/conn/CardService/v8.2 Kvnr,omitempty"`
	CertificateExpirationDate string                       `xml:"http://ws.gematik.de/conn/CardService/v8.2 CertificateExpirationDate,omitempty"`
	Error                     *error20.Error               `xml:"http://ws.gematik.de/tel/error/v2.0 Error,omitempty"`
}

// extends #/components/schemas/de.gematik.ws.conn.CardService820.CardInfoType
func (CardInfoErrType) IsCardService820CardInfoType() {}

type CardInfoTypeCardVersion struct {
	XMLName              xml.Name         `xml:"http://ws.gematik.de/conn/CardService/v8.2 CardVersion"`
	COSVersion           VersionInfoType  `xml:"COSVersion"`
	ObjectSystemVersion  VersionInfoType  `xml:"ObjectSystemVersion"`
	CardPTPersVersion    *VersionInfoType `xml:"CardPTPersVersion,omitempty"`
	DataStructureVersion *VersionInfoType `xml:"DataStructureVersion,omitempty"`
	LoggingVersion       *VersionInfoType `xml:"LoggingVersion,omitempty"`
	ATRVersion           *VersionInfoType `xml:"ATRVersion,omitempty"`
	GDOVersion           *VersionInfoType `xml:"GDOVersion,omitempty"`
	KeyInfoVersion       *VersionInfoType `xml:"KeyInfoVersion,omitempty"`
}

type CardInfoErrTypeCardVersion struct {
	XMLName              xml.Name         `xml:"http://ws.gematik.de/conn/CardService/v8.2 CardVersion"`
	COSVersion           VersionInfoType  `xml:"COSVersion"`
	ObjectSystemVersion  VersionInfoType  `xml:"ObjectSystemVersion"`
	CardPTPersVersion    *VersionInfoType `xml:"CardPTPersVersion,omitempty"`
	DataStructureVersion *VersionInfoType `xml:"DataStructureVersion,omitempty"`
	LoggingVersion       *VersionInfoType `xml:"LoggingVersion,omitempty"`
	ATRVersion           *VersionInfoType `xml:"ATRVersion,omitempty"`
	GDOVersion           *VersionInfoType `xml:"GDOVersion,omitempty"`
	KeyInfoVersion       *VersionInfoType `xml:"KeyInfoVersion,omitempty"`
}

type Base64Bytes []byte

func (b *Base64Bytes) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var s string
	if err := d.DecodeElement(&s, &start); err != nil {
		return err
	}
	decoded, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		return err
	}
	*b = decoded
	return nil
}

func (b Base64Bytes) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.EncodeElement(base64.StdEncoding.EncodeToString(b), start)
}
